### ISSUE TITLE
[Enhancement][OpenTX 2.1] Add Servo Channel Changer functionality 

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2849] opened 2015-09-08 09:45 UTC
Hi folks,

Since, we can now upgrade internal/external S.Port devices from our radio, would it be possible to also have the SCC feature?
I'm not a software guy, but I'm assuming that the biggest job/code is already done to establish the communication?
It would be very cool to be able to change FLVSS, servo,... ID (specially with the new telemetry system) directly from out radio.

**Comment by kilrah** [comment] 2015-09-08 10:21
Duplicate of #2100.

We don't know the protocol for that at this point.

**Closed by kilrah** 2015-09-08 10:21 UTC

**Comment by LapinFou** [comment] 2015-09-08 10:24
Oops!! Sorry I didn't see #2100
