### ISSUE TITLE
Native Mavlink support in OpenTx 2.1x

### ISSUE THREAD

**Issue by geofrancis** [opentx/opentx#3653] opened 2016-07-06 19:24 UTC
i use openlrs-gitsly with my 9x, 9xr and 9xr pro and taranis they can read native mavlink, directly from my apm/pixhawk using this firmware 
https://github.com/adriano65/opentx-2.0.14

can you port the mavlink changes to opentx 2.1x?

**Comment by kilrah** [comment] 2016-07-06 19:51
Duplicate of #2354

**Closed by kilrah** 2016-07-06 19:51 UTC
