### ISSUE TITLE
Companion performance issue loading a model on latest nightlies

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3128] opened 2015-12-06 09:31 UTC
On my GF's computer which has a Celeron CPU and is running Windows XP I'm having a serious performance issue when loading a model.
Granted, not a power house by modern standards, but it is a decent machine for its purpose.

On Companion 2.1.6 it takes 6 seconds to load a model (just reverted to it and tested).
No problem there, but starting with the nightlies of at least a week ago the loading of a model takes 176 seconds.

That's about 3 minutes one needs to wait before a model is loaded.

Tested with 2.1.6 and 2.1.6N557

**Comment by projectkk2glider** [comment] 2015-12-06 09:50
Duplicate of #3096

**Closed by projectkk2glider** 2015-12-06 09:50 UTC
