### ISSUE TITLE
Throttle trim idle only: affects elevator, not throttle

### ISSUE THREAD

**Issue by peterballen** [opentx/opentx#6039] opened 2018-07-12 19:26 UTC
On X9d+ v2.2.2 (3680b93d), ticking the throttle trim idle only check box in Model Setup affects the elevator trim, not the throttle trim (however I set up the throttle and elevator channels).
I have tried this using both S6R and X6R receivers.
Companion 2.2 shows the correct effect (i.e. throttle trim), but with both receivers, the elevator trim is affected, not the throttle trim.

**Comment by mpaperno** [comment] 2018-07-12 19:29
> ticking the throttle trim idle only check box in Model Setup

In the radio interface, or in Companion, or both?

**Comment by 3djc** [comment] 2018-07-12 19:31
Likely a duplicate of #6032

**Comment by peterballen** [comment] 2018-07-12 19:34
If I tick the checkbox in Companion, it simulates the correct effect. 
If I tick it in the radio interface, or download the eepe/otx from Companion, it shows the incorrect effect with the actual receivers.

**Comment by peterballen** [comment] 2018-07-12 19:35
Yes, I believe it is a duplicate of #6032.

**Comment by peterballen** [comment] 2018-07-12 19:38
Is #6036 the fix for #6032?

**Comment by 3djc** [comment] 2018-07-12 19:40
It will be included in rc5

**Closed as completed by 3djc** 2018-07-12 19:40 UTC
