### ISSUE TITLE
Lua telemetry view blank in case of error

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2683] opened 2015-08-09 16:01 UTC
When there is an error in Lua telemetry script (syntax or out of memory) and that script is selected as as telemetry view, the user gets a blank LCD screen and no feedback. 

We should at leas display something, ideally an exact error that caused the script malfunction.

**Comment by dsbeach** [comment] 2015-09-10 18:14
This is a duplicate of #1914

**Closed** 2015-09-10 18:32 UTC
Labels: enhancement, Lua, Radio Firmware
