### ISSUE TITLE
openTx V2.1.8  log switch as source for input or mixer, companion ok, Taranis not as source

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3632] opened 2016-06-27 04:04 UTC
Hy,
openTx v2.1.8 
At Companion I can select a log switch (L1) as source for inputs or mixer, ok.
transfer programm to Taranis and it works well, I can see L1 as source  On/Off, value 0% , 100%

At Taranis X9dPlus I can't select a log switch (L1) as source for inputs or mixers
no Log switch to selection there is possible

L1 log switch is programmed  simple as  a>x gas -90
L1 is aktiv  (gas -25)

**Comment by kilrah** [comment] 2016-06-27 07:32
Seems OK in mixes? Please confirm/detail...

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/16371951/0dca6694-3c4a-11e6-95bb-538a1aa3fc68.png)

**Comment by r41065** [comment] 2016-06-27 08:42
Yes its OK in Mixes,

only if you want to Use a log. switch as source in Inputs you can select them in Companion , transfer the Model to Taranis and it works.
Select log.switches as source direct in Taranis is not working.

**Comment by r41065** [comment] 2016-06-27 08:52
![screenshot001](https://cloud.githubusercontent.com/assets/15220072/16374089/33cbcb3e-3c55-11e6-8115-6a572f26f0d7.jpg)

**Comment by hrenz** [comment] 2016-06-27 09:02
Hy,
Yes I know, at Companion ok and at Simulator ok, I can select and see L1 at mixer and at Inputs 

But not at Taranis X9DPlus with openTx V2.1.8
cant select log switches L1, L2...

**Comment by kilrah** [comment] 2016-06-27 11:06
Simu and radio should behave the same, and they do here. 

You have entered your LS before trying to choose it, right? The list hides undefined LSs.

**Comment by projectkk2glider** [comment] 2016-06-27 17:05
Confirmed

**Comment by kilrah** [comment] 2016-06-27 17:09
I've got the fix committed locally, just waiting on @hrenz to confirm mentioning the mixer is a mistake of his before pushing.

**Comment by projectkk2glider** [comment] 2016-06-27 17:18
Lua script outputs are also not available, I wonder why.

**Comment by kilrah** [comment] 2016-06-27 17:24
I think there was a reason for that, but I'm not sure anymore...

**Comment by bsongis** [comment] 2016-06-27 17:26
Yes the reason is ... nobody asked

**Comment by kilrah** [comment] 2016-06-27 17:36
I think I remember we said cascading inputs might be a bit too messy, better have things defined locally to avoid confusion, if you want to chain things you rather do it in the mixer

**Comment by r41065** [comment] 2016-06-27 18:31
I think i have to explain:
I'm building ships with Muliple Functions.
For this my biggest Model ( til now) uses 56 Mixing lines for 22 Servo-Outputs
Therefore i was searching a solution to bring a new Function to this Model using less mixing lines.
In Simulator it was well working to put a logical switch as a source to an Input Line and then use only one Mixing Line with the "Slow Motion Functinality" to build the Servo-Output ( without the Jumps in the Output if you change only the mixing lines.).

During Testing I cleared the logical switch in my Taranis and use one of the physical switches.
After that i want to put the LS back into the Input-Line but i can't select it as source again.
( Only in the Input Lines, in Mixing Lines you can select every defined LS ! )

Yesterday evening I asked the people in our German Forum if someone knews about this "Bug"
and h.renz opened this point here.

Best Regards 
Ralf

**Comment by hrenz** [comment] 2016-06-27 18:57
Well I have tested now, at Companion
I have programmed a new Modell, then I programmed 2 log Switches L1, L2,
At Companion  I can select L1, L2 and all other log switches as source of the Input, 
at the simulator I can see  at Inputs the two Log switches  all ok.
I can transmit this programm to Taranis and it works well too.
------
Then I want to progrmm the same the simulator direct.
want to select the L1 or L2 as Input, but there is No log switch to select.
![2016-06-27_203646](https://cloud.githubusercontent.com/assets/6217896/16391849/406c3a82-3ca9-11e6-8e9c-bb6f43ed8d6f.jpg)
![2016-06-27_203419](https://cloud.githubusercontent.com/assets/6217896/16391865/507430c4-3ca9-11e6-9020-047ee009e4e9.jpg)
![2016-06-27_203616](https://cloud.githubusercontent.com/assets/6217896/16391885/6c7c0e90-3ca9-11e6-9c7c-adba478b8e6f.jpg)

see pictures

**Comment by hrenz** [comment] 2016-06-27 19:18
at mixers I can select the L1 or L2 as direct input selection, but not at the type selection menu
switches are there only phys. switches as SA,SB... but no log switches possible.
![2016-06-27_211100](https://cloud.githubusercontent.com/assets/6217896/16392456/4fdb60bc-3cac-11e6-92b1-6dc7bf5eb709.jpg)
![2016-06-27_211136](https://cloud.githubusercontent.com/assets/6217896/16392470/6aef0138-3cac-11e6-99f6-0365a166549a.jpg)

**Comment by kilrah** [comment] 2016-06-27 20:47
There has never been a separate line for logical switches in this menu, they're considered part of "switches". 
Could be an improvement, but it's unrelated.

**Closed** 2016-06-27 20:48 UTC
Labels: Bug, Radio Firmware
