### ISSUE TITLE
Create a new log file when sensors (header) are changed and there is a current log file

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4668] opened 2017-03-22 10:02 UTC
Log files become corrupt / unusable when sensors are added / removed and logging is continued the same day. When altering sensors, could the current log file be renamed so a new log file is created?

**Comment by kilrah** [comment] 2017-03-22 10:09
Duplicate of #2542

**Closed by kilrah** 2017-03-22 10:09 UTC
