### ISSUE TITLE
Limit contrast value in Companion

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5468] opened 2017-12-05 16:56 UTC
Companion 2.2.1N453 / Taranis X7

After converting my eeprom from my Sky9X radio to my new X7radio, i transfered it and get a blank screen after the splash, making the radio unusable.

I realised that it was due to the contrast value imported from the profile of my Sky9x radio (Which is set to "38", and the limit on the X7 is "30")

I don't know if a limit on the Companion field or a security on the firmware (when reading the eeprom value) could avoid that.
Now i know that situation i can correct it quickly, but it take time to understand what's happening the first time.

![image](https://user-images.githubusercontent.com/985702/33619279-0f127ce6-d9e5-11e7-9027-7e72a16ac1fb.png)

**Comment by raphaelcoeffic** [comment] 2017-12-07 06:19
It seems there are two issues here:
- min/max value in "Radio settings" dialog do not correspond to the board's capabilities (X7 has a different range from X9D).
- conversion does not take these values into account either.

**Comment by raphaelcoeffic** [comment] 2017-12-07 11:17
@capitaineflam25 do you have the possibility to compile companion yourself to test the fix?

**Comment by capitaineflam25** [comment] 2017-12-07 11:19
Thanks a lot @raphaelcoeffic 
i compile the firmware but not yet Companion, i'll try to do so and will tell you.

Will it be in tomorrow night build ? (Maybe it will be easyer for me to test)

**Comment by raphaelcoeffic** [comment] 2017-12-07 11:27
@capitaineflam25 in case it gets merged, which would happen faster if you report that it fixes your issue ;-)

**Comment by capitaineflam25** [comment] 2017-12-07 16:46
Companion compiled : i confirm i can't go over 30 for the contrast. If i load an older radio and setting file with an over limit value, it is now displaying "30" on companion.

I guess this is what you expected ? so thanks a lot.

![image](https://user-images.githubusercontent.com/985702/33726728-2408465c-db76-11e7-9ac6-591a5b5eff94.png)

**Comment by raphaelcoeffic** [comment] 2017-12-07 17:47
@capitaineflam25 yes, that’s exactly what it should be. Could you please try to transfer the converted file to the X7 without first opening the radio settings dialog? That should work as well.

**Comment by capitaineflam25** [comment] 2017-12-07 17:57
Unfortunately that is not OK ; 

i load an old converted file on companion with a value of 35 for the contrast

then i flash the radio, and the screen gets blank

if i read back the data from the radio i still can see "30" for the contrast on Companion, but i guess it was truncated after reading it from the radio...

**Comment by raphaelcoeffic** [comment] 2017-12-07 19:05
Exactly, as soon as the settings dialog opens, the value is clipped.

**Comment by raphaelcoeffic** [comment] 2017-12-07 19:56
@capitaineflam25 strange enough.... could you please upload your Sky9X model file? (before the conversion) I could not reproduce it with my X9D profile with contrast set to 45. My X7 would then start with the contrast set to 30.

**Comment by capitaineflam25** [comment] 2017-12-07 20:41
The file was one previously saved from a Companion without your fix.

If i read my sky9x from your latest patched version and write it directly to my X7 i get a darker screen with a contrast set to 30 👍 

So my previous test was not good, the issue is fixed with your new code.

**Closed as completed** 2017-12-07 21:10 UTC
