### ISSUE TITLE
Loosing/Changing Model-windows in the folders. Pics going Picasso?

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4072] opened 2016-11-26 08:41 UTC
Yesterday night about 1h30 I programed my Model 64. When I was ready, I wnat to load another Model to control if all is working, cause sometimes the sytem was hanging. But this time my Model Pictures with names become multicolorpixels and unreadable. When I go back in my ready made model with exit the model was ok. Than I try to load another time and in my folder more and more mocelpics become not readable mixed color windows . If you scroll over the models they become more and more unreadable windows. I was afraid that I loose all my ready made models. So I hold the Switch Off button to close. After new starting th TX all was OK, hopefully. Also I found out that the most hanging problems happen when the battery from TX goes to end of using, but that is not sure. I think so??!! But again not reproduceable, that is the most biggest problem. The Voltage has at this Moment 9.8V. Today I will program more and see what happen else.

**Comment by kilrah** [comment] 2016-11-26 08:57
Looks like your SD card is faulty and that is causing all your issues.

**Comment by Githubbachelor** [comment] 2016-11-26 09:03
I have 3 SD card, doesnt matter which card, on every was a problem. They are the quickest cards you can get. I thin it has to do with Voltage at the end of using the Horus.

**Comment by Githubbachelor** [comment] 2016-11-27 09:27
Last night again same procedure but not reproduceable. look pics. This happen if you have made a new model and you are ready with this. Than you want to make the next model and if the window come with the folder for models one picture has that. If you start to scroll in the folder over the ready made models came more. If you choose the next folder all models hace that pics abo. Look pictures. After you have to switch off the TX and switch on again and is ok.

![20161127_021437](https://cloud.githubusercontent.com/assets/22581690/20647111/0119d7bc-b48c-11e6-81f4-00cc4d917094.jpg)
![20161127_021508](https://cloud.githubusercontent.com/assets/22581690/20647112/011b7720-b48c-11e6-9bc5-15fcb7a6c63a.jpg)
![20161127_021523](https://cloud.githubusercontent.com/assets/22581690/20647113/011c43ee-b48c-11e6-9289-116b43f174d3.jpg)
![20161127_021528](https://cloud.githubusercontent.com/assets/22581690/20647114/011d930c-b48c-11e6-8989-e87f5c8e6b67.jpg)

**Comment by kellybyrd** [comment] 2016-12-12 03:19
Could this be related to #4099 ?

**Comment by Githubbachelor** [comment] 2016-12-12 08:07
No these are two different things

**Comment by projectkk2glider** [comment] 2017-01-14 13:44
I will tag this as duplicate of #4099.

**Closed by projectkk2glider** 2017-01-14 13:44 UTC
Labels: Bug, Horus, Radio Firmware
