### ISSUE TITLE
2.1 : telemetry values not selectable in model scripts

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#2585] opened 2015-07-28 12:52 UTC
I trying to get this to work : https://docs.google.com/document/d/1ILh9lSW4d05qJD2rSKxep0WnJUfNCcAPCafKZeESweE/pub#h.g2ulrfprjwnd

However, in the CUSTOM SCRIPT screen, inputs field, telemetry values cannot be selected, only sticks, switches, logicals but not telemetry by the look of it

**Comment by projectkk2glider** [comment] 2015-07-29 08:15
Duplicate of #2589

**Closed by projectkk2glider** 2015-07-29 08:15 UTC
