### ISSUE TITLE
Companion telemetry conversion for X9D+

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#6798] opened 2019-09-17 11:25 UTC
Conversion from a X9D+ 2.2.4 otx for any model with discovered telemetry displays Mod. **External** in the first 32 telemetry rows and blank for the remainder.
Models with no telemetry the Mod field is blank for all rows as expected.

End of configured sensors
![Screenshot from 2019-09-17 21-01-32](https://user-images.githubusercontent.com/15316949/65036768-849dde00-d98f-11e9-8fc7-9c4f74b431de.png)
Rows 32 onwards
![Screenshot from 2019-09-17 21-02-24](https://user-images.githubusercontent.com/15316949/65036778-8bc4ec00-d98f-11e9-8e4c-a4aee508dccf.png)

For a new model created in 2.3.0RC4 all fields are blank prior to any discovery on the radio. I haven't had a chance to flash the radio with 2.3 to test what is displayed after discovery.

**General information**
 - OpenTX version 2.3.0RC4
 - Hardware Frsky X9D
 - OpenTX Companion 2.3.0RC4 on Ubuntu 18.04)

**Comment by bsongis** [comment] 2019-09-17 14:59
Ah yes I saw it in the pull request and forgot to mention it. If the 3 bits are 1, the origin is "SPORT LINE", not the module given in the first bit. We have only 3 bits for storing the module index + rxId ...

**Comment by raphaelcoeffic** [comment] 2019-09-17 15:24
and how is "external module / third receiver" encoded? the same?

**Comment by bsongis** [comment] 2019-09-17 15:58
External module / First receiver = 100
External module / Second receiver = 101
External module / Third receiver = 110

**Comment by elecpower** [comment] 2019-09-17 21:03
The receivers are bound to the radio's internal module. I assumed the module was the  telemetry source which is external to the radio.

![Screenshot from 2019-09-18 06-58-28](https://user-images.githubusercontent.com/15316949/65079169-e4bd7000-d9e1-11e9-8f64-0b78ca471e60.png)

**Comment by raphaelcoeffic** [comment] 2019-09-17 22:04
@bsongis ok, so Companion should show something like "SPORT" in this case? (instead of a module or receiver?) Or maybe even nothing? (hiding the corresponding fields?)

**Comment by bsongis** [comment] 2019-09-18 06:26
Yes, SPORT (or even nothing) will be perfect

**Comment by raphaelcoeffic** [comment] 2019-09-22 06:42
@bsongis seems we have another problem here.

In the radio conversion, we set the upper 3 bits to 1 in case of XJT PXX1:
```
    if (oldModel.telemetrySensors[i].type == 0 && (oldModel.moduleData[0].type ==  MODULE_TYPE_XJT_PXX1 || oldModel.moduleData[1].type == MODULE_TYPE_XJT_PXX1))
      newModel.telemetrySensors[i].instance = 0xE0 + (oldModel.telemetrySensors[i].instance & 0x1F) - 1;
```

However, in Companion, we don't set these bit, and mask the instance for all PXX1 modules:
```
        if (model.moduleData[0].isPxx1Module() || model.moduleData[1].isPxx1Module())
          sensor.instance = (_instance & 0x1F) + (version <= 218 ? -1 : 0); // 5 bits instance
```

That does not seem to be consistent.

Shouldn't we set these 3 bits for anything but PXX2 modules?

**Comment by raphaelcoeffic** [comment] 2019-09-22 06:55
Further comment: Why do we subtract 1 for sensors with `instance == 0`? I think this is not correct.

**Comment by bsongis** [comment] 2019-09-23 08:26
1) In EEPROM v218 we don't have ACCESS, so writing 0xE0 when the module is PXX1 seems correct. I think the radio conversion is fine.

2) In Companion EEPROM export / import, we split the instance into (instance / rxIdx / moduleIdx)

3) Instance == 0 is impossible for FrSky sensors in 2.2

**Comment by raphaelcoeffic** [comment] 2019-09-23 08:34
> In EEPROM v218 we don't have ACCESS, so writing 0xE0 when the module is PXX1 seems correct. I think the radio conversion is fine.

The question was more: is `MODULE_TYPE_XJT_PXX1` in the radio equivalent to `isPxx1Module()` in companion? I don't think so, is it?

> Instance == 0 is impossible for FrSky sensors in 2.2

What about the disabled/blank sensors? the issue is that the instance is then `!= 0`, and the Companion thinks the sensor is not disabled. So I think we should not "convert" sensors for which the instance `== 0`, right?

**Comment by bsongis** [comment] 2019-09-23 08:42
a disabled sensor should have no name (not instance = 0)

**Comment by bsongis** [comment] 2019-09-23 08:42
you are right about the MODULE_TYPE_XJT_PXX1 comment

**Comment by bsongis** [comment] 2019-09-23 13:30
Fixed in RC5

**Closed as completed by bsongis** 2019-09-23 13:30 UTC
