### ISSUE TITLE
Companion Mix Outputs screen is erratic when displaying values over 100%

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#6103] opened 2018-08-16 13:13 UTC
In Companion, if you create a mix that can reach values over +100% and/or below -100%, the values will display correctly on the MIXERS MONITOR screen of the simulated radio display but not on the Mix Outputs tab of the Radio Outputs window.

Example:

    CH4 I4:Rud Weight(+100%)
     += I2:Ail Weight(+100%)

Run the simulator and enable "Hold Horizontal stick position" for both sticks. Set a stick to its limit on one side and then wiggle the other stick from side to side while watching the Mix Outputs tab of the Radio Outputs window. As you reach the stick limit on the same side that the other stick is on you should get a value of 200%, but you'll get a different value every time you try.

If you also watch MIXERS MONITOR on the simulated radio display, you'll see that it shows the correct values.

**General information**
- OpenTX Companion 2.2.2 set to Taranis X9D+

**Comment by mpaperno** [comment] 2018-08-16 13:22
Duplicate of #6064

**Closed as completed by mpaperno** 2018-08-16 13:22 UTC
