### ISSUE TITLE
VFAS (voltage metric) disappears after a while when using KISS FC?

### ISSUE THREAD

**Issue by b0rski** [opentx/opentx#4507] opened 2017-02-25 00:42 UTC
Hello there,

I was on the first 2.2 release with crossfire support and everything was working until I added a new model with KISS FC. Suddenly I was loosing the most important telemetry metric on all my KISS setups and was getting the sound message "sensor lost" (which I've never heard before) after few seconds. VFAS (battery voltage) is suddenly not being discovered at all. Strangely I get VFAS on my Betaflight rigs.

I'm mainly using FrSky X4R-SB as RX and FrSky Taranis Plus as TX.

I downgraded to Open TX 2.1.9 and then to 2.1.8 but nothing works. VFAS is just missing.

What would be steps to debug and fix this issue?

Kind regards
b0rski

**Comment by kilrah** [comment] 2017-02-25 08:31
This all points to an issue where the FC simply stops sending the values... Did you update its firmware recently? They might have introduced a bug in a recent revision.

Closing this since it's highly unlikely to be an OpenTX problem since you observe the same with several versions and it works with a different FC. We should be receiving the exact same thing with any S-PORT-capable FC, so if it doesn't work with one the problem is with it.
Feel free to reopen if more evidence points the problem is our side.

**Closed by kilrah** 2017-02-25 08:31 UTC
