### ISSUE TITLE
Companion Simulator GVARs Label/Name Confusion (Version 2.2.0N366)

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#4707] opened 2017-03-27 18:04 UTC
[Edit 
Original thread title  Companion Simulator GVARs Not Being Read (Version 2.2.0N366) (#4707)
end May 28th, 2017]
Companion > Edit Model > Flight Modes > FM0 
Any GVAR set a value
Simulate > View > Radio Outputs

**Comment by mpaperno** [comment] 2017-03-28 00:13
Can't reproduce in current `next` code.  Anyone else?  Might need more specifics... radio type, example model file, operating system...

**Comment by RCdiy** [comment] 2017-03-28 01:00
Apologies. 
Taranis Q X7 
Mac
I can make a video.

**Comment by RCdiy** [comment] 2017-03-28 01:02
I open Companion 
New models and settings 
Go through new model wizard 
Then steps from first post

**Comment by 3djc** [comment] 2017-03-28 05:11
Can't replicate either, but when trying too I made a mistake, maybe you do the same : where di you input your gv value ? You should not use the large area (this is for name) but the small one with arrows

![image](https://cloud.githubusercontent.com/assets/5167938/24389955/cd28439a-1385-11e7-9ff6-0ecea0fe7195.png)

**Comment by mpaperno** [comment] 2017-03-28 05:23
Yea, still can't recreate on X7 simulator, even on Mac.... :-/

I made the same mistake with the name/value fields though.  My GVAR was named "10" and value was zero, which I found a bit peculiar for sure.

**Comment by 3djc** [comment] 2017-03-28 05:25
Not urgent, but we could probably havve a look at the size of the field, it is a 'bit' large for the alowed 3 chars :D

**Comment by kilrah** [comment] 2017-03-28 08:20
Hopefully that helps... although it still does require people to read

**Comment by RCdiy** [comment] 2017-03-28 13:34
Apologies:) I do try and be thorough before opening an issue.
Works, but if I set GVAR1 in FM0 is it expected that GVAR1 in all flight modes have the same value?
Also is the simulator output going to later have the GVAR1 labels/names reflected?
![gvar1](https://cloud.githubusercontent.com/assets/20209851/24407682/a2793fbe-1399-11e7-8bc5-cf2efa890b40.png)
![simouts](https://cloud.githubusercontent.com/assets/20209851/24407688/a66e68c4-1399-11e7-9a78-09d936ba95ef.png)

**Comment by projectkk2glider** [comment] 2017-03-28 13:45
What you have there is that by default gvar value uses value from FM0 for all other flight modes. You can change that of course, but that is the default.

**Comment by 3djc** [comment] 2017-03-28 14:18
Gvar has been given a column names already, available in next RC. Closing this as this is not an open issue anymore I think

**Closed by 3djc** 2017-03-28 14:18 UTC
Labels: Needs more data
