### ISSUE TITLE
2.2.1 doesn't work with simulator

### ISSUE THREAD

**Issue by S-T-A** [opentx/opentx#5704] opened 2018-02-19 18:02 UTC
i have my radio properly configured it worked before this update. Also once the USB is plugged in, I can't change or select a diffrent model it use to work on DRL and i was tring to get it to work on lift off now i stooged my self:(

**Comment by kilrah** [comment] 2018-02-19 19:26
Duplicate of #5703, don't spam.

**Closed as completed by kilrah** 2018-02-19 19:26 UTC
