### ISSUE TITLE
companion 2.2 N371 crash

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4959] opened 2017-05-28 07:52 UTC
Systematic crash trying to open this file.
[9XR-28052017.zip](https://github.com/opentx/opentx/files/1034016/9XR-28052017.zip)

I have a X9D profile, I tryed to convert a model to a 9XR PRO profile. It gaves errors.

**Comment by schwabe** [comment] 2017-05-28 08:01
I cannot reproduce the crash on OS X. Does it crash when just opening the file?

**Comment by benoit35690** [comment] 2017-05-28 09:01
Yes, Companion has crashed 3 times with same file, now it does not crash anymore...

**Comment by benoit35690** [comment] 2017-05-28 09:15
Actually it crashes when trying to open the model "Claire"

**Comment by schwabe** [comment] 2017-05-29 16:19
should be closed by #4963

**Closed as completed by schwabe** 2017-05-29 16:19 UTC
