### ISSUE TITLE
Bug in flash code

### ISSUE THREAD

**Issue by ledvinap** [opentx/opentx#3684] opened 2016-08-03 14:45 UTC
condition is almost certainly wrong - `!` has priority, `&` will always evaluate to false.

https://github.com/opentx/opentx/blob/master/radio/src/targets/taranis/flash_driver.cpp#L20

**Comment by schwabe** [comment] 2016-08-03 14:53
Duplicate of pull request #3681

**Closed by schwabe** 2016-08-03 14:53 UTC
