### ISSUE TITLE
Open TX companion

### ISSUE THREAD

**Issue by ginney54** [opentx/opentx#2030] opened 2015-01-19 03:30 UTC
Running win 7 Dell OpenTX unable to check for updates. Will not download firmware. Works ok on my work Dell running Win8. Headbanger.

**Comment by kilrah** [comment] 2015-01-19 06:03
What companion version? 
If the same version works fine on another computer the problem is likely with the computer.

**Comment by ginney54** [comment] 2015-01-19 22:25
Thanks Andre both have the latest version, must be the computer but can’t get it sorted. I will keep looking. I have flashed the Taranis Plus using the file that downloaded from the working PC. Have looked at firewalls and cleared all cache.
Mystery. I will let you know if I get it fixed.
Greg

**Comment by projectkk2glider** [comment] 2015-02-28 20:54
No feedback, closing.

**Closed by projectkk2glider** 2015-02-28 20:54 UTC
