### ISSUE TITLE
OpenTX 2.1.6 / 9XR pro Telemetry Sensors have wrong units in Logical Switches

### ISSUE THREAD

**Issue by mikeller** [opentx/opentx#3133] opened 2015-12-06 20:02 UTC
The first sensor has correct units, for all others, the units do not seem to be correctly aligned in their respective arrays, with the units not being shifted to accommodate for the [sensor]+ and [sensor]- entries that are inserted after the respective [sensor] entry.

This only affects Logical Switches when set up on the TX itself, all works fine when setting up Logical Switches in the simulator.

**Comment by projectkk2glider** [comment] 2015-12-07 05:52
Duplicate of #3071?

**Comment by kilrah** [comment] 2015-12-07 06:39
Yup most likely.

**Closed by kilrah** 2015-12-07 06:39 UTC

**Comment by mikeller** [comment] 2015-12-08 09:52
Yes, seems to have been a duplicate. Built from master, units in logical switches now work as they should.
