### ISSUE TITLE
Opentx 2.2 RC10 Channel selection order X7

### ISSUE THREAD

**Issue by dkuenzi1** [opentx/opentx#4524] opened 2017-02-27 23:27 UTC
It appears that you cannot change the channel order from the default TAER to anything else. When scrolling through page one of the radio setup menu, it just wont let you select the channel order selection field.
I've tried changing this setting to a different default using a firmware update from Companion 2.2

**Comment by schwabe** [comment] 2017-03-01 11:52
Duplicate of #4490, will be fixed in RC11

**Closed by schwabe** 2017-03-01 11:52 UTC
