### ISSUE TITLE
[LUA/X10] drawing text with y>LCD_H crashes the TX

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#5359] opened 2017-11-13 22:31 UTC
Executing this script on the X10 will crash (emergency mode) the TX:
```
local function run_func()
  lcd.drawText(1,260,"Hello")
end

return { run=run_func }
```

**Comment by raphaelcoeffic** [comment] 2017-11-13 22:32
sorry gentlemen, I'm just too sleepy to fix that today...

**Comment by raphaelcoeffic** [comment] 2017-11-13 22:38
Forgot to tell: I'm using 2.2.1N433.

**Comment by 3djc** [comment] 2017-11-14 06:11
Yes, we are aware of that. We have a plan to better protect the screen buffer from overwrite (not only using lua), but it is a significant task to do it properly;. @projectkk2glider is working on that

**Comment by raphaelcoeffic** [comment] 2017-11-14 07:20
@3djc great, thx! I'll just have to be careful then.

**Comment by projectkk2glider** [comment] 2017-11-15 20:43
Duplicate of #5056

**Closed as completed** 2017-11-15 20:59 UTC
Labels: Bug
