### ISSUE TITLE
No Mavlink option on 9XR-Pro for 2.0.19

### ISSUE THREAD

**Issue by pyr8** [opentx/opentx#3335] opened 2016-03-01 23:10 UTC
I upgraded to the 9XR-Pro from the 9XR. There is no option for "Mavlink" under "OpenTX for 9XR-PRO" in Companion 2.0.19.

Do I need to flash the 9XR-PRO with the "OpenTX for 9XR with M128 chip" in order to get Mavlink back?

**Comment by kilrah** [comment] 2016-03-02 06:22
Mavlink protocol support has not been developed for ARM-based radios. 
You can't flash a Pro with the firmware for a 9XR, completely different processor and architecture. 

Closing as duplicate of #2354.

**Closed by kilrah** 2016-03-02 06:22 UTC

**Comment by pyr8** [comment] 2016-03-02 07:38
It has been done apparently as per: https://plus.google.com/109713849321222194668/post/MYdHi19m1jh

**Comment by kilrah** [comment] 2016-03-02 07:47
Broken link.

**Comment by pyr8** [comment] 2016-03-02 08:02
https://goo.gl/Dd54sT

**Comment by pyr8** [comment] 2016-03-02 08:11
I'm using APM with Openlrs TX & RX and would like to have MAVLINK data displayed on the Pro. Is it at all possible, or am I SOL using the current hardware?

**Comment by kilrah** [comment] 2016-03-02 08:27
As far as we know, as explained there is currently no solution to have native mavlink on a 9XR-Pro. Your hardware is fine, but the software work necessary to make it work has not been done, the issue I linked is about other requests for it. 

Your link however suggests someone has made the necessary work but without publising it... it could be integrated into OpenTX if someone could chase him down, but it seems several people have asked what he's using and he doesn't reply.

**Comment by geofrancis** [comment] 2016-03-17 12:57
I am using native mavlink and FRsky D mode with my 9xr and 9xr pro, the firmware is still a work in progress.

https://github.com/adriano65/opentx-2.0.14

**Comment by pyr8** [comment] 2016-03-21 18:07
geofrancis, I have a 9XR-Pro and both TX/RX modules are orange openLRS from HK flashed with gitsly fork. How do I get MAVLINK data showing on the pro?
