### ISSUE TITLE
Logical switches are not visible in drop down list

### ISSUE THREAD

**Issue by dalarne** [opentx/opentx#5607] opened 2018-01-07 21:52 UTC
Not all logical switches are showing up in the drop down lists for the tab 'Logical Switches'.
This is for Companion 2.2 runing on Windows 10 or 7.
On the Taranis X9E all the logical switches are available.
For instance in the first picture it is not possible to choose the switch L03.
But in the second picture there are a number of switches to choose from.

![bug for logiska brytare_2](https://user-images.githubusercontent.com/35202154/34654264-a1e06082-f3f9-11e7-871e-2e9ede05360d.jpg)

![bug for logiska brytare_1](https://user-images.githubusercontent.com/35202154/34654250-6d08a400-f3f9-11e7-8fc9-af58e6f09bee.jpg)

**Comment by kilrah** [comment] 2018-01-07 21:54
Version? A fix for that was made already. If not, close and reopen the window.

**Comment by dalarne** [comment] 2018-01-07 22:05
Version 2.2.1, Dec 17 2017
I tried it on three different computers and downloaded the file twice.
I have reopened Companion multiple times with the same result.
But now, when closing and reopen the window I can choose from switches L01-L05 from any position but the first one, there all are available.

**Comment by RealTadango** [comment] 2018-01-08 11:45
I think the issue is that you need to re-open the window after you add a LS. Then list do not update when a LS is added / removed.

**Comment by dalarne** [comment] 2018-01-10 00:17
Yes, reopen the window seems to "solve" the issue.
But the drop down lists for the other tabs (mixes, special functions etc.) are updated as expected with/without the new logical switch without the need to reopen the window.
All you have to do is to select a function (logical switches tab), you don´t even have to fill in anything else at that line and the switch is present in the other lists.

**Comment by mpaperno** [comment] 2018-01-10 06:55
This has been fixed early in v2.2.2 with https://github.com/opentx/opentx/commit/76ce186bd4a9e42ee8e336ae7ad601bbda6011c1 .  For 2.2.1 the only workaround is to reopen the window.

Duplicate of #5556.

**Closed as completed by mpaperno** 2018-01-10 06:55 UTC
