### ISSUE TITLE
opentx doesn't accept this radio protocol

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#3191] opened 2016-01-01 03:48 UTC
OpenTx 2.1.6
Taranas Plus
Taranis BootLoader - 2.0.9

When saving the epee file using the Taranis plus radio profile, the error:  OpenTX doesn't accept this radio protocol error occurs.

The expectation is that it will save the file without error.

I'm happy to try things to clear this error, however, it is not obvious.

![screenshot - 12312015 - 06 24 13 pm](https://cloud.githubusercontent.com/assets/2614846/12069684/ba5e61aa-afee-11e5-9c7b-015f915e9749.png)

**Comment by powercycle** [comment] 2016-01-01 03:55
This occurred after opening an eepe file created from a 9XR radio profile.

Saving a new empty file works as expected.

**Comment by kilrah** [comment] 2016-01-01 07:14
What version was the file created by?
Are you sure you then set companion back to Taranis Plus before saving?

Can you upload the file to a file sharing site and post a link?

**Comment by powercycle** [comment] 2016-01-01 22:05
I was able to resolve this by creating a new file and then copying the models to it.  It then saved without error.

The file from the 9XR was created with version 2.0.14 that I built on my Linux machine.

However, I tried to re-create the issue and was unable to do so.

We should probably consider this resolved unless you would like me to try something further.


[opentx.eepe.zip](https://github.com/opentx/opentx/files/76041/opentx.eepe.zip)

**Comment by kilrah** [comment] 2016-01-02 08:30
The problem is due to the 9XR having module protocol set for the to PPM (normal), but when transferred to Taranis it is not a valid option for the internal module.

You must manually change the protocol in each model to the appropriate one for the receiver you have in that model.

**Closed by kilrah** 2016-01-02 08:30 UTC
