### ISSUE TITLE
Improvement for backlight for HORUS

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4442] opened 2017-02-11 20:59 UTC
The option to switch the backlite full is very good. I think, alittle bit better is a aditional value for time and (may be) intensity. For example I use a moment switch or a temporaly switch. The backlite is only for the switched time on and it may be, it's to short to visible in the real flight.

**Comment by kilrah** [comment] 2017-03-08 21:52
Duplicate of #3408

**Closed by kilrah** 2017-03-08 21:52 UTC
