### ISSUE TITLE
Companion on Windows can't execute scripts in subdirs

### ISSUE THREAD

**Issue by u8mydog** [opentx/opentx#3046] opened 2015-11-10 02:04 UTC
It looks like running companion 2.1.5 on Windows 7 has problems in the simulator trying to execute a lua script in a subdirectory.

Created a hello.lua and placed in SDstructure directory for Companion. In companion, entered file browser, selected hello.lua and chose execute. Script ran fine.

Then copied hello.lua to SDstructure\SCRIPTS and tried executing. Companion sim screnn shows 'cannot open \SCRIPTS/hello.lua'. 'Bad file descriptor'.

Notice the wrong slash before the filename.

**Comment by kilrah** [comment] 2015-11-10 07:56
Duplicate of #3024

**Closed by kilrah** 2015-11-10 07:56 UTC
