### ISSUE TITLE
[OpenTx] 3 temporary positions switch

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#2960] opened 2015-10-11 08:09 UTC
Is not relevant but in Hardware configurations is not present a  3 positions temporary switch (ON-OFF-ON)
Is the same of 3 switch positions but in simulator may be useful to have the right switch type

**Comment by hrenz** [comment] 2015-10-11 09:38
Hy,
At the distributors 
the 3 Pos Switch are Called
ON - OFF - ON    both side switches
(ON)- OFF - ON  one side switch, other side temporary
(ON) - OFF - (ON) both side temporary

the 2 Pos switches
ON - OFF   2 two pos, normal switch
(ON) - OFF  2 pos, temorary switch

**Comment by kilrah** [comment] 2016-01-03 17:59
Duplicate of #3189

**Closed by kilrah** 2016-01-03 17:59 UTC
Labels: Companion, enhancement
