### ISSUE TITLE
Bad eeprom in Turnigy 9x (m128)

### ISSUE THREAD

**Issue by nikola-v** [opentx/opentx#5646] opened 2018-01-23 15:33 UTC
Hello,

I am running OpenTX 2.2 with Companion (2.2.1) and after doing firmware upgrade on my Turnigy 9x (m128 stock board) I read out models without problem with companion and try to save them back to radio, then message pops u saying Bad eeprom and I need to re-format my eeprom, also all my radio settings are lost.

Radio reports following:

FW: opentx-9x128
VERS: 2.2.1
DATE: 2018-01-23
TIME: 18:20:33
EEPR: 216-1

How can I convert it to eeprom 218 ?

Looking through the code I found part:
(https://github.com/opentx/opentx/blob/394bc1689f64b8bf7417fe8bb2e10b295217e289/radio/src/myeeprom.h)
```

#if defined(CPUARM)
  #define EEPROM_VER             218
  #define FIRST_CONV_EEPROM_VER  216
#elif defined(CPUM2560) || defined(CPUM2561)
  #define EEPROM_VER             217
  #define FIRST_CONV_EEPROM_VER  EEPROM_VER
#elif defined(CPUM128)
  #define EEPROM_VER             217
#else
  #define EEPROM_VER             216
#endif

```

So it seems it should be 217 if I am right?

**Comment by kilrah** [comment] 2018-02-11 11:22
Duplicate of #5586

**Closed as completed by kilrah** 2018-02-11 11:22 UTC
