### ISSUE TITLE
[Improvement] Unique USB Vendor and Product IDs

### ISSUE THREAD

**Issue by netizen01** [opentx/opentx#8190] opened 2020-12-30 17:39 UTC
A current issue with (almost) every OpenTX radio is that Windows changed how it ranks the appropriate driver for radios that are connected as HID Joysticks.

In September 2019, something changed in a Windows update to where the higher ranked driver became the "BETTER_USB_HS" driver published by STM. Exploring that INF shows that it matches the VID and PID exactly but does not classify the driver as a Joystick, thus it does not work as intended. The current workaround / solution is to switch the driver to the built in USB HID Device driver.

This workaround requires administrative privileges on the system and is a [rather complicated task](https://www.youtube.com/watch?v=Aeb8gN-60VA). For beginners who are just starting and learning to fly through a simulator, this is a huge hurdle to get over and many give up. In addition, if they are using a non-administrator account, the fix requires another person (such as a parent or school administrator), which just increases the complexity of the fix exponentially.

Certain radios are able to get around this issue by changing the Vendor ID to something other than STM, thus allowing the built in HID Driver to become the better match. The correct solution for each manufacturer (Taranis, RadioMaster, Jumper, TBS, etc.) would be for them to apply to the USB-IF and pay the $5,000 required to acquire their own Vendor ID. Unfortunately it seems none of them are willing to do that or have taken the time to investigate it. [TBS does have their own Vendor ID](https://devicehunt.com/view/type/usb/vendor/734C), but they do not actually use it for their Tango2 radio. Instead they switched it to [Microchip Technology's VID](https://devicehunt.com/search/type/usb/vendor/04D8/device/5710) to avoid this issue, though the Product ID is still the default "Joystick FS" Product ID provided by STM. (This is not the correct approach and we should avoid using an invalid VID / PID or using a VID without permission)

Given the nature of this open source hardware / firmware, it seems an appropriate solution would be to find a way to obtain a VID / PID for any OpenTX radio that does not want to supply its own unique VID. Understandably a $5,000 fee is not realistic for an open source community. Fortunately there are a few solutions for OSS projects.

[https://pid.codes](https://pid.codes)

This site has acquired a Vendor ID from an older company before the USB-IF started prohibiting the transfer of VIDs. [It is actively](https://github.com/pidcodes/pidcodes.github.com/commits/master) allowing OSS projects to use their VID and apply for a free unique PID through a simple Pull Request on their Github repository.

[I believe OpenTX qualifies.](https://pid.codes/howto/)

The process here would be to apply for a unique PID and then once approved, change the USB Vendor and Product IDs in the OpenTX Firmware.

**This fairly straightforward fix would solve the current windows driver issue that is present for all OpenTX radios** that do not create custom firmware images with a modified Vendor ID.

There are other options as well. STM will provide a unique Product ID that can be used in production if you use their chips in your products. I am unsure if they would give the Product ID to the OpenTX group though. Might be worth exploring as well.

Please consider this improvement as I believe it will dramatically improve the onboarding experience for new pilots who are wanting to use a simulator and may not be able to make the driver changes needed (school computer, not tech savvy, etc.).

Steps to Implement:
- An admin for the OpenTX GitHub group should [fork the PID.codes repository as explained](https://pid.codes/howto/), create the required files and submit the pull request. (appropriate contents below)
- Once approved for the Product ID, change the Vendor and Product IDs in https://github.com/opentx/opentx/blob/2.3/radio/src/targets/common/arm/stm32/usbd_desc.c

Forthcoming Pull Request on this commit:
https://github.com/netizen01/opentx/commit/79aa5ca32347b25783f1a8ac3fad771540945d0c

Caveats:
- _Multiple PIDs may be needed for the different modes that the radios can represent (Mass Storage, Joystick)_
- We would possibly need to continue to use the STM VID for Mass Storage and the Virtual Serial Port (CDC) - a simple if statement to select the correct VID just like the selection of the PID (lines 129-170).

PID codes markdown file contents:

```
---
layout: org
title: OpenTX
site: https://www.open-tx.org
---
OpenTX is open source firmware for RC radio transmitters. The firmware is highly configurable and brings much more features than found in traditional radios. The daily feedback from the thousands of users ensures the continued stability and quality of the firmware.
```

**Suggested PID: 5458 ("TX" in ASCII)**

```
---
layout: pid
title: Radio Transmitter
owner: OpenTX
license: GPLv2
site: https://www.open-tx.org
source: https://github.com/opentx/opentx
---
```

**Comment by i2bh** [comment] 2020-12-30 17:53
Thank God someone finally fixed this! The n00b killer glitch 😑 thnx netizen01

**Comment by netizen01** [comment] 2020-12-30 18:05
> Thank God someone finally fixed this! The n00b killer glitch 😑 thnx netizen01

Not fixed yet, but this is at least a possible solution!

**Comment by DownRightFPV** [comment] 2020-12-30 18:12
Nice work!

**Comment by batcavegames** [comment] 2020-12-30 18:16
please look into this, the support that all sims have to go through daily fixing customers who don't know about this is a major hassle and a great annoyance to OpenTX users.

**Comment by skyfpv** [comment] 2020-12-30 18:20
Our team would greatly appreciate this fix being implemented as well! This has been the bane of our customer support efforts.

**Comment by FPVanadium** [comment] 2020-12-30 19:58
What he said. ^^^

**Comment by lephro** [comment] 2020-12-31 02:44
I agree. This is a huge pain and in an unexceptable state, for eveyone using openTX based products. You gotta fix this for at least 2.3 and the upcoming releases. FFS.

**Comment by netizen01** [comment] 2020-12-31 21:08
I've tested the change to the VID / PID on [this commit](https://github.com/netizen01/opentx/commit/79aa5ca32347b25783f1a8ac3fad771540945d0c).

Radio: FrSky XLite
Tested Joystick mode on Windows 10 and macOS - both worked as expected, Windows defaulting to the correct USB HID Driver instead of the BETTER_USB_HS (!).
Tested Mass Storage mode on Windows 10 and macOS - both worked as expected.

If the OpenTX team can request the suggested PID, I can open a PR on that commit and get this change merged!

**Comment by mcw719** [comment] 2021-01-01 00:03
Fixing this issue will have far-reaching effects. The pandemic triggered a boom in sim use, and our Youth Drone Sports Championships program was the only high school sport that didn't cancel last spring when we shifted to racing in VelociDrone. With virtually every student pilot needing to roll back their driver update to get their radio to work, we lost valuable time and many pilots bounced, meaning more time trying to bring them back. With this update, we can onboard many more students with far fewer hurdles. Thank you netizen01!

**Comment by ZOETEK** [comment] 2021-01-01 16:57
I agree with everything mcw719 said! cheers mate!! this is a urgent request!

**Comment by juniordiscart** [comment] 2021-01-01 18:55
As a Liftoff developer, we would love to finally see this solved. 95% of our controller related support questions are about them not being recognized due to this issue.

**Comment by MooreMapping** [comment] 2021-01-03 04:01
This would be a great fix to have! Really annoying to have to reset this every time there's a windows update. Thanks for the input Netizen01!

**Comment by spinkham** [comment] 2021-01-06 01:35
PR #8195 was merged into 2.3 branch recently with the [newly assigned ID](https://pid.codes/1209/4F54/).

**Closed as completed** 2021-01-06 17:18 UTC

**Comment by bsongis** [comment] 2021-01-06 17:27
Thanks for your help on this one @netizen01 

Thanks @ all other people for the kind comments ;) please keep in mind that people helping here give their time on OpenTX for free, AFAIK OpenTX didn't get any free license / donation / whatever from simus companies mentioned in this issue.

**Comment by ZOETEK** [comment] 2021-01-06 17:36
Where could we send a donation? 

Kind Regards,

Jeff "ZOETEK" Grabowsky
SaltCtyRacingFPV, LLC
weBLEEDfpv.com
7256 LeafCrest Ln
East Syracuse, NY 13057

United We Fly, Together... weBLEEDfpv

**Comment by batcavegames** [comment] 2021-01-07 03:58
@bsongis perhaps you don't realise just how much this particular problem has cost the sim companies in support hours. Saying we didn't donate - we did - literally hours on end of support over the past year instead of redirecting all those people here for OpenTX support people to deal with. This problem has cost thousands in support time for us. I'll happily donate you some money if it makes you feel better but please try to understand this from our point of view - this has been one of the most costly problems we have ever had to deal with, the fact it is finally fixed is a blessing and we thank you for it but don't think for one moment we didn't pay for it.

**Comment by kilrah** [comment] 2021-01-07 08:33
> @bsongis perhaps you don't realise just how much this particular problem has cost the sim companies in support hours. Saying we didn't donate - we did - literally hours on end of support over the past year instead of redirecting all those people here for OpenTX support people to deal with. This problem has cost thousands in support time for us.

It's been a problem for you for a year yet the slew of companies in this issue is literally the first time any of them complains to us about it and it's suddenly "unacceptable", "urgent" and the likes? 

The problem was caused by a change out of our control, and it's the first time someone finds a way to fix it as well...

**Comment by bsongis** [comment] 2021-01-07 13:37
@ZOETEK here: https://www.open-tx.org/donations
@batcavegames well, no comment :)

**Comment by DigoFuerte** [comment] 2023-05-22 10:24
Please tell me there is a definitive fix for this problem - it is 2023 and this issue seems to have started in 2019. I just bought a Taranis X9D and LiftOff (to train myself to fly). My PC is Win 11 Pro, and the Taranis in Bootloader mode (v2.2.2) in OpenTX does not appear to connect, though I can see some of the start screen info from the X9D. LifOff reports that the X9D is not connected and in Win 11 Device Manager the only evidence of the X9D is in the Disk Driver branch where it appears twice as "FrSky Taranis USB Device". Any suggestions are welcome.

**Comment by juniordiscart** [comment] 2023-05-22 10:30
@DigoFuerte This is a whole different issue and the issue from OP was fixed in v2.3.11. If you're on an older version than that, you may still encounter the issue as described in the OP.

What you're experiencing is that your remote is set to function as a disk extension rather than a HID/gamepad. If you're still on v2.2.2, then perhaps the functionality is not present yet, but when connecting it to the system, it should provide you with a message on the radio to ask in what mode you want to connect it to the system.
If this is not the case, then there's still a setting somewhere that should toggle the radio's function upon connecting it to an external system. I would look into updating the firmware though, as that's imo the better course of action.

**Comment by DigoFuerte** [comment] 2023-05-22 10:31
Sorry, I can also see "FrSky Taranis Bootloader" in the Other Device section on the BlueTooth & Devices tab in Settings. It does not have any facility to update or change the driver... ?

**Comment by juniordiscart** [comment] 2023-05-22 10:36
@DigoFuerte updating is not done through device manager. Please check out the manual or support page of your radio on how to update it.

**Comment by DigoFuerte** [comment] 2023-05-22 10:46
@juniordiscart thanks for your response. I am a bit at this right because I am totally new to all of this... I am building a drone (piece by piece) and LiftOff was supposed to get me ready to fly when the drone is done. The Bootloader on the X9D is version 2.2.2 and on the FrySky support page that is the latest version. What am I missing there? Do I have to somehow install OpenTX on the X9D? 
When I start the bootloader, I see listed; Write Firmware, Restore EEPROM, Exit... then at the bottom
Curr FW: opentx-x9d+-2.2.2 (a5de713b)
Or plug in a USB cable for mass storage
Are any of these options what I need?

**Comment by DigoFuerte** [comment] 2023-05-22 10:53
@juniordiscart - thank you very much. You prompted me to look again at how I was starting the receiver. I got myself confused because I was following a video on YouTube on how to update firmware - which meant starting in Bootloader mode. I didn't realise that all I had to do was start the receiver and then insert the USB cable. LiftOff now sees the controller but it looks like the sticks are on the wrong sides (the left stick appears on the right in LiftOff, and vice versa). Thanks again

**Comment by juniordiscart** [comment] 2023-05-22 11:46
@DigoFuerte Those issues should be solved when performing a calibration of the controller in-game.

**Comment by DigoFuerte** [comment] 2023-05-22 12:11
@juniordiscart ...yes, that was the first thing I did in LiftOff. Now... the bigger problem... I am rubbish at flying. The drone in LiftOff is going up to the moon and back every time I try to fly level in a straight line... I despair. Good thing I am not smashing my expensive drone making these baby steps.
