### ISSUE TITLE
[OpenTX 2.x][Companion]Smooth curve not working

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#1859] opened 2014-11-20 11:04 UTC
Well everything is in the title. :)
When editing a curve under Companion, the "Smooth" does not work. I noticed this for Companion 2.0.12, 2.0.13 and 2.1.

**Comment by projectkk2glider** [comment] 2015-01-17 17:21
Duplicate of #1330

**Closed by projectkk2glider** 2015-01-17 17:21 UTC
Labels: Companion, enhancement

**Comment by LapinFou** [comment] 2015-07-01 15:45
I probably missed something, but, do you plan to implement this feature in the OpenTX 2.0.x branch?

**Comment by bsongis** [comment] 2015-07-01 16:48
No, 2.1.1

**Comment by LapinFou** [comment] 2015-07-01 18:38
OK. Thanks for the update. Anyway, it is just a cosmetic feature.
:]
