### ISSUE TITLE
Control loss randomly 

### ISSUE THREAD

**Issue by snir2001** [opentx/opentx#7288] opened 2020-01-11 17:06 UTC
Hi,

Today I lost a jet due to control loss in mid flight.
It was the first flight after updating to 2.3.4

To check it, I tried few receivers, all showing the same problem:
The servos hangs for few seconds while there is no alarm, and the RSSI is normal, and also the receiver battery is normal. 
I tried of course few batteries.
After that kind of a loss, I can't trust my transmitter any more....

Any suggestions ? 

**General information**
 - OpenTX version 2.3.4
 - Hardware Horus X10S

**Comment by kilrah** [comment] 2020-01-11 18:25
What exact X10S, the normal, normal upgraded to ACCESS, or Express?
What firmware on the module and receivers?

**Comment by snir2001** [comment] 2020-01-11 18:31
Normal X10S, no upgrades.
OpenTX 2.3.4
All of my RX8R Pro receivers.

The receiver not going into failsafe, and the monitor on the radio shows everything normal, ie servos moving by stick movement, but the actual servos freeze for 3 seconds

**Comment by kilrah** [comment] 2020-01-11 19:03
Did you find particular conditions that make it repeatable?

**Comment by snir2001** [comment] 2020-01-11 19:06
No, but I will try to downgrade and check it again.
I want to be sure it's not the transmitter itself.

**Comment by 1Sven** [comment] 2020-01-11 19:24
I have another error: It happens that a servo (often Ch3) runs briefly into the end stop. X12s LBT. Not reproducible. Maybe the same cause.

**Comment by 1Sven** [comment] 2020-01-11 19:27
Caution! Not just now, but when switching to LBT:

**Comment by snir2001** [comment] 2020-01-11 19:32
OK, I have an ongoing update.
I managed to reproduce the problem ONLY in the crashed model profile.
ALL other profiles works normally for now, but i'm trying to do so over long time.
I will give final verdict tomorrow.

**Comment by kilrah** [comment] 2020-01-11 19:43
Might be too late, but please backup the EXACT configuration that causes the issue (copy entire SD card to somewhere, and read firmware from radio to a file) before changing stuff.
And if you know what you have on them include the info about the internal module and receiver firmware versions.
Provide us with a link to download these things to have a look at, using Dropbox or such.

**Comment by snir2001** [comment] 2020-01-11 19:51
OK, I will do so tomorrow. Thanks.,

**Comment by snir2001** [comment] 2020-01-12 11:08
Well, after rigorous testing on a test rig I build, with my trusty Futaba for comparison, I have some results.
The tests took place at a free airfield, on ground level.
The Horus was with the same working setup as before upgrading to 2.3.4:  2.4Ghz RX8R Pro with R9 transmitting on 100mw.
The Futaba was only with 2.4Ghz of course as a reference.
Both radio used the very same servos and battery.

The Horus was hanging badly on all profiles...

After disabling the R9, the Horus and the Futaba shows the same results of 320 meters from the transmitter.

I repeated the test four times with the same results, with robust link and no hangs. 

Because this setup was working flawless before the update, my conclusion is that there is a problem with 2.3.4 (Maybe even before) regarding the setup I used.

**Comment by snir2001** [comment] 2020-01-12 11:13
> Provide us with a link to download these things to have a look at, using Dropbox or such.

Here you go:
https://drive.google.com/drive/folders/1xq3J_ibg42Xd8kXFYmmgX_ua_1L9XGGA?usp=sharing

**Comment by 3djc** [comment] 2020-01-12 11:15
Well, I do not understand how you can come to this conclusion !

If I understand correctly:
- with only 2.4ghz, both radio work fine, so clearly horus 2.3.4 2.4GHz runs perfect

You then add r9 to only Horus, it stops working nicely, and you conclusion is ... OpenTX fails ??? The only way you could say that is if similar setup with FrOS was working flawlessly, which you do not seem to have tested.

What you could do it test with your horus with a profile that uses both 2.4 and r9 BUT without the R9 module. If that works, it means OpenTX is doing its job correctly, and R9 module interfere with you Horus hardware

**Comment by snir2001** [comment] 2020-01-12 11:22
> Well, I do not understand how you can come to this conclusion !
> 
> If I understand correctly:
> 
> * with only 2.4ghz, both radio work fine, so clearly horus 2.3.4 2.4GHz runs perfect
> 
> You then add r9 to only Horus, it stops working nicely, and you conclusion is ... OpenTX fails ??? The only way you could say that is if similar setup with FrOS was working flawlessly, which you do not seem to have tested.
> 
> What you could do it test with your horus with a profile that uses both 2.4 and r9 BUT without the R9 module. If that works, it means OpenTX is doing its job correctly, and R9 module interfere with you Horus hardware

No....
It works perfectly with 2.2.3 before, do the math....

**Comment by 3djc** [comment] 2020-01-12 11:24
You haven't said that in your test reports have you ? And is that it is working today if you put 2.2.3 in the very same conditions, or is it worked some weeeks ago, because thats very different

**Comment by snir2001** [comment] 2020-01-12 11:27
With the very same conditions, yes, it's working fine and that's why my conclusion is OpenTx.
I updated version, lost control, simple as that.

**Comment by 3djc** [comment] 2020-01-12 11:28
So  you tested yesterday with 2.2.3 ?  So I'm assuming it happens with model UltraFlash as it is the only one with both xjt and r9 ?

Also, how are your receivers setup ? RX8R Pro with redundancy to ???

**Comment by snir2001** [comment] 2020-01-12 11:31
> So you tested yesterday with 2.2.3 ? So I'm assuming it happens with model UltraFlash as it is the only one with both xjt and r9 ?

Yesterday crash and tests, today more tests. (not the very same receiver obviously)

**Comment by 3djc** [comment] 2020-01-12 12:23
What model are you using ? The only one with both modules is UltraFlash , but that uses an RB and you mention that nowhere

**Comment by snir2001** [comment] 2020-01-12 12:23
OK,
I changed again one hour ago, this time to 2.2.4
The system works for the full hour now, with R9 on 100mw flawless...
IT'S THE 2.3.4 VERSION! (for my setup)

I will keep it working for another hour, but it's pretty obvious.

**Comment by kilrah** [comment] 2020-01-12 12:39
Please connect some servos directly to both receivers, use 2.3, and see if when the servo connected to the RB freezes the ones connected to the receivers do as well or not.

**Comment by snir2001** [comment] 2020-01-12 12:40
The RB is out of the game, crashed yesterday... I use only receivers.

**Comment by 3djc** [comment] 2020-01-12 12:42
I use your model, rx8r pro and r9, servo connected to rx8r, can’t reproduce

**Comment by kilrah** [comment] 2020-01-12 12:58
How exactly are you set up now on the receiver side then? R9 sbus out into rx8r sbus in, and servo connected to rx8r? If so, firstly:
- Connect a servo to the same channel on both receivers, see if both stop working
- Leave those servos, and disconnect the cable between the 2 receivers (add power to the other obviously), see again if they both freeze simultaneously

**Comment by snir2001** [comment] 2020-01-12 13:11
The setup on the doomed model was RB-20 with RX8R Pro to RX1 and R9 mini to RX2.
Since the R9 mini disintegrated, I have no R9 receiver to check, so all my testing is with various RX8R Pro (standalone, no RB).

The servos hangs with 2.3.4 (R9M - on 100mw)  and works nicely with 2.2.3 and 2.2.4 (R9M - on 100mw).

**Comment by kilrah** [comment] 2020-01-12 13:17
Ouch, one day we might have a chance to understand your test setup, would be much easier if you clearly described it.

So you just have a standalone RX8R Pro and no other accessories on the RX side, and on the TX side you have both the internal module and an R9M. When you are transmitting both with the internal module and the R9M it causes drops, but if the R9M is disabled this does not happen?

If that is correct, what if you leave the R9M on in the menu but physically remove it from the radio?

**Comment by snir2001** [comment] 2020-01-12 13:20
> Ouch, one day we might have a chance to understand your test setup, would be much easier if you clearly described it.
> 
> So you just have a standalone RX8R Pro and no other accessories on the RX side, and on the TX side you have both the internal module and an R9M. When you are transmitting both with the internal module and the R9M it causes drops, but if the R9M is disabled this does not happen?
> 
> If that is correct, what if you leave the R9M on in the menu but physically remove it from the radio?

That is correct. 

I will try later with R9M removed but switched on.

**Comment by snir2001** [comment] 2020-01-12 14:10
OK,
That was pretty straightforward.

Did a clean install of 2.3.4
Config 1: R9M physically out, and external module off in menu.
Result: Working fine.

Config 2: R9M physically in, and external module off in menu.
Result: working fine.

Config 3: R9M physically in, and external module on in menu.
Result: Servos hangs.

Config 4: R9M physically out, and external module on in menu.
Result: Servos hangs.

All of the above works fine with 2.2.4....

**Comment by 3djc** [comment] 2020-01-12 14:13
Ok so r9 pulses seem to be affecting xjt pulses. How frequent are those freeze ? It is like always and you can’t miss, or less frequent ?

**Comment by snir2001** [comment] 2020-01-12 14:18
It can be right at the start, or after few minutes.

I will upload a short video.

**Comment by snir2001** [comment] 2020-01-12 14:34
https://youtu.be/Ixp_f7jnp-0

**Comment by i3dm** [comment] 2020-01-13 05:31
has anyone managed to recreate this bug?
any idea what's causing it?

**Comment by bsongis** [comment] 2020-01-13 08:13
Reproduced with X10
Impossible to reproduce with X7

**Comment by mpjf01** [comment] 2020-01-13 23:27
TBH, given that this would seem to be a critical bug, users deserve a clear explanation of the cause and remedial action taken, what systems are affected and what are not. Where would one go to test the "attempt to fix"? I and many others would not have the skills needed to decipher the code changes in the commit.

**Comment by bsongis** [comment] 2020-01-13 23:29
The PR automatically closed the issue. More explanations tomorrow, it's not a simple one, I worked the whole day on it.

**Comment by bsongis** [comment] 2020-01-13 23:32
@3djc we need a big warning on the opentx website, this bug is critical, all X10 (+ Express) / X12S must be upgraded.

**Comment by bsongis** [comment] 2020-01-13 23:33
X7 tests done

**Comment by bsongis** [comment] 2020-01-13 23:33
XLite Pro tests needed

**Comment by mpjf01** [comment] 2020-01-14 00:53
Could help with X-Lite/R9M-Lite and X9D/X9D+/R9M if need be.

**Comment by 3djc** [comment] 2020-01-14 06:05
It can be tested in 2.3.5N100. It affects Horus when two pxx1 modules (xjt/r9m) are been used at the same time

**Comment by i3dm** [comment] 2020-01-14 06:12
will there he a release of 2.3.5 identical to 2.3.4 with just this bug fix?

**Comment by 3djc** [comment] 2020-01-14 06:14
Not decided yet, will be decided today. Temporary bugfix : don't use both

**Comment by i3dm** [comment] 2020-01-14 06:15
some of the higher end models need both for added safety

**Comment by 3djc** [comment] 2020-01-14 06:17
We understand that, but with 2.3.0 to 2.3.4, it is really not a good idea on horus. We will decide how we adress the issue today.

**Comment by i3dm** [comment] 2020-01-14 06:21
no problem.
may i ask why you consider it not a good idea?

**Comment by 3djc** [comment] 2020-01-14 06:22
Because in Horus 2.3.0 to 2.3.4, it has the issue you experienced !

**Comment by i3dm** [comment] 2020-01-14 06:23
well of course. we had a miscommunication. i thought you were talking about 2.3.5 release, sorry.

**Comment by 3djc** [comment] 2020-01-14 19:23
Could you try 2.3.5N101 ? We believe it fixes the issue

**Comment by bsongis** [comment] 2020-01-15 08:54
- X10 tests done
- X12S tests done
- XLitePro tests done

**Comment by 3djc** [comment] 2020-01-15 08:57
While not fully applicable; T16 test done

**Comment by i3dm** [comment] 2020-01-15 11:39
Was the bug evident on T16 before the update?
is it exhibited only with XJT / R9M external module? or also MPM?

**Comment by 3djc** [comment] 2020-01-15 13:32
The bug you describe no, it did not exist on T16, but another one lined to emergency that we fixed at the same time yes

**Comment by 3djc** [comment] 2020-01-15 15:45
Fixed in 2.3.5

**Closed as completed by 3djc** 2020-01-15 15:45 UTC
Labels: Bug, Priority-Critical, Radio Firmware

**Comment by i3dm** [comment] 2020-01-15 18:19
i just flashed 2.3.5 to my X10S Express and got a "Wrong PCB deteced" error, i verified on bootloader screen it should version as x10express.
2.3.5 is currently unuseable on X10S express.

**Comment by 3djc** [comment] 2020-01-15 18:21
What is the exact name of the file you downloaded, so that we can check that ?

**Comment by i3dm** [comment] 2020-01-15 18:22
opentx-x10express-flexr9m-lua-en.bin

**Comment by 3djc** [comment] 2020-01-15 18:29
What is the size of the firmware ?

**Comment by i3dm** [comment] 2020-01-15 18:30
1041 kb

**Comment by 3djc** [comment] 2020-01-15 18:30
1 048 952 bytes ?

**Comment by i3dm** [comment] 2020-01-15 18:31
Size on disk: 1.01 MB (1,069,056 bytes)

**Comment by 3djc** [comment] 2020-01-15 18:32
size on disk depends of your disk cluster size, can I hve the other one ?

**Comment by i3dm** [comment] 2020-01-15 18:33
Size: 1.01 MB (1,064,996 bytes)

**Comment by i3dm** [comment] 2020-01-15 18:34
Also tried: opentx-x10express-en.bin
Wrong PCB detected

**Comment by 3djc** [comment] 2020-01-15 18:35
Ok, that seems to be the roght file. Very strange, we will find someone to try on an x10 express

**Comment by i3dm** [comment] 2020-01-15 18:39
am i not enough? :)

**Comment by kilrah** [comment] 2020-01-15 18:43
Someone who can try a fix AND test it on his X10 Express ;)

**Comment by i3dm** [comment] 2020-01-15 18:55
i can. where do i get the fix?

**Comment by kilrah** [comment] 2020-01-15 19:09
Try to MAKE a fix.

**Comment by i3dm** [comment] 2020-01-15 19:10
gotchata. since im not fimiliar with OpenTX code, will leave that to the experts.
i can help with testing.

**Comment by i3dm** [comment] 2020-01-15 19:22
can i somehow get the 2.3.4 file again? just so my X10S express is not temporarily bricked? as im using internal module only for now on this radio anyway.

**Comment by bsongis** [comment] 2020-01-15 19:23
I take it

**Comment by bsongis** [comment] 2020-01-15 19:23
Reproduced.

**Comment by i3dm** [comment] 2020-01-15 19:24
just opened a new issue for that Bertnard, hope thats OK.

**Comment by bsongis** [comment] 2020-01-15 19:24
Yes thanks, this one is already something ...
