### ISSUE TITLE
Log file updates when new sensors added

### ISSUE THREAD

**Issue by boblane1949** [opentx/opentx#6169] opened 2018-09-11 21:01 UTC
When using logging, the first use of the (radio) day creates a log file with that days date.  This file is appended with each use on that date.  If a new sensor is added, the log file does not add the header names to that days log file, but it does start to log the new data.  This results in a log file with data that has no column header.  Deleting the .csv log file and forcing creation of a new log file will result in all sensors having a column heading.

Maybe an alert option to create a new log file when sensors are added.

FrSky X9D Plus OpenTX 2.2.2 July 28, 2018
FrSky X8R, LiPo and RPM sensors

**Comment by kilrah** [comment] 2018-09-11 22:49
Duplicate of #2542

**Closed as completed by kilrah** 2018-09-11 22:49 UTC

**Comment by boblane1949** [comment] 2018-09-12 00:48
Thank you for your time and looking into this.  Sorry I wasted your time
and missed the previous reports of this issue.

Thx Bob
