### ISSUE TITLE
X9E logs more values than header fields

### ISSUE THREAD

**Issue by myckey** [opentx/opentx#2638] opened 2015-08-04 14:08 UTC
Using latest versions of both companion and firmware as downloaded by companion.

Companion cannot open the log files the TX has created, no problem opening in Excel and the data looks good and "clean", error message in Companion is "selected file contains X invalid lines out of X total lines". Same result if tge log file is transferred to desktop first then opened.

**Comment by kilrah** [comment] 2015-08-04 14:13
What sensors do you have?

**Comment by myckey** [comment] 2015-08-04 14:20
No sensors as such just a D8R 11 Plus RX.

**Comment by kilrah** [comment] 2015-08-04 14:39
Can you post an affecting log? Note the email reply doesn't support attachments.

**Comment by myckey** [comment] 2015-08-04 14:50
Here is a small log file opened in Excel, no RSSI as the RX wasn't on but all error messages are the same.

**Comment by myckey** [comment] 2015-08-04 14:53
![log file](https://cloud.githubusercontent.com/assets/13611228/9063729/e49f8aa0-3ac0-11e5-9d35-b845c7901c68.PNG)

**Comment by myckey** [comment] 2015-08-04 14:53
Log file now displayed.

**Comment by kilrah** [comment] 2015-08-04 14:54
Would be best to have the original file so I can try to reproduce.

**Comment by myckey** [comment] 2015-08-04 14:55
Tell me how to send it and I will do so right now

**Comment by kilrah** [comment] 2015-08-04 15:12
You can use something like wetransfer.com and post the link.

**Comment by myckey** [comment] 2015-08-04 15:51
I've put two log files on dropbox for you, https://www.dropbox.com/sh/zpxakqj5agwl06g/AACttaabxnnvKxHtFs1G-7Yga?dl=0

**Comment by projectkk2glider** [comment] 2015-08-04 16:50
@myckey your log file has three more values in data rows compared to the first row where field names are declared. This is the first two lines of your log:
```
Date,Time,RSSI,Rud,Ele,Thr,Ail,S1,S2,S3,LS,RS,SA,SB,SC,SD,SE,SF,SG,SH
2015-08-04,11:35:15.360,105,-3,-2,-1024,0,0,12,-1024,0,-13,17,1024,1024,-1,-1,-1,-1,-1,1,-1,-1
```

This has either been already fixed in 2.1.1 **or** does not occur if one logs some additional telemetry fields, because it works for me (with several telemetry fields enabled). I haven't tried with default fields only like your example.

**Comment by griebd** [comment] 2015-08-04 17:46
I have a model without telemetry (DSM2) and the logs worked as expected, BUT I'm on a self compiled 2.1.X...

Actually, now that I think about it, I did not configure this model to log anything at all... Why are logs been generated? I though logs where enabled only by setting a 'special function'...

**Comment by kilrah** [comment] 2015-08-04 17:48
What radio do you have? If it's an X9E it could have something to do with the number of switches as it's variable.

**Comment by kilrah** [comment] 2015-08-04 17:51
Ah sorry it IS an X9E, was in the original title.

**Comment by myckey** [comment] 2015-08-04 20:39
I can't say it would log or wouldn't if you hadn't enabled it but I enabled logs in the special function menu, files as said can be read in companion OK if the last three columns of non headed data are deleted.

Question, should I be raising an issue here if I'm only using the latest download from Companion? I assume 2.1.1 isn't on general release yet which is why companion doesn't update to it?

**Comment by kilrah** [comment] 2015-08-04 20:56
Correct, 2.1.1 isn't released yet. Anyway it's a firmware issue, not a companion one.

**Closed** 2015-08-06 17:28 UTC
Labels: Bug, Radio Firmware
