### ISSUE TITLE
Simulator AnalogInput

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#3094] opened 2015-11-22 19:10 UTC
Simulator S1 = F1 Mischer
Simulator S2 = F2 Mischer
Simulator RS = S1 Mischer

Simulator LS not Work
Simulator F1, F2 ????

**Comment by kilrah** [comment] 2015-11-22 19:11
Duplicate of #2377, like 2 #3092 and #3093.

**Closed by kilrah** 2015-11-22 19:11 UTC
