### ISSUE TITLE
taranis radio plus

### ISSUE THREAD

**Issue by antonucci** [opentx/opentx#2383] opened 2015-06-25 00:25 UTC
Hello ,
    I'm looking for help with my radio  I have bang my head on the wall for about 4 days and I'm starting to  like but real need help with putting models on . I can not get it to work right I watch you tube and still noting please can anyone help me with my taranis plus radio

**Comment by projectkk2glider** [comment] 2015-06-25 05:58
duplicate of #2384

**Closed by projectkk2glider** 2015-06-25 05:58 UTC
