### ISSUE TITLE
copy model problem

### ISSUE THREAD

**Issue by tedbmoss** [opentx/opentx#6295] opened 2019-01-10 23:18 UTC

**Comment by tedbmoss** [comment] 2019-01-10 23:26
ver 2.2.3 if you copy a model from an existing model in d16 mode (or if it ever was in d16 mode) to another model and make it d8 mode it alarms with model was used in xx which is true, but not applicabile to d8 mode. this is a very minor problem, I point it out only because it might cause some other problem I don't know about. I expected the change to d8 mode to drop off the information from d16 mode not required in d8 mode. This was probably there for some time not just this version. That is I copied it after changing it to d8 mode. Using Frsky X9D+.

**Comment by kilrah** [comment] 2019-01-11 08:25
Duplicate of #6194

**Closed as completed by kilrah** 2019-01-11 08:25 UTC
