### ISSUE TITLE
companion X9E incorrect operation of controls 

### ISSUE THREAD

**Issue by Poppy-Ann** [opentx/opentx#3092] opened 2015-11-22 11:19 UTC
I have been trying to use Companion 9X with my Frsky X9E but some of the controls operate the wrong function in the simulate mode, the analogue settings are incorrect.

control	operates 	Analogue
LS		nothing		08
RS		S1 (inverted)	09
S1		F1		05
S2		F2		06
Nothing		LS		
Nothing		RS

**Comment by projectkk2glider** [comment] 2015-11-22 11:33
Duplicate of #2377

**Closed by projectkk2glider** 2015-11-22 11:33 UTC
