### ISSUE TITLE
Wrong switch position warning Simulator at first run (Horus, N369, Mac OS X 10.12.4)

### ISSUE THREAD

**Issue by Red-Devil74** [opentx/opentx#4803] opened 2017-04-16 11:39 UTC
1. -Open companion(N369) on Mac.
2. -Open .otx file (imported from Horus with N369 firmware).
3. -Click Simulate Radio
The screen shows me the "Controle warning" with S1 and S2 at wrong position (see attached)
![image](https://cloud.githubusercontent.com/assets/23432540/25070863/79cf913e-22a9-11e7-9645-1855db7cecd9.png)
I know this to be wrong as more position warning are set and wrong at boot.
4. -Close the simulator
5. -Open the simulator again
The screen now shows the correct warnings (see attached) SA, SB, SE, S1, S2
![image](https://cloud.githubusercontent.com/assets/23432540/25070880/d40a7ede-22a9-11e7-8bc0-02f3181c2596.png)
[170415.otx.zip](https://github.com/opentx/opentx/files/924238/170415.otx.zip)

**Comment by mpaperno** [comment] 2017-04-16 20:34
Unfortunately can't recreate this either (OSX Sierra).  We'll keep trying, and thanks for posting .otx file.  Can you tell us more about your Mac?

**Comment by Red-Devil74** [comment] 2017-04-16 20:48
It's an MBP
![image](https://cloud.githubusercontent.com/assets/23432540/25074211/69c31d22-22f6-11e7-921d-60637f6a3d6a.png)
rather old, but with a samsung SSD in it... Recently I tried to take a stab at compiling and therefor I installed a lot of shit via terminal but it is way out of my league so I stopped... I am having serious other issues with lua scripting which makes me doubt if it is not my (machine) that is acting up... I don't know how to remove all OTX stuff and start from scratch... As far as I can see, nothing is installed in other locations than "applications"... I there something in library that I can delete, or in preferences?

**Comment by Red-Devil74** [comment] 2017-04-16 20:51
What info are you looking for,.... I call it " Johny",... the SSD is called " Max Drive" and the old HDD is called "Big Mac",... they don't listen to me any more than my kids do... ;)

**Comment by mpaperno** [comment] 2017-04-17 00:00
Underlying cause is duplicate of #4796, so will close this.

(Sorry, storage and offspring issues are out of scope here :-D  )

**Closed by mpaperno** 2017-04-17 00:00 UTC
