### ISSUE TITLE
Telemetry simulator with Companion

### ISSUE THREAD

**Issue by aviat40** [opentx/opentx#7141] opened 2019-12-01 13:23 UTC
Hello,

I used to check my Lua widget with the telemetry simulator from companion but, 
from the lastest 2.3.x  version, with the same use of the software from 2.2.4, it is impossible after setting a value in the telemetry screen simulator, to check the value in the Lua widget.

Any idea, I have intalled the nightly version also to check and it is the same. The change seems to be from 2.2.4 to 2.3.x

Thank you if somebody else can try

**Comment by 3djc** [comment] 2019-12-01 13:27
Have you tried rediscovering your sensors, and reaffecting thoise to the widgets ?

**Comment by aviat40** [comment] 2019-12-01 13:47
Yes of course. But, I just checked on the radio for example, the RSSI and BtRx are as ID 248 ( I asked
you previously how this is coded ) and after backup the radio with companion, on the telemetry screen with companion, the ID is 25 on the model telemtry screen, and in the telemetry simulator within companion, it is 248 ...
So i think there is a bug somewhere with the new ID between COmpanion and Opent TX

**Comment by kilrah** [comment] 2019-12-01 14:17
Duplicate of #6862

**Closed as completed by kilrah** 2019-12-01 14:17 UTC

**Comment by aviat40** [comment] 2019-12-01 14:39
Thanks, Kilrah, I tried to check before in the list but !!
So the bug is known
