### ISSUE TITLE
X7: shorten the shutdown procedure

### ISSUE THREAD

**Issue by AABatteries** [opentx/opentx#4897] opened 2017-05-06 15:36 UTC
Right now the shutdown procedure of X7 requires the user to hold the power button for more than 3 seconds to perform a successful shutdown, anything shorter than that will result in return to normal state. Is it possible to enforce a full shutdown procedure after holding the power button for just 1 second? Could this be added as an option to the 'radio setup' menu, possibly with an adjustable value? This minor annoyance has been noticed by many hobbyists, and such a change would be a more viable solution than hardware modding. Thank you!

**Comment by 3djc** [comment] 2017-05-06 15:39
Sure, and the same wise hobbyist will screen when a model is lost or an accident happens "when I thought I was trimming" ...

Anyhow, this is a duplicate of #4639

**Closed by 3djc** 2017-05-06 15:39 UTC
