### ISSUE TITLE
Add Model Name sound to Setup page, Minor enhancement for 2.1 or beyond

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#1225] opened 2014-06-08 18:47 UTC
Add Model Name sound to Setup page, it seems to be the same sort of thing that most would setup for each model. It complements the Model image on setup page.

**Comment by projectkk2glider** [comment] 2015-11-22 20:35
Duplicate of #2404

**Closed by projectkk2glider** 2015-11-22 20:35 UTC
Labels: enhancement, Radio Firmware
