### ISSUE TITLE
ON368- Special Function issues

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#4789] opened 2017-04-13 10:04 UTC
With 2.2 ON363 special functions not working for the assignment of Adjust GV's, Volume, Play Value and Vario.

**Comment by schwabe** [comment] 2017-04-13 13:53
A bit more context please, which radio? Companion or Radio? What exactly is not working.

**Comment by clivemartin** [comment] 2017-04-13 14:08
Problem is with companion, both Horus and 9XD radio profiles.  Start new model, go through Wizard basic set up, in mix panel set up a GV for weight (GV1) on any channel, go to Special functions to assign a source for adjusting GV1  eg S1, that source cannot be set, dropdown menu goes grey, also same effect with trying to set Volume, Play Value and Vario.

Also have noticed same faults when trying to edit downloaded model files/setups from transmitters.

**Comment by mpaperno** [comment] 2017-04-13 19:35
Pretty sure this is a dupe of #4779 and fixed now.

**Closed by mpaperno** 2017-04-13 19:35 UTC
Labels: Bug, Companion
