### ISSUE TITLE
Companion 2.2.1N Simulator Crashes at Telemetry Display

### ISSUE THREAD

**Issue by r41065** [opentx/opentx#5263] opened 2017-10-03 16:26 UTC
![screenshot005](https://user-images.githubusercontent.com/15220072/31135574-b189c120-a865-11e7-821f-036385064e75.jpg)

Win 7, Companion2.2.1N395
[CompanionDebug_17-10-03_17-58-52.log](https://github.com/opentx/opentx/files/1353020/CompanionDebug_17-10-03_17-58-52.log)

 Taranis X9D:  If using one of this Telemetry Fields with Numbers

TX-Voltage
Time
Timer1
Timer2
Timer3

Companion Crashes when calling Telemetry Picture with Page Long.

All Working Telemetry Fields are Displayed with TELEx: "Name of Field"
( Sorry in the Moment i can not test at the real Tx....) 
With N388 was OK, not tested the Versions between.
Ralf

**Comment by schwabe** [comment] 2017-10-03 16:36
Can you include a saved otx file that crashes when you press simulate? That would make debugging for us much easier.

**Comment by r41065** [comment] 2017-10-03 17:13
[W3.otx.zip](https://github.com/opentx/opentx/files/1353229/W3.otx.zip)

maybe you can make .otx Files to Upload directly  

Ralf

**Comment by r41065** [comment] 2017-10-03 17:17
Simulator starts normal, crashes in the Moment i switch to Display the Telemetry Page with PAGE Long...

**Comment by schwabe** [comment] 2017-10-03 19:28
Hm works fine here:

![image](https://user-images.githubusercontent.com/1038539/31144674-b7797898-a881-11e7-945c-5e058cb3b805.png)

**Comment by kilrah** [comment] 2017-10-03 19:45
Can reproduce here, both X9D and X9D+ (he said X9D)...

**Comment by schwabe** [comment] 2017-10-03 19:51
hm cannot reproduce on my mac.

**Comment by kilrah** [comment] 2017-10-03 20:07
And I can't properly debug on windows since for some reason the simulators never load when built in DEBUG mode :(

**Comment by powercycle** [comment] 2017-10-04 02:30
can't reproduce on Ubuntu 16.04, but not built with debug...mine is from PPA.

**Comment by r41065** [comment] 2017-10-04 18:18
![screenshot_x9d_17-10-04_20-09-03](https://user-images.githubusercontent.com/15220072/31192006-3e69b2e6-a940-11e7-94cd-7816a3dbb026.png)
![screenshot_x9d_17-10-04_20-14-40](https://user-images.githubusercontent.com/15220072/31192171-c1424d36-a940-11e7-81f7-1a72e4b3b9c8.png)
Second Screenshot shows my working Lua Script

Update N396:
Value fromTimer3 is more than 11 hours, 41 Minutes, if this will be deleted from Page the  Simulator didn't crash but only shows strange Values for Battery Voltage, Time and Timer 1...

**Comment by r41065** [comment] 2017-10-22 05:54
![screenshot_x9d_17-10-22_13-49-28](https://user-images.githubusercontent.com/15220072/31858673-2a206d54-b730-11e7-9b9b-56b536c5acb3.png)

Update N412:
Simulator didn Crash anymore, only Display Strange Values on Battery Voltage, Timer 1 and Time...

**Comment by 3djc** [comment] 2017-10-22 06:57
Have you not rediscovered sensors and they are now all shifted ?

**Comment by r41065** [comment] 2017-10-22 10:31
because i'm in  China since a few weeks i can only open my otx-files from Version 2.2.0
therefore i said that i cannot test with my real TX.
i do not discover new sensors inside Simulator....

Headline from Telemetry Page and my Lua Screen display the correct Values, so the Data itselve seems to be Ok

**Comment by 3djc** [comment] 2017-10-23 05:27
There is indeed something very broken, will have a look at it

**Comment by r41065** [comment] 2017-10-28 14:51
Update N418 / N419
Simulator Crashes every First Time after new Installation of Companion when i call the Telemetry Page with Timer Values,
After that it shows the Strange Values..
Sorry but i cannot really find a pattern in behaviour

Ralf

**Comment by 3djc** [comment] 2017-10-28 15:28
The fix has not been merged yet, so it is not yet available in nightlies

**Comment by r41065** [comment] 2017-10-29 01:54
Ok

**Closed as completed** 2017-10-29 07:36 UTC

**Comment by r41065** [comment] 2017-10-31 10:26
![screenshot_x9d_17-10-31_18-19-02](https://user-images.githubusercontent.com/15220072/32219196-56de597a-be68-11e7-8f41-77c43012f0df.png)


Update N422:
- Values for Timer and Time are displayed correct

- Value from Battery Voltage shows same strange  behaviour as before, 

may i reopen this point or will there be an solution ?

Ralf

**Comment by 3djc** [comment] 2017-10-31 10:53
It is even stranger, it crashes the radio, so yes , there will be follow ups

**Comment by 3djc** [comment] 2017-11-07 07:31
I just merged the fix, should be ok tomorow
