### ISSUE TITLE
Have installed 3 more  Switches at X9E but cant simulate it at Companion

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3458] opened 2016-05-04 05:23 UTC
Hy,
latest Companion V2.1.8 and openTx

3  more switches at X9E installed, ok, works at openTx

but cant simulate it at Companion

what to do?

**Comment by projectkk2glider** [comment] 2016-05-04 06:38
Duplicate of #2377

**Closed by projectkk2glider** 2016-05-04 06:38 UTC
