### ISSUE TITLE
N371 - X9D+ - Hello.wav does not play on start-up

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#4885] opened 2017-05-01 03:24 UTC
Just upgraded from N362.  
Downloaded X9 zip
Synced SD using N371 version of companion.
hello.wav does exist on card but does not play.
This seems related to having existing files on the SD card or some other problem related to SD card.
Clearing the SYSTEM directory on the SD, then resyncing fixed the issue.
Needs more testing.

This occurred on Ubuntu Linux 16.04.02

**Comment by kilrah** [comment] 2017-05-01 06:31
Most likely duplicate of #4848, SD sync has issues. Just fix things straight on the card for now.

**Closed by kilrah** 2017-05-01 06:31 UTC

**Comment by powercycle** [comment] 2017-05-02 05:29
That is what I did.  I'll see if I can find a way to "break it" consistently.  Hopefully narrow down the sync issue.
Unless of course someone already knows what the problem is and just hasn't had time to fix it.

**Comment by kilrah** [comment] 2017-05-02 11:56
Nope, it isn't clear what the problem is.
