### ISSUE TITLE
companion 2.2 multiprotocol

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4225] opened 2017-01-12 14:32 UTC
Companion version : 2.2.0 RC8N360
Configured for a Taranis X9D

-> bug 1 :  the Field "Channels is gray. Not able to select the correct number of channels. Or the number of channels is not correct depending on the protocol.
How to reproduce
In the "Editing model" page
In the "Setup" tab
In the "External Radio Module" section
a) select "DIY Multiprotocol Module" in the "Protocol" field
b) select "KN" in the "Multi Radio Protocol" field
c) select "WLToys" in the "SubType" field

-> bug 2 : multiprotocol selection not saved
How to reproduce
a) after having selected the multiprotocol options, save the model
b) close it
c) open the same model
d) look at the multiprotocol options : the fields are empty

**Comment by kilrah** [comment] 2017-01-12 14:44
1st bug isn't one, the protocol between radio and module is specified as always being 16 channels. 
The module then chooses to use them or not depending on protocol.

**Comment by benoit35690** [comment] 2017-01-12 14:47
OK but it is not always 16.
If you first select "DSM2" for "Protocol", then "DIY Multiprotocol Module", the value is not updated and stays at 6.

**Comment by 3djc** [comment] 2017-01-15 07:47
I cannot reproduce that scenario on next

**Comment by kilrah** [comment] 2017-01-15 08:30
Yeah closing that - given the refactoring will change everything RC8 observations make no sense anymore, new testing is needed.

**Closed by kilrah** 2017-01-15 08:30 UTC
Labels: Bug, Companion
