### ISSUE TITLE
Companion Add Mixer Scripts tab to model editing. 

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#4228] opened 2017-01-12 16:44 UTC
Besides renaming custom scripts to mixer scripts it would be good to add a mixer scripts table just like we have Logical Switches, Special Functions and Telemetry tabs. 

Mixer/Custom scripts are available through the simulator so the underlying code seems to already be there.

**Comment by kilrah** [comment] 2017-01-12 16:49
Duplicate of #1488, see there why it will likely never happen.

**Closed by kilrah** 2017-01-12 16:49 UTC
