### ISSUE TITLE
Make text in syncing between radio and computer as it was before in 2.2.4

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8655] opened 2021-08-06 09:49 UTC
For a normal user, who only syncs between radio and local from time to time, the 'old' text was in my eyes much cleared. 

The question, what is source and what is destination is not clear, radio and local is much easier to get.

So please think of returning to the 'old' text.

br KH

![Unbenannt](https://user-images.githubusercontent.com/17964433/128492335-80fdc2ba-d91f-4db6-bc0a-ca9ad06366f7.png)

**Comment by therealzanfar** [comment] 2021-08-18 13:08
I agree that the new text is decidedly unclear--it appears as if a generic synchronization dialog has simply had the local/radio folder labels slapped on. I'm not sure the "old" text is the clearest--I'm not completely sure what "first" means here--but the use of "Local" and "Radio" vs "Source" and "Destination" at least match the corresponding folder selection labels.

**Comment by ghost** [comment] 2021-08-18 15:29
The problem, in my eyes, is here, that a user programming mainly with the radio sees the radio as 'source' and the computer running companion as 'destination', whereas a user doing the programming in companion sees the situation vice versa. Absolutely not clear, as it is now.

br KH

**Comment by elecpower** [comment] 2021-08-18 20:19
Duplicate of #8319

**Closed as completed by elecpower** 2021-08-18 20:19 UTC
