### ISSUE TITLE
Companion 2.1.8 - X9E - LS and RS missing - S1 and F1 reversed

### ISSUE THREAD

**Issue by hobby1946** [opentx/opentx#3597] opened 2016-06-14 17:41 UTC
Note:
on X9D S1, S2 the pots above
on X9E are S1, S2, the faders in the middle
F1, F2, the potentiometers are top (instead of S1, S2)
This is annoying when you transmits models of the Taranis on the X9E

This is not included in Companion 2.1.8 for X9E!
Since there is only F1-F2-S1-S2

The controller LS and RS are absent.

**Comment by kilrah** [comment] 2016-06-14 17:44
Duplicate of https://github.com/opentx/opentx/issues/2377

**Closed by kilrah** 2016-06-14 17:44 UTC
