### ISSUE TITLE
Companion Telemetry CheckBox not saved

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#3833] opened 2016-09-19 21:45 UTC
hi,
While using Companion, on telemetry screen the checkbox don't give us the screen for saving the file .eepe, if you only change that of course.

![capture7](https://cloud.githubusercontent.com/assets/2773940/18649985/f4ec1864-7ec2-11e6-8277-a0d89d9c6f8b.JPG)

![capture8](https://cloud.githubusercontent.com/assets/2773940/18649990/fd65f992-7ec2-11e6-8821-a94f43b7b8cd.JPG)

**Comment by kilrah** [comment] 2016-09-20 08:22
Duplicate of #3254

**Closed by kilrah** 2016-09-20 08:22 UTC
