### ISSUE TITLE
LIBEAY32.dll Error When Starting Companion 2.2

### ISSUE THREAD

**Issue by helinv** [opentx/opentx#4995] opened 2017-06-03 01:34 UTC
After running Companion 2.2, two errors popped up stating "The ordinal XXXX could not be located in the dynamic link library LIBEAY32.dll."

It turns out there are many programs that provide their own version of LIBEAY32.dll, and may put that file in the search path before the correct version needed by Companion 2.2.  By copying  %SystemRoot%\libeay32.dll to the Companion 2.2 program folder, Companion 2.2 starts without errors.

**Comment by mpaperno** [comment] 2017-06-03 02:06
This has come up before... #4787.

**Comment by kilrah** [comment] 2017-11-08 13:15
Duplicate of #5217

**Closed as completed by kilrah** 2017-11-08 13:15 UTC
