### ISSUE TITLE
Multi Protocol Module - power cycle bay when swapping module

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#4278] opened 2017-01-24 07:11 UTC
Occationally when using a multi protocol module I notice and issue in which the protocol does not change when swapping between two multi protocol module aircraft.

eg.  Flysky & DSMX

The solution is always to powercycle the radio.

I suspect the issue is a simple fix of powercycling the module bay when the models get swapped?

**Comment by projectkk2glider** [comment] 2017-01-24 09:22
Which radio and OpenTX version?

**Comment by robthomson** [comment] 2017-01-24 13:13
Has happened to me on horus and q7.  Latest firmware downloaded from companion :-)

**Comment by schwabe** [comment] 2017-01-24 15:04
Occationally when using a multi protocol module I notice and issue in which the protocol does not change when swapping between two multi protocol module aircraft.

How do you notice that? Does your model not work or does the new model not react?

**Comment by robthomson** [comment] 2017-01-24 15:44
New model does not bind.

Its as if the module is still stuck on the old protocol.

**Comment by 3djc** [comment] 2017-01-24 15:47
Is the red led turned on when that happens ?

**Comment by bsongis** [comment] 2017-02-14 19:00
Duplicate of #4404 which has been fixed yesterday
Well in fact #4404 is duplicate of this one, but it doesn't matter

**Closed by bsongis** 2017-02-14 19:00 UTC
Labels: Bug, Radio Firmware
