### ISSUE TITLE
Support widget setup for horus 

### ISSUE THREAD

**Issue by williajgr** [opentx/opentx#7280] opened 2020-01-07 11:56 UTC
*Before suggesting a new feature here, please search the open issue if there is already a request for the feature*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 3djc** [comment] 2020-01-07 12:02
And the issue is ????

**Comment by williajgr** [comment] 2020-01-07 14:20
This was supposed to be submitted as a feature request.  I would like to be able to set up the telemetry screens  in open-tx ie. setup the widgets for the telemetry screens.  Also be able to copy the telemetry screens to other models.  It takes a lot of time to set them up on the transmitter.

**Comment by kilrah** [comment] 2020-01-07 15:14
So you're talking of companion. Then please explain that in your submission instead of using a nondescript title and leaving the unfilled template in the comment.

Anyway, duplicate of https://github.com/opentx/opentx/issues/6257

**Closed as completed by kilrah** 2020-01-07 15:14 UTC

**Comment by williajgr** [comment] 2020-01-07 15:24
sorry, When I open Companion on my computer, the icon is Open-Tx  so I think of companion and open-tx as one and the same.  Sorry again my mistake.
