### ISSUE TITLE
X10S OTx 2.2.1 loud noise on headphone

### ISSUE THREAD

**Issue by hpolig** [opentx/opentx#5721] opened 2018-02-24 15:35 UTC
With opentx there is a loud noise like white noise with some distortions. This ist also with 2.2.2N528 but NOT with FrOS. It's not possible to reduce the noise with changing the volume level, it's always there in the same level. Testet with different earplugs und a beyerdynamic dt770pro 32 Ohm.
Using the speaker it is much lower.

As written above the noise ist only there under opentx, not under FrOs.

**Comment by 3djc** [comment] 2018-02-24 15:40
Well, using such an headphone for a monophonic output is a bit strange, but yes, we use the audio chip very differently than FrOS. The gain is that we have a much more dynamic management of audio events, but yes, on x10, for some reason, it seems to produce noise for some users

I am closing this as it is a duplicate of #5561

**Closed as completed by 3djc** 2018-02-24 15:40 UTC
