### ISSUE TITLE
Companion can't reference newly made input in a Special Function.

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#5933] opened 2018-06-01 23:14 UTC
When you create a new input in companion (nightly build 2 weeks ago, but probably all builds) you can't reference this input in a logical switch until you restart companion.
I believe a similar bug existed for logical switches, but that was fixed some time ago.

When creating this post I noticed this (last sentence)

https://www.rcgroups.com/forums/showpost.php?p=39657839&postco

**Comment by kilrah** [comment] 2018-06-02 06:14
You don't need to restart companion, just close/reopen the model.

There's already an issue open for all those propagation issues in companion.

**Comment by notlebowski** [comment] 2018-06-02 06:46
Sorry, wrote that down wrong.
Indeed, I just closed and reopened the model.

I didn't check github because I knew that the one involving LS was fixed and assumed that if there was a ticket already that it was closed.

Thanks

**Comment by mpaperno** [comment] 2018-06-02 19:26
Can't reference it where, exactly?  Just tested latest code and new inputs show up fine, e.g. in V1/V2 fields.  AFAICT it should be the same 2 weeks ago also.

**Comment by mpaperno** [comment] 2018-06-03 04:27
@notlebowski  In the RCG post you said the problem is in the Special Functions panel. Not "in a logical switch" as you stated above... is that right?

In which case that's correct, and will be fixed by #5936 .

**Comment by notlebowski** [comment] 2018-06-03 07:41
@mpaperno  I was just about to post that I just tested it and you were right that it works in LS...
It was already 2 weeks ago that I encountered it and didn't have github then.
Good that you read my RCG-post....!!

I have another one which is more cosmetic than functional.
Just changed a name of a telemetry item and that change didn't get propagated across the setup until model close/open.
I wouldn't mind if that would not be fixed
I leave it up to you

**Comment by mpaperno** [comment] 2018-06-03 16:25
> Just changed a name of a telemetry item and that change didn't get propagated across the setup until model close/open.

This seems to be also fixed... or at least I can't recreate w/out more specifics.  I have to assume it worked in the LS editor already (in nightlies), but is now fixed in SF editor as well (or will be once latest fixes are merged).

**Comment by notlebowski** [comment] 2018-06-03 19:30
Hi..
Not sure if we speak of the same thing and if it should work on N621
I just tested this on N621:

![tele3-1](https://user-images.githubusercontent.com/39838998/40890371-3cd2dfe0-6775-11e8-8413-92f0fb756a35.PNG)
![tele3-2](https://user-images.githubusercontent.com/39838998/40890372-3f6636ee-6775-11e8-8ad4-39cce70edde6.PNG)

_change **3S** to **3SB**_

![tele3-3](https://user-images.githubusercontent.com/39838998/40890375-417c85dc-6775-11e8-9a0a-227e2d2fef79.PNG)
![tele3-4](https://user-images.githubusercontent.com/39838998/40890376-449f6b9e-6775-11e8-84c1-9c0b6b8bf0c8.PNG)

_close/open model editing:_

![tele3-5](https://user-images.githubusercontent.com/39838998/40890377-4843b9da-6775-11e8-923f-6a625d12b684.PNG)

**Comment by mpaperno** [comment] 2018-06-03 19:47
Yep, we're on the same "page."  :)  Already worked for LSs, and confirmed fixed for SFs in #5936.

**Closed as completed** 2018-06-03 21:20 UTC
