### ISSUE TITLE
"Write Models and Settings to Radio" dialog corrupts model data

### ISSUE THREAD

**Issue by sbuhre** [opentx/opentx#7575] opened 2020-05-03 12:49 UTC
The "Write Models and Settings to Radio" dialog corrupts "Multi Radio Protocol" of external Radio Module "DIY Multiprotocol Module"

Testcase:

Companion 2.3.7 on Windows 10 Build 1909 english
Open Companion
Create New Document (File|New)
Add Model (Wizard): Next, Next... Agree, Finish
Edit Model
Change "external Radio Module" to: "DIY Multiprotocol Module"
Change "Multi Radio Protocol" to "HoTT" (value is important, internal ID has to be > 16)
Close edit dialog
Open "Write Models and Settings to Radio" dialog
Close "Write Models and Settings to Radio" dialog
Edit Model
"Multi Radio Protocol" is corrupted: Changed from "HoTT" to "Devo"

**Comment by 3djc** [comment] 2020-05-03 12:56
Please check n800, should be fixed already (and this is a duplicate of #7548)

**Comment by 3djc** [comment] 2020-05-03 13:27
Need to check how it behaves on companion model creation

**Comment by 3djc** [comment] 2020-05-03 14:26
I'm sorry but I just tested N800 Windows downloaded from Otx website, creating a model with wizard, selecting multi, then HoTT.

Transfer to radio (tested T16 intenral and X10 external), both ok on HoTT

**Comment by sbuhre** [comment] 2020-05-03 15:46
where do I get n800? I can only see n200.

https://downloads.open-tx.org/2.3/nightlies/companion/windows/

The problem is not the transfer to the TX. The settings are corrupted within companion. 
Just open the "write models and settings to radio" dialog. Don't do a transfer. Close it and edit the model again-> model corrupted.

**Comment by 3djc** [comment] 2020-05-03 15:53
ok seem to apply only to non colorlcd radio, works fine on horus

**Comment by sbuhre** [comment] 2020-05-03 16:09
yes, tested with X-Lite Pro

**Comment by 3djc** [comment] 2020-05-04 08:47
Fixed by https://github.com/opentx/opentx/commit/6f90454bd9dc58c5fff27ba3d167ce36997219bc

**Closed as completed by 3djc** 2020-05-04 08:47 UTC
