### ISSUE TITLE
Horus X12S - 2.3.13 servo movement jittery/delayed

### ISSUE THREAD

**Issue by dl3it** [opentx/opentx#8608] opened 2021-07-08 20:20 UTC
Radio used: Horus X12S, internal ACCESS module, ACCST mode; all components flashed with latest firmware

Using opentx 2.3.11, everything works fine.

Using opentx 2.3.13, servo movement is jittery and sometimes up to 1s delayed. I tried several receivers, X8R, RX8R, XM+, ... same problem. Servo movement is a bit smoother when using D8 mode, D16 mode is unusable.
Interesting sidenote: I cleaned the whole radio; new formatted sdcard, standard setup, automatic generated model. Everything works fine. After adding the next model (with built in wizzard), the new model shows jitter, the first model remains ok. Every additional model shows the problems; no difference between models new created or imported by the companion.

**Comment by 3djc** [comment] 2021-07-08 20:21
Please try nightly N530 or later

**Comment by kilrah** [comment] 2021-07-08 20:24
Duplicate of #8575

**Closed as completed by kilrah** 2021-07-08 20:24 UTC

**Comment by dl3it** [comment] 2021-07-08 20:45
seems to be fixed :-)

Thanks for the super fast reply...
