### ISSUE TITLE
Companion 2.1.1 Model Wizard limited to 8 channels

### ISSUE THREAD

**Issue by rguptaca** [opentx/opentx#2711] opened 2015-08-15 06:47 UTC
Select Plane
Standard flying wing
Throttle Ch 1
Aileron controlled by Ch 2 and 5
Flaps controlled by Ch 6 and 8
Airbrakes controlled by Ch 7 and 4
Tail elevator and rudder
Rudder Ch 3
Elevator Ch 3 (same as rudder)

**Comment by projectkk2glider** [comment] 2015-08-15 11:48
Duplicate of #2624

**Comment by projectkk2glider** [comment] 2015-08-15 11:50
Ok, the CH3 duplicate usage is a bug. 

But as explained in #2624 such complex setup is beyond the wizard.

**Comment by griebd** [comment] 2015-08-15 13:25
just wait a second... some clarifications:

@projectkk2glider, it's a companion issue, by the title, not radio firmware.... ;)

@rguptaca, companion 2.1.1, not 2.2.1 (there is no such)... ;)

**Comment by griebd** [comment] 2015-08-15 14:29
Was fixed in 2.0 already, probably missed to port to next at the time!

Thing is, the fix is only a warning so people know they should do things by them self... Again, the wizard is just a show up for newcomers. :wink:

**Comment by rguptaca** [comment] 2015-08-15 17:14
Where did I write 2.2.1? If I did apologies for causing confusion if any. 
For beginners maybe simplify the wizard to just TAER and maybe Gear with only AIL having a choice of 2 seperate or 1 channel. Most off the shelf planes have simple setups.  Or at the end mention the 8 channels have been exceeded. 
I did read the titles of every open issue before posting. 
Only trying to help.

**Comment by griebd** [comment] 2015-08-15 18:44
no problems @rguptaca, I thought it was a typo in the title and changed it... and the issue is valid as the fix was done only in 2.0.15 and not in 2.1 and later. (the issue for 2.0 was #2091)
This issue will auto close as soon as the fix get merged for 2.1.2.

**Closed** 2015-08-16 07:02 UTC
Labels: Bug, Companion, Priority-Low
