### ISSUE TITLE
Access violation when launching Simulator from Mixes tab

### ISSUE THREAD

**Issue by cass3825** [opentx/opentx#2971] opened 2015-10-15 01:52 UTC
![screenshot 4](https://cloud.githubusercontent.com/assets/15134084/10502783/218b9a5e-72b5-11e5-8e70-362f846a841e.png)

**Comment by projectkk2glider** [comment] 2015-10-17 17:40
Which version of Companion? Anything particular about the model that causes the crash or does it crash if you just create and simulate empty model? If only particular model, then post it here.

**Comment by cass3825** [comment] 2015-10-17 19:00
Version 2.1.3
Simulator crashes when using logic switch to enable a Flight Mode.  Confirmed with blank model using L1 switch entry on Flight Mode 1.

**Comment by projectkk2glider** [comment] 2015-10-17 19:23
Damn, cant reproduce on Linux. Perhaps the change to strip companion binary (`SET(CPACK_STRIP_FILES TRUE )`) in 51b8d70cc650605f85a42e37a74b07b5ccddd26f was not so smart (it was made by me :stuck_out_tongue: ). Now the backtrace is empty and not very useful.

**Comment by projectkk2glider** [comment] 2015-10-17 19:25
@cass3825 which radio are you simulating?

**Comment by bsongis** [comment] 2015-10-17 20:53
Yes strip files was a good idea :) I will try to find another minute for this one.

**Comment by cass3825** [comment] 2015-10-17 21:12
@projectkk2glider taranis plus.

**Comment by mpaperno** [comment] 2017-04-11 17:00
Cannot recreate in `next`, most likely fixed by the numerous other changes in 2.2.

**Closed** 2017-05-11 15:17 UTC
Labels: Bug, Companion
