### ISSUE TITLE
Haptic vibration issue with new Open TX firmware

### ISSUE THREAD

**Issue by GRCT42** [opentx/opentx#2854] opened 2015-09-08 21:02 UTC
After installing the new firmware my radio continues to vibrate when turned on. (Haptic vibration) Not sure what's on the go. Any help would be appreciated.

**Comment by bsongis** [comment] 2015-09-08 21:06
Perhaps you flashed the wrong firmware Taranis / Taranis Plus

**Comment by GRCT42** [comment] 2015-09-08 21:35
Here's a pic of the currently installed firmware version on myTaranis Plus.
![img_1408](https://cloud.githubusercontent.com/assets/12574350/9747953/b11af2c6-565b-11e5-9788-a51e4dcd69ad.JPG)

The radio vibrates erratically! not sure if it has to do with loss on signal from the receiver? I have a ezuhf jr module installed with 4ch lite.

I heard somewhere that you now have to create you're own Telemetry alerts? Not sure how to do this.

Thanks for the reply...

**Comment by GRCT42** [comment] 2015-09-08 21:36
Whats this Discover New Sensors?

**Comment by kilrah** [comment] 2015-09-09 00:01
Duplicate of #2722.
And you won't get telemetry out of an EzUHF.

**Closed by kilrah** 2015-09-09 00:01 UTC

**Comment by GRCT42** [comment] 2015-09-09 02:52
yeah the same issue as the rest of the guys in that other post... thanks for pointing me in the right direction.

**Comment by hrenz** [comment] 2015-09-09 14:44
there are 4-6 reasons of vibration
some Alarms 
Mid Potis
Timers
Low Batt level
lost of Kalibration values
and so on.
