### ISSUE TITLE
companion X9E incorrect operation of controls 

### ISSUE THREAD

**Issue by Poppy-Ann** [opentx/opentx#3093] opened 2015-11-22 11:33 UTC
I have been trying to use Companion 9X with my Frsky X9E but some of the controls operate the wrong function in the simulate mode, the analog settings are incorrect when looking at the calibration page.
control	operates 	
LS		nothing		
RS		S1 (inverted)	
S1		F1		        
S2		F2		        
Nothing		LS		
Nothing		RS

on the analog input page

control        operates analog
LS              08 
RS              09
S1              05
S2              06

this shows that the LS control works but gives nothing out in the calibration page, and there are no  controls for F1 to F4 or for any of the extra switches.

I am not sure if this is the correct place of reporting faults so if not I am sorry.

Regards Poppy Ann.

**Comment by projectkk2glider** [comment] 2015-11-22 11:34
Duplicate of #2377

**Closed by projectkk2glider** 2015-11-22 11:34 UTC
