### ISSUE TITLE
Special Function Increment function (Horus OpenTX)

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#3887] opened 2016-10-07 18:03 UTC
Using +=1 increases the GVAR value by 10, not 1 as would be expected, and value continues to increase for as long as switch is true.

**Comment by projectkk2glider** [comment] 2016-10-07 18:19
I see the problem that increase never stops as long as condition is true. In my mind it should only do one increase or decrease when the condition becomes true.

Even if you use EDGE LS, that switch is ON for 100ms which is enough to do 10 increments instead of one.

**Comment by projectkk2glider** [comment] 2016-10-07 18:20
I also think it is not Horus only issue, it affects all ARM platforms.

**Comment by strgaltdel** [comment] 2016-10-08 08:28
... duplicate of #3858 ?

**Comment by projectkk2glider** [comment] 2016-10-08 08:36
Yes

**Closed by projectkk2glider** 2016-10-08 08:36 UTC
Labels: Bug, Radio Firmware
