### ISSUE TITLE
Added switch problem. 9XE

### ISSUE THREAD

**Issue by bigbobed** [opentx/opentx#2821] opened 2015-08-31 19:13 UTC
I relocated the toggle sw and plugged it into the sw J slot. I renamed the SH.wav files to SJ.wav in \SOUNDS\en\<model name> folder on the SD card, but the tracks don't play. Yes I have defined SJ in the setup and it works as an input and will play the sounds as an input to a Special Function.

**Comment by kilrah** [comment] 2015-08-31 19:20
Duplicate of #2754

**Closed by kilrah** 2015-08-31 19:20 UTC
