### ISSUE TITLE
Companion 2.2.1 Logical Switches V1 V2 Menu Missing Lxx Values

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5630] opened 2018-01-15 20:03 UTC
For comparative functions such as a=x,a <b 
L01 to L64 show up in the menu.

For AND, OR, XOR Edge, and Sticky
L01 to L64 does not show up.
Only logical switch configured in a previous editing session show up.

To duplicate this do the following
- New document
- New model
- Edit model
- Logical Switch Tab
- Configure L01 to L06 logical switches in any way 
- L07 try and configure AND with V1 and V2 (you will notice the problem)
- CLOSE the edit model window
- Edit same model again
- Logical Switch Tab
- L07 try and configure AND with V1 and V2 (you will notice that now the configured LS show up)
![lxxmissing](https://user-images.githubusercontent.com/20209851/34959615-46fb16d2-fa05-11e7-8d41-0384adc65b01.png)

**Comment by RCdiy** [comment] 2018-01-15 20:06
![lxxmissing2](https://user-images.githubusercontent.com/20209851/34959688-9912b84e-fa05-11e7-9b88-4adbe807b2fa.png)

**Comment by mpaperno** [comment] 2018-01-15 22:00
This has been fixed early in v2.2.2 with 76ce186 . For 2.2.1 the only workaround is to reopen the window.

Duplicate of #5556 and #5607

We should make this a sticky or something... :) or maybe leave it open (and tagged somehow as fixed) if people don't search closed issues?

**Closed as completed by mpaperno** 2018-01-15 22:00 UTC

**Comment by 3djc** [comment] 2018-01-16 06:20
Not sure what the magic receipe is, I keep closing issue for things in the release notes !

**Comment by RCdiy** [comment] 2018-01-16 18:43
I apologize. This was posted in a forum. Kilrah suggested an issue. I made one. Usually I check on rocket chat before.
