### ISSUE TITLE
Expo on throttle from -100 to 100 instead of 0

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3235] opened 2016-01-17 09:34 UTC
When using the throttle channel in a conventional way the expo curve implied on it is not the one you want. It should be 1 curve starting at -100

I checked how Futaba is doing it and they too have another expo for throttle.

There's a similar issue posted here, but there they want it even more flexible. I think one should make a custom curve then.
https://github.com/opentx/opentx/issues/1654

**Comment by kilrah** [comment] 2016-01-17 09:43
Duplicate of that #1654 really.

**Closed by kilrah** 2016-01-17 09:43 UTC
