### ISSUE TITLE
GVAR min/max range limits incremental change steps value in Special Functions (Companion)

### ISSUE THREAD

**Issue by makcorner** [opentx/opentx#6161] opened 2018-09-08 09:20 UTC
When you define a min/max limit on GVAR in flight mode tab, i.e.:

![image](https://user-images.githubusercontent.com/11466449/45252534-4690d600-b39b-11e8-9929-4073ac67450e.png)

than you cannot define anything outside of allowed min/max range in Special Functions, even when using "Increment":

![image](https://user-images.githubusercontent.com/11466449/45252548-75a74780-b39b-11e8-9fa9-131632fdb792.png)

I assume when "Increment" is selected, there should be still possibility to have in example 0.1 as increment value. Here I cannot as 0.1 is outside of allowed -100/-80 limits.

Limits are valid for direct value changes.

Easy to reproduce this using Companion 2.2.2

**Comment by kilrah** [comment] 2018-09-08 09:49
It's likely your Prec setting rather than the limits, can you check?

**Comment by makcorner** [comment] 2018-09-08 09:52
It is rather not. I had it on 0.1 already, and got surprised when applied min / max limits. Incremental value changed to -80 and could not set it up to anything outside -100/-80 anymore.

**Comment by kilrah** [comment] 2018-09-08 10:04
OK, thanks

**Comment by makcorner** [comment] 2018-09-08 10:19
No worries. I didn't check it on the radio, but will do shortly.

**Comment by mpaperno** [comment] 2018-09-08 17:15
Same on radios.

**Comment by elecpower** [comment] 2018-09-08 23:09
Duplicate of #5602. There is an open PR #5609 with the fix.

**Comment by mpaperno** [comment] 2018-09-08 23:18
Indeed! With another linked duplicate even.  And the PR needs to be merged.

**Closed as completed by mpaperno** 2018-09-08 23:18 UTC
Labels: Bug, Radio Firmware, Companion
