### ISSUE TITLE
SDL not packaged with Companion 2.1.1? (OSX)

### ISSUE THREAD

**Issue by pkiela** [opentx/opentx#2673] opened 2015-08-08 15:01 UTC
Launching Companion but I'm immediately greeted with this error. Going through it, it looks like SDL framework isn't being included?

Process:               companion [25529]
Path:                  /Applications/companion.app/Contents/MacOS/companion
Identifier:            companion
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           companion [25529]
User ID:               501

Date/Time:             2015-08-08 10:55:09.261 -0400
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        8C80143F-6442-2B8E-00DD-921076FE2625

Sleep/Wake UUID:       0C1F7F7B-9686-41D8-A994-ED61D9441A4E

Time Awake Since Boot: 110000 seconds
Time Since Wake:       7 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/SDL.framework/Versions/A/SDL
  Referenced from: /Applications/companion.app/Contents/MacOS/companion
  Reason: image not found

Binary Images:
    0x7fff6d1df000 -     0x7fff6d215837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld
    0x7fff98fbd000 -     0x7fff98fbeff3  libSystem.B.dylib (1213) <AD223AEB-237D-35A3-825E-EECF95916838> /usr/lib/libSystem.B.dylib

Model: MacBookPro11,1, BootROM MBP111.0138.B15, 2 processors, Intel Core i5, 2.6 GHz, 16 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.5f8 15969, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

**Comment by projectkk2glider** [comment] 2015-08-08 15:36
Duplicate of #2667

**Closed by projectkk2glider** 2015-08-08 15:36 UTC
