### ISSUE TITLE
Modifying SPORT parameters using the Taranis

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2001] opened 2015-01-14 00:57 UTC
Mike Bland made it possible to use the Taranis to upgrade the firmware of the SPORT devices. Frsky has Windows software to change parameters like sample rate (the one I'm interested in).
I have already ordered the USB-stick so I can use the Windows software for this, but it would be nice if we in the future could do it with the Taranis.

Mike was interested in doing this, but he needs to find time.

**Comment by kilrah** [comment] 2015-01-15 09:32
Duplicate of #1599

**Comment by fraternl** [comment] 2015-01-16 00:52
Hi Kilrah...
This is not a duplicate of 1599
It's updating the parameters of the SPORT-devices.
Not updating the firmware.
Mike wasn't even aware until a few days ago.
He got in touch with Frsky that gave him the info to do this.... one day.

**Comment by kilrah** [comment] 2016-06-14 19:35
#3461

**Comment by griebd** [comment] 2016-06-14 21:30
nice feature in my opinion, why close it? hope it was a miss click while commenting... reopening it! If I'm wrong, please explain why it's not going to happen...
p.s.: IF and WHEN I have the time I will look at implementing it, if not already implemented...

**Comment by griebd** [comment] 2016-06-14 21:32
sorry, my mistake! now I see you moved it to #3461...

**Closed** 2016-06-14 21:31 UTC

**Comment by bsongis** [comment] 2016-06-15 05:47
It's already done
