### ISSUE TITLE
Sounds on 9XR-Pro not working anymore (Release v2.1.1)

### ISSUE THREAD

**Issue by BobMarley100** [opentx/opentx#2695] opened 2015-08-11 14:33 UTC
Same Problem as in Issue #1690.

**Comment by bsongis** [comment] 2015-08-11 16:09
Duplicate of #2665 which is already fixed. Please give a try at nightly builds!

**Closed by bsongis** 2015-08-11 16:09 UTC

**Comment by majkkky** [comment] 2015-08-12 18:14
Same Problem as in Issue #2665

**Comment by rafabene** [comment] 2015-08-14 21:46
How can I get access to the nightly builds ?

**Comment by kilrah** [comment] 2015-08-14 22:35
The link is on the "Links" page of open-tx.org. Download a nightly companion build from there, install, check the "get nightly builds" checkboxes in the settings, download firmware with your options.
