### ISSUE TITLE
Screen Problem in the Folder Models

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4041] opened 2016-11-19 00:13 UTC
I copy a ready made model Polizia in a folder Heli. Than I changed some data in the mixer, make a new name DARIO 600 PRO D8 prepare all. After you will load again a model from the folder Heli (in my example) you see a wrong sreen from that model DARIO 600 Pro D8. And you cannot read the name in the screen. See pics.

![20161119_005945](https://cloud.githubusercontent.com/assets/22581690/20450988/3a408416-adf5-11e6-8716-8c172b578d2e.jpg)
![20161119_005959](https://cloud.githubusercontent.com/assets/22581690/20450989/3a4203f4-adf5-11e6-813b-5de1ae35b4b4.jpg)
![20161119_010121](https://cloud.githubusercontent.com/assets/22581690/20450990/3a448322-adf5-11e6-9763-2acf43b003df.jpg)

**Comment by Githubbachelor** [comment] 2016-11-19 00:18
You can move the Model but the hacked screen from picture and name is still there. If you make a next new model it is clear.

**Comment by 3djc** [comment] 2016-11-19 07:33
I cannot reproduce this issue, (please join sd card backup), but I could see a minor one when model name is too long:
![image](https://cloud.githubusercontent.com/assets/5167938/20453883/baad0b78-ae32-11e6-9b6c-325b3c263e53.png)
![image](https://cloud.githubusercontent.com/assets/5167938/20453887/ca71d1ce-ae32-11e6-8523-40ab138fd880.png)

Name is cut

**Comment by bsongis** [comment] 2016-11-19 07:39
I also think that the name length is the reason of the issue. We should add some protection to avoid writing  outside the BitmapBuffer (the one created in modelslist.h:52)

**Comment by 3djc** [comment] 2016-11-19 08:07
@bsongis : I have a proposed patch (https://github.com/opentx/opentx/commit/b0df773c03090ba0fdbc5b13ac1eb07e27d23ee0), let me know what you think

**Comment by bsongis** [comment] 2016-11-19 08:57
You also may write with a smaller font?

**Comment by 3djc** [comment] 2016-11-19 09:01
I sure can, here is how it looks:
![image](https://cloud.githubusercontent.com/assets/5167938/20454362/24652102-ae3f-11e6-9caa-ab004f8225eb.png)

**Comment by 3djc** [comment] 2016-11-19 09:09
But even smlsize may noit always be enough:
![image](https://cloud.githubusercontent.com/assets/5167938/20454399/4fbeb93e-ae40-11e6-81ec-87baf1cd3d1e.png)

**Comment by 3djc** [comment] 2016-11-19 09:13
This is smalsize + char number cut

![image](https://cloud.githubusercontent.com/assets/5167938/20454418/bd4bffde-ae40-11e6-9140-b8744144dd81.png)

**Comment by 3djc** [comment] 2016-11-19 09:20
Even with smallsize, we can fit only 13 out of the 15 chars allowed for model name when using the larger chars

**Comment by 3djc** [comment] 2016-11-19 10:01
I'm rearranging the whole screen, stay put :)

**Comment by 3djc** [comment] 2016-11-19 10:12
![image](https://cloud.githubusercontent.com/assets/5167938/20454708/03a85574-ae49-11e6-8b99-817914cc700b.png)

**Comment by Githubbachelor** [comment] 2016-11-19 10:19
Hi djc and Bertrand
do you have a actuall patch from now whithout deleting anything in my ready models , which I can install? And how I must do? Where?

**Comment by 3djc** [comment] 2016-11-19 10:20
If my patch is accepted, it will be available in the next nightly

**Comment by kilrah** [comment] 2016-11-19 10:32
The only thing you'll have to do is update when the next RC is out. Leave those models alone until then.

**Comment by Githubbachelor** [comment] 2016-11-19 10:33
ok

**Comment by Githubbachelor** [comment] 2016-11-19 10:39
By the way, are the internal multi protocols in OpenTX working with the multi modul from Banggood Version2 WITHOUT PPM ? Someone told only to make a bridge in the multimodul and switch to zero Position, and it works. Did someone test that? 1000 people write anything without a 100% result. And a very important protocol is the Nine Eagle protocol which is written but nowhere to find?

**Comment by kilrah** [comment] 2016-11-19 11:04
Yes they work. Selections may not include the very latest things that were added to the multi module, but you can always use CUSTOM to reach those until they get added.

**Comment by Githubbachelor** [comment] 2016-11-19 11:13
Yes I want to find that Chat but where? Do you have a link for that. I am still new in Github and only find that here

**Comment by Githubbachelor** [comment] 2016-11-19 11:16
I would like to have a contact to you outside from here, over email if possible from Bertrand, Andre 3djc, kilrah. How can I write to you ?

**Comment by bsongis** [comment] 2016-11-19 11:19
Here:
https://opentx.rocket.chat/channel/OpenTX_General

**Comment by 3djc** [comment] 2016-11-20 08:11
This is fixed in next RC.

**Closed by 3djc** 2016-11-20 08:11 UTC
