### ISSUE TITLE
Throttle Cut went to full throttle

### ISSUE THREAD

**Issue by JohnRCox** [opentx/opentx#5447] opened 2017-12-01 03:41 UTC
I have a Taranis +. I don't know how to get the version number of the software. I needed to reset the throttle sensitivity as a control arm had failed. I completed this successfully. After a successful flight, I pressed the throttle cut switch, which was set to give a -120 counts and which had worked to kI'll the enine before. The throttle went to a high position and the plane was destroyed when it hit a table leg. My belief is that that the setting is not being clamped to a negative number and can wrap around.

**Comment by 3djc** [comment] 2017-12-01 06:15
ok, you seem new here, so i'll explain a little. This is  a bug tracking system, not an end user support tool. You should use this when you have reviewed your issue with knowledgeable peers in support forums, in your club,.., that the issue is not with your setup, and is actualy a Opentx software issue.

During that  investigation, you should have discovered ways to replicate the problem in details, and thats what we need posted here in order to solve bugs.

I'm closing this for now as we cannot do anything at this stage. If you find ways to repliacte the issue that demonstrate it is an OpenTx issue, feel free to re-open

**Closed as completed by 3djc** 2017-12-01 06:15 UTC
