### ISSUE TITLE
Companion 2.2.1 - UpdateGV with Increment: can't enter valid increment values

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#5686] opened 2018-02-11 18:45 UTC
Steps to reproduce:

1. With GV1, set min=-100 and max=-20
2. Create SF with action = UpdateGV, set mode to Increment

The increment field is locked against entering a valid positive value e.g. 5

[Download minimal test file](https://www.dropbox.com/s/yxo46km2irajj46/companion_no_pos_increments_for_gv.otx?dl=0) (for 2.2.1/X9D)

It seems to only affect Companion (works fine if increments are entered directly in the transmitter).

**Comment by kilrah** [comment] 2018-02-11 22:29
Duplicate of #5602

**Closed as completed by kilrah** 2018-02-11 22:29 UTC
