### ISSUE TITLE
Companion 2.2(n369) Copy and Paste of Special Function causes big problems

### ISSUE THREAD

**Issue by calril312** [opentx/opentx#4849] opened 2017-04-24 05:17 UTC
If you copy a special function and paste it to a new special function line in companion model edit, it changes all special functions to OverrideCH1 except for the one that was pasted.
![beforecopy](https://cloud.githubusercontent.com/assets/27895043/25323173/d37b4378-287a-11e7-925d-20690fc0c23d.jpg)
![afterpaste](https://cloud.githubusercontent.com/assets/27895043/25323176/d86ff022-287a-11e7-9e82-0c595b02090e.jpg)

**Comment by 3djc** [comment] 2017-04-24 05:20
Duplicate of already fixed #4825

**Closed by 3djc** 2017-04-24 05:20 UTC

**Comment by mpaperno** [comment] 2017-04-24 07:07
Until next release, workaround is to close and re-open the model editor.  The actual actions are not being modified, the problem is display-only.
