### ISSUE TITLE
Helicopter Option

### ISSUE THREAD

**Issue by robblot** [opentx/opentx#2083] opened 2015-02-16 13:15 UTC
When I try to create a new model(helicopter), the helicopter option is inactive. I am using version 2.0.15. I just learned about the Taranis transmitter and want to play with the companion a bit before I decide to purchase one.

**Comment by jermoo** [comment] 2015-02-16 13:25
The Heli option in the Model Wizard is still in work. Many functions in LUA are still not available. What you are experiencing is normal. 
We have manual steps to create Heli models depending on your needs.

**Comment by robblot** [comment] 2015-02-16 13:37
Thank you... where can I find this information please?

**Comment by projectkk2glider** [comment] 2015-02-16 13:38
True, helicopter part of the new model wizard is still missing, we are still looking for a brave soul to write it. You can read http://open-txu.org/ccpm-for-taranis/ and recreate configuration yourself.

**Comment by projectkk2glider** [comment] 2015-02-16 13:39
Duplicate of #906

**Closed by projectkk2glider** 2015-02-16 13:39 UTC
