### ISSUE TITLE
USB data link between a PC and the Taranis

### ISSUE THREAD

**Issue by TexasFPV** [opentx/opentx#601] opened 2014-01-25 18:23 UTC
A feature I would find useful is a real time USB data link between a PC and the Taranis.  The PC could receive telemetry from the Taranis, and the Taranis could receive control commands (e.g. from a joystick) that could be relayed to a model.

**Comment by projectkk2glider** [comment] 2015-01-17 17:32
Duplicate of #2008

**Closed by projectkk2glider** 2015-01-17 17:32 UTC
Labels: Companion, enhancement, Radio Firmware, Taranis
