### ISSUE TITLE
SF "increment/decrement GV" doesn't work as intended in 2.2n

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#3858] opened 2016-09-28 06:52 UTC
Hi,
just made some migration tests to 2.2n358

oTx 2.18 was able to use GVs as a counter by define some SFs like this

![sf gvar](https://cloud.githubusercontent.com/assets/20392683/18903285/89e9ce7a-8558-11e6-89e6-f8b2bdd9f79f.jpg)

so the stepping rate was +/-1 

after converting to 2.2, the GV value jumps quickly to its new defined max/min values (+/- 1024 as standard?) by pulling/pushing the configured switch.
incremental value seems to be completely ignored

regards
Udo

**Comment by Viruswelt** [comment] 2016-09-30 09:41
i have the same problem with the Trim Switches. i use these switches on taranis to ingrease/degrease a Gv +1/-1 to ajust a gyro gain.

**Comment by kilrah** [comment] 2016-10-16 19:35
Set/Reset SFs have the same problem

**Comment by fraternl** [comment] 2016-10-17 07:41
The action itself apparently requires an interval to prevent a race condition, but the SF itself could be expanded in a way that it works the same as "Play Track" where an interval can be given.  !1x 1x 1s 2s 3s instead of the enable/disable checkbox.

This also means we would lose the enable/disable option.
This could be solved by adding a 0x (zero times).

**Comment by projectkk2glider** [comment] 2016-10-17 07:56
The SF reset problem is the same in 2.1 release! I wonder how that went unnoticed. :worried:

**Comment by 3djc** [comment] 2016-10-17 08:12
I think it could make sense to apply the same options as play track to a few more fonctions. For some, it is unclear how they should behave when coupled with a non edge  trigger (screenshot,...)

**Comment by fraternl** [comment] 2016-10-17 08:12
If I would have simplified my setup a year ago, I would have noticed then.
It did take me several rows of LS's



L1  LowC < 3.7 Delay(5s)
L2 LowC > 4.18 Delay(5s)
L3 Sticky(L2, L1)
L4 Edge(L3, [1:instant]) 


SF1 L4 - Reset(Flight)
SF2 L4 - Reset(Cnsp)
SF3 L4 - Play Track(reset) 1x

**Comment by projectkk2glider** [comment] 2016-10-17 08:19
Most of the functions that need it have an activation flag that handles them correctly - ie only fire once when the switch becomes true. One such function is Screenshot. Some are missing this processing step.

**Comment by 3djc** [comment] 2016-10-17 08:20
Yes, but what you might want to do by using a 'constant' on trigger, il to take more than one. Rather than decide which one should be runed once or not, I thjink it could make sense to leave that choice to the user in the same way as playtrack does

**Comment by kilrah** [comment] 2016-10-17 08:27
If you want repeated events you can use a Timer LS, and have even more precise control.

**Comment by strgaltdel** [comment] 2016-10-23 18:09
Just to get confirmed:
the solution has not made his way into RC7, right?
I have to wait for RC8 or make an interims compiling?

Today i got the same wrong behavior after update to nightly 359 (Taranis X9e)

**Comment by kilrah** [comment] 2016-10-23 18:10
Yes it has and should be fixed.

**Comment by strgaltdel** [comment] 2016-10-23 18:14
simple test (Rc7):
![gvar22](https://cloud.githubusercontent.com/assets/20392683/19628392/162569b8-995d-11e6-921a-68bdeedbf69e.jpg)

under 2.18 this config will increment GV9 every time switch SH is pushed by value "1"

otx 2.2 RC7:
this config will increment GV9 every time switch SG is pushed, directly from "0" to value "1010" !
The options "no repeat" etc doesn't affect the result

**Comment by kilrah** [comment] 2016-10-23 18:17
Try it on the radio itself, not in the simulator

**Comment by tomkfly** [comment] 2016-10-23 18:25
When I tried it on the radio the GVAR increment end by 10 instead of 1.

**Comment by projectkk2glider** [comment] 2016-10-23 18:35
I will re-test this now.

**Comment by projectkk2glider** [comment] 2016-10-23 18:42
Taranis `simu` is OK.
Taranis Compaion radio simulator is OK (btw Companion model editor is actually broken, the enable option is missing for the GVAR INC/DEC SF)
Horus radio is OK.

I can't reproduce.

**Comment by strgaltdel** [comment] 2016-10-23 18:43
i made my tests on an existing model with following "history":
oTx 2.18 >>RC6 >>RC7
here the GV functionality seems totally "messed up", every GV shows deifferent, but "fixed" values....
BUT
When i build a new model the same SF-line settings are working well

**Comment by projectkk2glider** [comment] 2016-10-23 18:44
Wait, I have something....

**Comment by projectkk2glider** [comment] 2016-10-23 18:50
Companion is the only broken thing here, it seems it injects a repeat parameter somehow. The thing actually works OK on the radio. On my system the GVAR is incremented every second while the switch is true.

@strgaltdel plese repeat the test with a new empty model programmed on the radio.

**Comment by strgaltdel** [comment] 2016-10-23 19:07
yepp,
as i wrote before, by using an empty model all is working fine
i will do some more researches why the "transformed" models are not working as expected, 

thanks !

**Comment by projectkk2glider** [comment] 2016-10-23 19:12
Damn, this is strange, can't even reproduce it now in Companion. 

Looks like the bug is originating from e8aaa674505946a5b1009b47c7ddccdf9c5457a7 were the GVAR INC has *repeat and enable* parameters in Companion, while this combination is not implemented on the radio. Additionally the GVAR INC can't have a repeat parameter because of `HAS_REPEAT_PARAM(func)` and `HAS_ENABLE_PARAM(func)` macros.

So to fix this we have two options:
 * drop the broken repeat support for GVARS SF (my preferred solution)
 * or implement it fully

@bsongis and @kilrah please advise.

**Comment by kilrah** [comment] 2016-10-23 19:24
Agree on dropping repeat, that was never intended in the first place and most likely a bug.

**Comment by projectkk2glider** [comment] 2016-10-23 19:31
Actually this merge commit cbec010f44adf078ef8c7694d9d398737d670dc3 wiped out the HAS_REPEAT_PARAM(func) and HAS_ENABLE_PARAM(func) macros.

**Comment by projectkk2glider** [comment] 2016-10-23 19:48
So it looks like @bsongis moved GVAR SF to repeat. This is also strongly related to #3770.

**Comment by projectkk2glider** [comment] 2016-10-26 17:24
I believe that @bsongis idea was good, so I will try to re-implement it (hopefully without the bugs).

**Closed** 2016-10-27 18:34 UTC
Labels: Bug, Radio Firmware
