### ISSUE TITLE
companion update failed win 10

### ISSUE THREAD

**Issue by normtx16s** [opentx/opentx#9019] opened 2023-07-24 14:50 UTC
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

**Comment by JFingerle** [comment] 2023-09-06 08:23
Please close this nonsense issue. Thank you!

**Closed as completed** 2023-09-06 08:24 UTC

**Comment by normtx16s** [comment] 2023-09-06 19:44
An issue is only nonsense to someone who knows all the answers!
Thanks for all your help...
...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JFingerle** [comment] 2023-09-06 20:55
@normtx16s In this case the issue description is a placeholder text, thus the issue is nonsense to me. In case your original text was edited by someone else I apologize. Have a good one!
