### ISSUE TITLE
S3 on Taranis X9D+ does not calibrate correctly & disappears from hardware config

### ISSUE THREAD

**Issue by adengle** [opentx/opentx#5104] opened 2017-07-22 17:18 UTC
OpenTX 2.2.0
Reproduced on two radios: Taranis X9D+ & Taranis X9D+ Special Edition
Both radios have 6-position switch installed, configured as "Multipos Switch" for S3

While attempting to calibrate, the bar graph is very jumpy and inconsistent. [See example video here](https://youtu.be/t2NsXLB3wjE).

Sometimes, after usage or calibration, S3 disappears entirely from the hardware configuration. Suspect ADC scaling incorrectly. CORRECTION: S3 disappears during calibration when values are too erratic, as Andre notes below.

Verified voltage across switch (Vcc - Gnd): 3.00v
Verified voltages present on the switch in various positions (Flap - Gnd):
1: 0.000v
2: 0.595v
3: 0.745v
4: 0.998v
5: 1.490v
6: 2.998v

**Comment by kilrah** [comment] 2017-07-22 21:56
Video looks as expected.
Disappearing during calib is possible if more than 6 positions are sensed due to a bouncy switch, set back to multipos and try again. No reason it would disappear under normal use though.

**Comment by adengle** [comment] 2017-07-22 22:31
Thanks for looking at this!

It must be the bouncy switch…although I rolled one of the radios back to 2.1.9 and it seems to be more tolerant. Despite being bouncy input, it seems to cleanly recognize the six separate positions on 2.1.9.

Did something change with S3 reading or calibration? Debouncing?

**Comment by hrenz** [comment] 2017-07-23 07:21
Same Problem with S3 at X9DPlus, 
6 Pos switch mounted 1 Year ago, works fine under all openTx V2.1xx
got S31, S32, S33, S34, S35, S36
got -100, -60 -20 +20 +60 +100

But now under V2.2,0 final Version, nothing correct, it disapear in the hardware-setting
No S31 to S32
No  analog steps

At a X9E (I have one too) with V2.19 it works perfect as F3

--

**Comment by hrenz** [comment] 2017-07-23 08:12
Not one problem at calibrating the S3 / F3 with V2.19 at X9D+ and at X9E
calibrating works perfect
more tollerant, more Hysteresis, more time for detecting the 6Pos Switch at older openTx-Versions?

**Comment by projectkk2glider** [comment] 2017-07-24 17:44
I wonder why this is apparently working on the Horus and not on Taranis. I remember I did some refactoring around analog sampling and jitter filter and calibration code (this looks suspicious https://github.com/opentx/opentx/pull/3327/files#diff-38f78c082c0646df0f5cd9d302b7360dR83 :stuck_out_tongue: ).

**Comment by adengle** [comment] 2017-07-24 18:20
Honest suspicion (or crazy guess): Perhaps the 6-position switches sold for taranis are lower quality and exhibit far more bounce than those on Horus? Perhaps older routine was more tolerant?

**Comment by stanislavdavid** [comment] 2017-08-18 16:36
I bought 6-position swtich from authorized reseller of frsky - rcstudio.cz and I do not think they have lower quality. It is the only service center for X9D+and I have the same issue

**Comment by schwabe** [comment] 2017-08-18 16:37
@stanislavdavid we are talking about orgina frsky ones, they are not well designed.

**Comment by Stylusboy** [comment] 2017-08-21 20:41
I've recently experienced the same 6-pos calibration failure. I installed the 6-pos switch option right after I acquired my Taranis a few years ago. Back then, OpenTx allowed effortless calibration of this switch. I've updated the firmware a few times (current firmware revision - 2.2.0 N359) and during these updates, I've never attempted to re-calibrate the sticks/pots/switches until last week.

I have numerous multi-rotor models setup on the Taranis and all use the 6-position flight mode switch. Following my attempt to re-calibrate the sticks/pots/switches last week, ALL of the setups ceased to work, due to the flight controller getting bad information (i.e. bad or wrong flight modes, etc.) and not arming.

I ran across this GitHub thread started by CavRecon and his experience was identical to mine. Kilrah's response got me thinking about the problem. Upon connecting the Taranis to 6-pos switch/resistor divider "wiper", I was able to easily see rapid and multiple switch bounces when moving to each of the flight modes. Although projectkk2glider's comment pointed to corresponding code, I wondered if the sampling rate or moving average filter rates had changed. I hung a small bit of capacitance between the "wiper" output and ground. The rapid switch bounce spikes smoothed out and without downgrading to earlier firmware revisions, the 6-pos switch then calibrated without issue and ALL of the tried and tested model setups returned to full functionality.  I will admit that I liked the earlier display of S3's position during calibration where an integer corresponding to the switch position was displayed under the S3 vertical bar. 

Surely a better quality multi-position switches could be sourced, but before the software/firmware changes, my 6-pos switch worked flawlessly. I decided to install a single SMT capacitor (size 0805) with a value of 0.1uF. This size of capacitor can be added either on the 6-pos switch carrier PCB or on the S3 input solder pads and the problem is immediately solved. Even if the sampling rates are returned to their earlier values, the capacitor won't affect such a change. I hope this helps.

Tom

![cap_on_carrier](https://user-images.githubusercontent.com/31198537/29536994-336beac0-867d-11e7-858f-cb821f3acb79.jpg)
![cap_on_pcb](https://user-images.githubusercontent.com/31198537/29536993-3369aca6-867d-11e7-9c09-90c1df2a4850.jpg)

**Comment by Fraggs** [comment] 2017-12-05 06:51
After updating my Taranis Plus to Opentx2.2 I also had the problem of the 6pos switch not calibrating (connected toS2) after lots of messing about I finally got it to calibrate 
While it isnt exactly a great solution by slowly (very slowly) turning/switching through all the positions I did like I said get it to calibrate, several times it missed the last position and the transmitter slider graphic showed full one position to soon, but eventually I got it to calibrate correctly, I dont know if I was just lucky or its because its a newish switch thats not had much use.(genuine frsky)
I might look into the capacitor mod stylusboy mentions if no other solutions are going to be available as it was a pain to get it to calibrate

**Comment by mpjf01** [comment] 2017-12-05 10:01
It seems to work as before on my X9D. Is the value of the play delay relevant during the calibration process - or at all these days?

**Comment by Pix4hawk** [comment] 2018-04-06 22:33
same Problem with my X9e ..... thinking is clear ..... replace the switch..... nothing change..... 8-(
## **Thank you Tom !**
I use a "normal" size 0.1uF 

Mike

**Comment by david-ng-hk** [comment] 2018-08-22 11:42
I am on 2.2.2, can not calibrate, try many times already,
what is going one?
it was ok, why why why...

**Comment by bsongis** [comment] 2019-09-10 11:39
Cannot reproduce in 2.3

**Closed as completed by bsongis** 2019-09-10 11:39 UTC
Labels: Bug, Radio Firmware

**Comment by fiechr** [comment] 2020-01-03 13:24
I've just installed a 6-pos switch and having the same issue: The switch disappears after calibration.

Will try adding a 100 nF capacitor between S and GND, like mentioned above.

![6-pos-switch](https://user-images.githubusercontent.com/12040376/71725390-02e59980-2e34-11ea-902f-4117606e21a4.jpg)

**Comment by fiechr** [comment] 2020-01-03 18:20
Added a 100 nF capacitor at the other side of the PCB - calibration worked at first try. Thank you for the tip!

**Comment by zedthirteen** [comment] 2020-11-24 15:10
@Pix4hawk Capacitor modification on switch worked for me. Thanks Tom :-)
