### ISSUE TITLE
Special Functions reset the Xlite Pro

### ISSUE THREAD

**Issue by Talha909** [opentx/opentx#6735] opened 2019-09-10 16:16 UTC
**Describe the bug**
When I try to add special function for the RSSI play out.  My Xlite Pro resets itself. And give error of  No sound on Sd card. After that I switch off the the xlite pro and try to add function again the sound files appears but when i select the file then again xlite pro turn on and off.  And after reset there is some line break shows on the right upper side. 

**To Reproduce**
1. Go to Special Functions
2. Click on Play Track
3. Scroll down to Try to select the voice file
4. See  System reset and next gave error No sound on Sd

**Expected behavior**
Play sound of the rssi
**Screenshots**

**General information**
 - OpenTX version (e.g. 2.3 or N84)
 - Hardware (e.g. Frsky xlite pro)
 - OpenTX Companion (e.g. 2.3 on windows 10
![5d8117f4-3829-4cd2-937f-533a810d2d59](https://user-images.githubusercontent.com/29024390/64631290-3b3e1380-d410-11e9-8176-b8fe4f4607ab.jpg)
![31a04faa-59c4-43d4-8b42-9017d997503b](https://user-images.githubusercontent.com/29024390/64631291-3b3e1380-d410-11e9-8c55-d62269b13fec.jpg)
![aad68f4d-d6ad-449c-b107-74cda1c7c40e](https://user-images.githubusercontent.com/29024390/64631292-3bd6aa00-d410-11e9-9dec-15cca294cfeb.jpg)
![f8003361-3c13-4088-b7a1-683ddbd3cbc0](https://user-images.githubusercontent.com/29024390/64631294-3bd6aa00-d410-11e9-9470-73af06bcc7d5.jpg)

)

**Comment by 3djc** [comment] 2019-09-10 16:19
Please post the content of your sound directory as a zip so we can try to reproduce. Have you tried just with our SD card pack or are you using externa content ?

Also have you tried with another sd card ? I can't seem to be able to duplicate that

**Comment by bsongis** [comment] 2019-09-10 16:36
Duplicate of #6730 (scrolling issue)

**Closed as completed by bsongis** 2019-09-10 16:36 UTC
