### ISSUE TITLE
Random change of GV9 value

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#7521] opened 2020-04-14 10:34 UTC
Horus X10S Expres -- Opentx 2.3.7 -- EU/LBT.

Since I bought my Horus X10S radio, and installed OpenTx in the first version that supported it, until today I have version 2.3.7 in the models that use all the local variables GV1-GV9, sporadically, today It has been configuring the telemetry screens but other times doing other things, it only changes the "GV9 flight mode 0 value" to 1%, normally I have 80% and it is the dual rate of the ailerons, I hope that it will never happen. do in flight.

In one of the models that used GV1-GV9 I stopped using GV9 and it never gave any more problems, in another I still use GV1-GV9 and the problem persists, I see it every 10-15 times I use the model.

It gives the impression as if the memory size of the GV`s was not well dimensioned or not.

**Comment by kilrah** [comment] 2020-04-14 11:33
Can you supply a model where the issue is reproducible?

**Comment by afdofdez** [comment] 2020-04-14 11:44
Cheers

 

 

De: Andre Bernet <notifications@github.com> 
Enviado el: martes, 14 de abril de 2020 13:33
Para: opentx/opentx <opentx@noreply.github.com>
CC: Fernando Fernández <a.fernando.fernandez@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [opentx/opentx] Random change of GV9 value (#7521)

 

Can you supply a model where the issue is reproducible?

**Comment by kilrah** [comment] 2020-04-14 12:10
If there was supposed to be an attachment, github doesn't take email attachments.

**Comment by afdofdez** [comment] 2020-04-14 12:19
Modelo Heron.otx     https://drive.google.com/drive/u/0/my-drive

 

 

De: Andre Bernet <notifications@github.com> 
Enviado el: martes, 14 de abril de 2020 14:11
Para: opentx/opentx <opentx@noreply.github.com>
CC: Fernando Fernández <a.fernando.fernandez@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [opentx/opentx] Random change of GV9 value (#7521)

 

If there was supposed to be an attachment, github doesn't take email attachments.

**Comment by kilrah** [comment] 2020-04-14 16:39
Wrong link.

**Comment by afdofdez** [comment] 2020-04-14 16:43
https://drive.google.com/open?id=1KajJosMmUXWc5g1HYGe1vO2_vWKAQZ7t

 

Sorry

 

De: Andre Bernet <notifications@github.com> 
Enviado el: martes, 14 de abril de 2020 18:40
Para: opentx/opentx <opentx@noreply.github.com>
CC: Fernando Fernández <a.fernando.fernandez@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [opentx/opentx] Random change of GV9 value (#7521)

 

Wrong link.

**Comment by robustini** [comment] 2020-05-24 14:40
I can confimr the bug.
I had models that used GV9 and the first value I had set it to 88, now it is 1.
Reproducing the bug is simple, just change that first value from tx, exit and re-enter the page, go back to 1.

**Comment by robustini** [comment] 2020-05-24 14:41
I can confirm the bug.
I had models that used GV9 and the first value I had set it to 88, now it is 1.
Reproducing the bug is simple, just change that first value from tx, exit and re-enter the page, go back to 1.
Here only change the first value of GV9, not the others.

**Comment by robustini** [comment] 2020-05-24 15:22
A video showing the bug:

https://youtu.be/-0c10dJ24lw

**Comment by 3djc** [comment] 2020-05-24 15:29
Can’t reproduce here with tx16s, does the same happen on a empty model without yapuu and all ?

**Comment by afdofdez** [comment] 2020-05-24 15:44
I found the video of the GV9 failure very interesting where it is observed that the model has Yapu telemetry.
I also have the Yapu telemetry installed on another model, not the one that uses the variables GV1 to GV9.
I wonder, is it not an error of the yapu telemetry, which overwrites the GV9 value of some model to 1?

**Comment by kilrah** [comment] 2020-05-24 16:55
A script cannot touch anything but the current model.

**Comment by robustini** [comment] 2020-05-24 17:12
Don't ask me why but I just created a copy of that model by removing the Yaapu and that variable now doesn't change it.
I try to investigate with Alessandro Santilli, the author of Yaapu if there can be a relationship.

**Comment by StefanKellerAC** [comment] 2020-05-25 11:11
I can confirm it: 
The yaapu mapping widget uses GV9 FM0 and FM7

**Comment by 3djc** [comment] 2020-05-25 11:16
So nothing wrong with OpenTX then, right ?

**Comment by robustini** [comment] 2020-05-25 11:36
Yes, nothing wrong with OpenTX.

**Comment by 3djc** [comment] 2020-05-25 11:36
Ok, closing this then.

**Closed as completed by 3djc** 2020-05-25 11:36 UTC
