### ISSUE TITLE
Simulating Multiposition Switch with Flight Modes does not work

### ISSUE THREAD

**Issue by bitogre** [opentx/opentx#3607] opened 2016-06-18 02:53 UTC
Set up a radio with a multi-position switch (in "General Settting" under "Hardware" tab) and assign that switch to different flight mode.  For example S2 is the Multi-position switch and FM1 is on S22, FM2 on S23, ... assigning all positions except S21 (could assign S21 as well but we would never get to default).  Now simulate the radio and change the given knob.  

Expect: As you change the know, the flight modes should change accordingly.
Actual: It will remain in a given Flight mode (I have got different starting results depending on which S knob I made the multi position but stay in whatever it was when simulation started).

**Comment by projectkk2glider** [comment] 2016-06-18 07:18
Duplicate of #2377

**Closed by projectkk2glider** 2016-06-18 07:18 UTC
