### ISSUE TITLE
OpenTx support for Multi-Protocol Modules on 9X (TGY or other Standard)

### ISSUE THREAD

**Issue by xtremet1** [opentx/opentx#5681] opened 2018-02-10 19:57 UTC
On many Radio's OpenTX supports at their Build Options - The Multi-Protocol Modules

On the 9X (TGY / Standard) there appears to be no support, thus not enabling Serial Mode
To control the module easily / enjoy the already written code and implementation available on other Radios (at OpenTX)

If possible please integrate the Multi-Protocol Modules - on the TGY 9X enabling Serial Mode with  OpenTX & Companion SW

1) Please Add a Multi-Module (Multi Protocol Module) option "checkbox" on the 9X build options at the Companion SW
2) I think the 9X is able to support Serial Mode (if you do the right conversions freeing the MOSI, MISO pins and making a route for one of them to pin 5 (for Telemetry)) - equivalent to "FrSky" CheckBox at the companion SW 
3) Probably if some code is missing this code may be could be ported from the er9x Firmware supporting both Serial & Telemetry (so it seems possible HW wise & SW wise)
4) Please if possible integrate with the description on the Transmitters page of the Multi-Modules : https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Tx-FlyskyTH9X.md   - to further support OpenTX Multi-Module

This help will be very efficient to many having the 9X, and making it even better

**Comment by 3djc** [comment] 2018-02-10 21:35
This is a duplicate of #3812. I think @schwabe commented somewhere that he as no plan to implement it for AVR.

**Closed by 3djc** 2018-02-10 21:35 UTC
