### ISSUE TITLE
X9E simulator missing F1/F2

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#2642] opened 2015-08-05 06:33 UTC
Hi,

just noticed while testing out some bits in the simulator that for the X9E the F1/F2 are missing. Are there also any planning on F3/F4 and the by default unused SI-SR switches to be integrated?

**Comment by projectkk2glider** [comment] 2015-08-05 07:01
Duplicate of #2377

**Closed by projectkk2glider** 2015-08-05 07:01 UTC
