### ISSUE TITLE
Duplication of receiver number when copying a model

### ISSUE THREAD

**Issue by Comdoc292** [opentx/opentx#2935] opened 2015-09-28 03:55 UTC
Had a situation where I left a battery connect in a model I had copied in my Taranis, result was one plane took off and one in the pits ran into a fence, air born plane crashed as lost sight of it. There needs to be a warning that copying a model also copies the receiver number. If 2 receivers have the same number and both are powered, they will both respond. If you try to manually change a receiver number the software rightly will not allow this to happen, but no restriction if copying a model

**Comment by kilrah** [comment] 2015-09-28 12:27
Duplicate of #2187

**Closed by kilrah** 2015-09-28 12:27 UTC

**Comment by griebd** [comment] 2015-09-28 13:10
just as a clarification, which firmware do you have in your radio @Comdoc292?

**Comment by Comdoc292** [comment] 2015-09-29 00:08
I have a Taranis Plus 2.0.17

  _____

**Comment by griebd** [comment] 2015-09-29 00:39
OK then, I just wanted to be sure there was no unseen bug in 2.1... For 2.0.17 there is already a fix, issue #2187. It will be available in 2.0.18.
