### ISSUE TITLE
Close Window Keyboard Shortcut Wrong on Mac

### ISSUE THREAD

**Issue by xtrmtrk** [opentx/opentx#5064] opened 2017-06-27 02:01 UTC
In the the Mac version of Companion 2.2, Command-W should close an open window when editing a model, not Escape.  For those of us used to the Mac conventions, this switch is frustrating.

**Comment by projectkk2glider** [comment] 2017-07-24 14:45
Just a reminder: when fixing this first check if perhaps the issue is caused by the Qt library.

**Comment by projectkk2glider** [comment] 2017-07-24 14:46
@xtrmtrk did you had the same problem in previous versions - ie 2.1?

**Comment by xtrmtrk** [comment] 2017-07-24 16:55
Yes, there's been the same behavior for as long as I can remember (I'm patient, or lazy - the frustration took years to build for me before I submitted a bug!).

What's kind of odd is that Command-W works correctly for a file window - the window that lists all of the models.  But it does not work when trying to close individual model windows or simulator windows.

**Comment by raphaelcoeffic** [comment] 2018-05-07 07:02
@xtrmtrk that's probably because the "open windows" are considered dialog boxes, which are not closed by Cmd-W either on Mac.

**Closed as completed** 2019-08-14 08:27 UTC
Labels: Bug, Companion
