### ISSUE TITLE
LUA insertInput missing many options

### ISSUE THREAD

**Issue by u8mydog** [opentx/opentx#3058] opened 2015-11-12 03:32 UTC
I wrote/modified a lua wizard for helicopters using 2.1.6 and insertInput() is missing many options. I've always been under the opinion that it is better to do curves, expo and dual rates on the input and before the mix. This makes it easier to use CYCx and removes possible interactions in the mixes. I see that insertMix() supports the extra options.

Please make the following options available to insertInput():
inputName (vs line name)
curveType
curveValue
flightModes
carryTrim
 And some documentation to tell me how to set weight, offset and/or curve to use GV.

**Comment by kilrah** [comment] 2015-11-12 05:31
Duplicate of #1647

**Comment by u8mydog** [comment] 2015-11-13 00:47
I don't think it is a dup. #1647 covers insertMix(). And insertMix() is looking pretty good. insertMix() provides access curveType/value, flightmodes, etc.

But I'm asking for access to these parameters for insertInput().

I'm trying to put together an environment to compile opentx & companion. I'm a bit more of a hack but I could probably make the changes by using insertMix() as a guide.

**Comment by kilrah** [comment] 2015-11-13 06:37
Well it's related, #1647 is basically a blanket issue to add lots of useful things to the lua API... Whenever it's completed both the mixer and inputs should be taken care of. You can jsut add a comment on the other one.

**Closed by kilrah** 2015-11-13 06:37 UTC
