### ISSUE TITLE
Hello.wav stutters on Horus is now warnings are present

### ISSUE THREAD

**Issue by JanneMantyharju** [opentx/opentx#5246] opened 2017-09-27 19:13 UTC
When starting up Horus on 2.2.0, the default (english) hello.wav stutters on startup. Surprisingly if there are warnings like switch warning, hello.wav plays without problems, followed by warning sound also without any stuttering.
Maybe the tx is doing something processor intensive initialization while playing the hello and is not so busy if warnings are present.

**Comment by projectkk2glider** [comment] 2017-09-28 16:26
Duplicate of https://github.com/opentx/opentx/issues/3815#issuecomment-255988284

**Closed as completed by projectkk2glider** 2017-09-28 16:26 UTC
