### ISSUE TITLE
Companion 2.1.8 serial port -- type "FrSky D (cable)" NOT showing

### ISSUE THREAD

**Issue by nostromo123** [opentx/opentx#3582] opened 2016-06-09 17:04 UTC
Hi, I am missing FrSky D (cable) in companion.

see attached screenshot. Only two items available.
On my Taranis, I have option FrSky D (cable)
br
![screenshot 9](https://cloud.githubusercontent.com/assets/17964433/15938724/ae57b190-2e74-11e6-93e4-16fe0249b7ce.jpg)

**Comment by projectkk2glider** [comment] 2016-06-09 17:23
Duplicate of #3372 (which you reported :wink:), fix will be in 2.1.9

**Closed by projectkk2glider** 2016-06-09 17:23 UTC
