### ISSUE TITLE
2.1.7 S3 as 6poz switch should have separate steps in Compaion 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#3259] opened 2016-01-28 16:52 UTC
If on X9D are in HW S3 6 poz switch there should be S3 as stepper in Cmpanion fer clearer simulation
![image](https://cloud.githubusercontent.com/assets/2682800/12651695/e8dce470-c5e7-11e5-89bc-ea4f4a8891a0.png)

As well the free wheel of S3 not change FM if are FM selected like S31-36 well 

Please look at video 

http://www.youtube.com/watch?v=V33OOJy7WOE

**Comment by projectkk2glider** [comment] 2016-01-28 18:06
Known issue, duplicate of #2377

**Closed** 2016-01-28 18:06 UTC

**Comment by janekx** [comment] 2016-01-28 18:11
Ok i search for S3 so not found it
