### ISSUE TITLE
Companion v2.0.16 May 3 2015 crashing

### ISSUE THREAD

**Issue by ljt2000** [opentx/opentx#2254] opened 2015-05-03 15:54 UTC
Hello,

I use the latest version release date. I had a crash when I use the simulation:
Crash when using the latest version on Windows 8.
I put the Windows 7 compatibility mode and it crashed.
I have set the mode of compatibiltié in Windows XP and there, no crash.

Thanks,

LJT2000
![capture-companion](https://cloud.githubusercontent.com/assets/12222170/7445674/4d84f700-f1bd-11e4-8d20-b7ef68245ce6.PNG)

**Comment by projectkk2glider** [comment] 2015-05-03 16:28
Duplicate of #2253

**Closed by projectkk2glider** 2015-05-03 16:28 UTC
