### ISSUE TITLE
Ratio at Telemetry Sensor  the Range is to small

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2723] opened 2015-08-17 04:54 UTC
Hy,
for Multiply or Divide the Sensorvalue the Ratio range should be from 100 to 0,01
now its only ?1000?  to 0,1
have an  Alt sensor with cm vlaue,  need to multiply with  0,01

**Comment by kilrah** [comment] 2015-08-17 07:22
Duplicate of https://github.com/opentx/opentx/issues/2615

But in your case you probably want to change the sensor's Precision.

**Closed by kilrah** 2015-08-17 07:22 UTC

**Comment by hrenz** [comment] 2015-08-17 07:37
Hy,

I got from Sensor 12345cm  for an Alt of 123,45m 
so Multiply (Divide)  at Ratio schould be  0,01
to get Value in correct Meters

**Comment by kilrah** [comment] 2015-08-17 07:41
Just choose precision=2.
