### ISSUE TITLE
Random changes of offsets and switch positions Horus

### ISSUE THREAD

**Issue by marcogpw** [opentx/opentx#4340] opened 2017-01-30 06:58 UTC
Have observed that writing a models file from PC based computer running OpenTX 2.2.0 RC9 and RC10 to the Horus (on RC10 as well) randomly changed the inputs offset settings ranging from 2 to 49 %. Also the positions of the switch warning panel changed randomly, resulting in lots of switch warnings when powering on the Horus adn when switching models. Don't know yet if these changes happen at transfer to the Horus, during saving or maybe writing it twice in a row, since there is no transfer progress monitor for writing the models file to the transmitter.

**Comment by projectkk2glider** [comment] 2017-01-30 08:02
This should be fixed in R10 by https://github.com/opentx/opentx/pull/4331. Are you sure it sill happens in RC10?

**Comment by projectkk2glider** [comment] 2017-01-30 08:30
I can't reproduce with RC10.

**Comment by marcogpw** [comment] 2017-01-30 08:33
I will get my transmitter and test with RC10, standby for updates, thank you for looking into it though !

**Comment by marcogpw** [comment] 2017-01-30 09:00
You are completely correct, no more random offsets and switch positions anymore. I tried everything, reading/writing and doing things you would normally not do:reading from Horus and writing 4 time in a row ... sorry for the complaining

**Closed** 2017-01-30 09:06 UTC
Labels: Bug, Companion, Needs more data
