### ISSUE TITLE
Timerdisplay on Telemetry-page on 2.2.1 for X9D+ corrupt

### ISSUE THREAD

**Issue by hmichl** [opentx/opentx#5626] opened 2018-01-14 12:47 UTC
Hi,
I just upgraded to Open-TX 2.2.1 (German Version) and am using X9D and X9D+ transmitters. On my transmitters, as well as on the simulator I get a corrupted display of timers in the top-line.
In the past there was "Tmr1" and "Tmr2" regardless if I defined a name for the timers or not. But now with 2.2.1 it tries to write-down the name in the telemetry page, and there is not enough space. So I cannot see the timer.
I add a screenshot of the simulator, on the transmitter it is the same.
![screenshot_x9d timer-display-problem](https://user-images.githubusercontent.com/17198370/34916059-78e5c950-f931-11e7-80ca-153e637359f8.png)

Can anybody help?

Thanks,
Harald

**Comment by 3djc** [comment] 2018-01-14 13:25
Duplicate of already fixed  #5467

**Closed as completed by 3djc** 2018-01-14 13:25 UTC
