### ISSUE TITLE
io.open(file,"r") crashes companion on filenames starting with a dot instead of returning nil

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3343] opened 2016-03-09 05:08 UTC
Io.open('/directory/.lua','a') crashes companion.

So when constructing filenames to load from file="somefile" and io.open("/directory/" .. file .. ".lua"," a")
Make sure file is not "".

**Comment by projectkk2glider** [comment] 2016-03-09 13:18
Most likely related to #3342

**Comment by projectkk2glider** [comment] 2016-03-09 13:18
Do you know if it works on a radio?

**Comment by bsongis** [comment] 2016-03-11 17:07
Duplicate of #3342

**Closed by bsongis** 2016-03-11 17:07 UTC
Labels: Bug, Companion, Lua
