### ISSUE TITLE
VFAS-40 sensor with a D4R-II receiver not create in Taranis correctly

### ISSUE THREAD

**Issue by bitogre** [opentx/opentx#2629] opened 2015-08-04 01:49 UTC
I use a VFAS-40 sensor with a D4R-II receiver.  It was easy to set up and get this sensor to work with my Taranis on OpenTX 2.0.x but with OpenTX 2.1.0, the Taranis was not able to properly set up this sensor correctly.  The voltage sensor was added as name "003B" with a Precision 0, Range 0.0, and Offset 0.  With these settings, my radio reports a battery with 12.5V as having a voltage of only 4V.

**Comment by projectkk2glider** [comment] 2015-08-04 06:03
Already fixed in 2.1.1, duplicate of #2518

**Closed by projectkk2glider** 2015-08-04 06:03 UTC
