### ISSUE TITLE
Telemetry Simulator does not work anymore

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#6869] opened 2019-09-30 14:51 UTC
after updating to 2.3.0 companion and horus x10
1. Button click: read models and settings from radio
2. Button click: Simulate Radio
3. Button click: Telemtry Simulator
Checkbox  "Simulate" is activ, some values are filled e.g. RxBt
The Telemtry widget in Horus Simulator shows only "0"  e.g. RxBt

Telemtry in Horus X10 is fine

The same procedure in 2.2.4 works fine

**Comment by ParkerEde** [comment] 2019-09-30 14:58
![otx telemtry simulator](https://user-images.githubusercontent.com/15068446/65890621-75f9f280-e3a3-11e9-8d67-b56604558d9f.jpg)

**Comment by kilrah** [comment] 2019-09-30 17:21
Duplicate of #6862

**Closed as completed by kilrah** 2019-09-30 17:21 UTC
