### ISSUE TITLE
Companion 2.1.1 on Mac OS X crashes on start

### ISSUE THREAD

**Issue by mars-wolf** [opentx/opentx#2677] opened 2015-08-09 08:07 UTC
This happens:

Process:               companion [902]
Path:                  /Applications/companion.app/Contents/MacOS/companion
Identifier:            companion
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           companion [902]
User ID:               501

Date/Time:             2015-08-09 10:04:13.223 +0200
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        72EF10E8-7CC5-2563-18C3-EE1B441B03C8

Time Awake Since Boot: 220 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/SDL.framework/Versions/A/SDL
  Referenced from: /Applications/companion.app/Contents/MacOS/companion
  Reason: image not found

Binary Images:
    0x7fff683a6000 -     0x7fff683dc837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld
    0x7fff8fae8000 -     0x7fff8fae9ff3  libSystem.B.dylib (1213) <AD223AEB-237D-35A3-825E-EECF95916838> /usr/lib/libSystem.B.dylib

Model: MacBookPro11,1, BootROM MBP111.0138.B15, 2 processors, Intel Core i5, 2.6 GHz, 16 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.5f8 15969, 3 services, 27 devices, 1 incoming serial ports
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

**Comment by kilrah** [comment] 2015-08-09 08:11
Duplicate of #2667

**Closed by kilrah** 2015-08-09 08:11 UTC
