### ISSUE TITLE
Trainer mode not work 2.1.4N465 X9E

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2913] opened 2015-09-21 13:15 UTC
1. X9E with 2.1.3 stable slave / jack
2. X9E with 2.1.4N465 master / jack

using 3.5mm mono jack

1. new model slave / jack 1-8ch 22.5 300u -
2. new model master/ jack at main menu can not select calibration. the numbers at 0.0 0.0 0.0 0.0 right aside Cal. very quickly and hard to noticible shows signals from slave. To see -100 to 100 look like shows for 1/200sec only so disapear very quicky. 

When turn roles from radio 1 to 2 and vice versa it is same. 

If X9E is slave and T+ 2.0.17 master it works all well.

**Comment by bsongis** [comment] 2015-09-26 11:31
Tested this morning on my X9E prototype

- I have the trainer / trainee icon always present in the notification bar (hardware bug fixed on production radios)

- I have the trainer / trainee correctly detected (haptic bzzz)

- **As described above I have 0.0 in all numbers from the Trainer screen**

**Comment by bsongis** [comment] 2015-09-26 11:31
Does anyone has Trainer function correctly working on a production X9E?

**Comment by janekx** [comment] 2015-09-28 12:01
Here is my test, 2 production line X9E with 2.1.3, one first batch X9E with 2.1.4N465 and X9D+ with 2.0.17 
The firstbatch X9E not tell the connection of the trainer port, but production line X9E tells conection and disconnection. On X9E there is no icon of the connected trainer port. 


http://www.youtube.com/watch?v=m_W7bI_TSKQ

**Comment by arnaudmz** [comment] 2015-10-02 07:46
Issue confirmed here, the tests I ran:
  * master: X9D, slave: Spektrum D7 => **OK**
    * Icon appears on X9D **OK**
    * sounds do notify jack connection and disconnection **OK**
    * slave sticks move the servos **OK**
  * master: X9D, slave: X9E => **OK**
    * Icon appears on X9D **OK**
    * sounds do notify jack connection and disconnection **OK**
    * slave sticks move the servos **OK**
  * master: X9E, slave: X9D => **KO**
    * Icon won't appears on X9E **KO**
    * sounds do notify jack connection and disconnection **OK**
    * slave sticks won't move the servos **KO**
  * master: X9E, slave: Spektrum D7 => **KO**
    * Icon won't appears on X9E **KO**
    * sounds do notify jack connection and disconnection **OK**
    * slave sticks won't move the servos **KO**

Both X9D and X9E are running 2.1.3 OpenTX, My X9E might come from the second batch (recieved it just one week ago)

**Comment by hrenz** [comment] 2015-10-03 07:50
Hy,
same Trainer-Problem  

X9E first batch, openTx V2.1.4 N453
X9DPlus, one year old,  openTx V2.1.2 N417
Simple old 4K TX as slave/jacket,  PPM-Signal at Oszi tested, is ok, 4,5V 

Test with Mono and Stereo Kabel

X9E as slave/jacket, X9D as master/jacket,  is ok, all works fine, symbol only at X9D, not at X9E
X9E as master/jacket, X9D as slave/jacket,  not ok, nothing input at X9E no symbol at X9E
X9E as master/jacket, Simple old 4K TX as slave/jacket, not ok, nothing input atX9E no symbol at X9E

Huston we have a problem

**Comment by Eagle69** [comment] 2015-10-04 15:32
Hi

before I did the update of the software from FRSKY original to Open TX the master/slave function did worked, at least that's how I remeber it.
Is this easy to test again ?

**Comment by bsongis** [comment] 2015-10-04 17:32
@Eagle69 That's interesting, are you sure?

**Comment by Eagle69** [comment] 2015-10-05 04:47
@bsongis 
Pretty sure that I could read it on the TX before I changed the Software.
I think I saved FrSky original Sw so I should be able to reverse and try it.

**Comment by bsongis** [comment] 2015-10-05 05:09
Yes, thanks!

**Comment by Eagle69** [comment] 2015-10-05 16:01
Hi

I couldn't restore it but since it works the other way around it can't be Hw error.
Even if I connect a Spektrum Tx to X9E the Spektrum Tx lit up.
Or ??

**Comment by bsongis** [comment] 2015-10-05 17:05
Here we need @janekx I am almost sure he performed tests with the X9E stock firmware, am I right?

**Comment by janekx** [comment] 2015-10-05 17:07
Tested with opentx 2.1.3 and nightly,  never test with fw the FrSky load there.

**Comment by bsongis** [comment] 2015-10-05 17:11
Ok, I need the FrSky original firmware, I will ask Adela.

**Comment by janekx** [comment] 2015-10-05 17:13
They have holiday now.  Will be from 8.10 back in work.  I am possible to test it too...

**Comment by janekx** [comment] 2015-10-05 17:17
Officially they have only lattest available i think we need that older one http://www.frsky-rc.com/download/view.php?sort=Firmware&down=213&file=Firmware-%20Taranis%20X9E

**Comment by bsongis** [comment] 2015-10-05 17:22
@janekx Would you check it it's better with this firmware?

**Comment by janekx** [comment] 2015-10-05 17:26
Ok will try it tomorrow and will report,  but this FW was relased after my batch come to me. So can be fork of the newer opentx that "contain" bug.

**Comment by bsongis** [comment] 2015-10-05 18:10
Not sure, especially if it comes from a different compiler

**Comment by janekx** [comment] 2015-10-05 18:12
I see it is alternative too

**Comment by Murphy25** [comment] 2015-10-05 22:09
Bonjour,

Je viens de tester sur ma X9E non EU avec un câble jack mono.
- Moniteur : X9E non EU firmware 2.1.3
- Elève : Radio Protonik PTR-6A V2

J'ai aussi le problème alors que la double commande fonctionne bien avec ma X9D en 2.0.17.

Merci d'apporter une solution car je compte bien équiper ma X9E en double aussi avec un récepteur connecté en PPM comme sur ma X9D.

**Comment by GervaisPinot** [comment] 2015-10-06 15:39
Bonjour,

J'ai recu ma X9E, j'ai transféré tous mes modèles de la X9D et j'ai un problème avec l'écolage.

L'écolage  ne fonctionne plus. Quand je branche le Jack sur la prise arrière de la radio (la bonne, pas la prise caque....) je ne vois rien dans les signaux d'entrée dans l'écran de calibration de l'émeteur élève. Y a t'il una endroit ou on doit déclarer le mode élève autre part que dans le menu modèle ?
J'hésite entre un problème de soft et un problème de hard.

Est ce que qu'elqu'un a fait fonctionner le mode élève avec une X9E ?

Merci pour vos réponses.

**Comment by bsongis** [comment] 2015-10-06 15:54
Justement c'est l'objet de l'issue, on ne voit personne pour qui ça
fonctionne

**Comment by janekx** [comment] 2015-10-06 16:11
So I tested on production X9E the FW from FrSky DL page. 
Same issue.
It says trainer port connected, no icon, no signal on Trainer setup page. 
Same as before there is lightly see the numbers but only like shadows.

Firmware says 2.1.4 Eeprom 217 
2015-09-24

**Comment by Murphy25** [comment] 2015-10-06 17:09
Bonjour,

En tout cas ce n'est pas un problème de hard puisque dans le sens X9E élève > X9D moniteur ça fonctionne. Donc la prise est bonne.

**Comment by janekx** [comment] 2015-10-06 17:15
Please use English...  Thanks

**Comment by Murphy25** [comment] 2015-10-06 19:44
Sorry, Google my friend :)

**Comment by janekx** [comment] 2015-10-06 19:56
OK tak se tu muzeme zacit bavit cesky a bude ti to stejne k nicemu, protoze to google spatne prelozi. :)

**Comment by bsongis** [comment] 2015-10-06 20:52
He says something wrong. For the moment we can't say anything. PPM in and PPM out are on different PINS on the CPU.

**Comment by arnaudmz** [comment] 2015-10-07 05:58
Bertrand, is there any way we can be of any help investigating this?
I can backup everything and try any kind of debug/experimental firmware if you like.

Let us know.

**Comment by bsongis** [comment] 2015-10-07 17:02
My problem is simple. FrSky told me that they don't have this problem. I need them to double check, if they are right, it means they fixed an hardware problem. If wrong there is a bug in the software. But when you plug the trainer cable the fact is there are a lot of interrupts, it seems the PPM input is working, but only during ~50ms

**Comment by janekx** [comment] 2015-10-07 17:18
I got scope back,  i can do it but do not know where to check have no diagrams to look at.  
50ms looks like that ghost numbers rhat can be lightly seen

**Comment by bsongis** [comment] 2015-10-07 18:17
You will probe on either side of the cable!

**Comment by janekx** [comment] 2015-10-07 18:23
So i should check if the trainee send  the PPM correctly right?

**Comment by bsongis** [comment] 2015-10-07 18:44
In fact you will check if once the wire is connected your PPM stream remains OK. If the X9E grounds the PPM signal, then it is a problem ...

**Comment by janekx** [comment] 2015-10-07 18:48
I see the task...

**Comment by wollenagold** [comment] 2015-10-08 16:59
Hi guys
When I got my X9E 6 days ago I made a security of the original bin. whit which the TX was delivered to me.
Perhaps you need such an original bin.  tell me to what e-mail I can send to help you to fix the bug.
Because I need the opinion teachers-TX while I make the introduction of beginners in our club.
Wolfgang

**Comment by bsongis** [comment] 2015-10-08 17:10
@janekx already told here that the original firmware has the same problem

**Comment by janekx** [comment] 2015-10-09 08:11
As I can measure the pads on the PCB of DSC port there is already good signal on trainer from trainee.

**Comment by kilrah** [comment] 2015-10-09 08:32
Some on RCGroups however said the original FW was OK...

**Comment by janekx** [comment] 2015-10-09 08:45
will try to contact FrSky for that FW, older then we tested ....

**Comment by GervaisPinot** [comment] 2015-10-09 16:43
Hello,

I have checked again the trainer mode  with the initial firmawe delivered
with the TARANIS X9E
opentx-taranis-x9e-2.1.0
EEPR217

The trainer mode works fine., The same way it worked with my X9D

This confirm the firmware issue with the 2.1.3

Hope this helps the problem solving.

Let me know when you wish extra information.

Gervais


2015-10-09 10:45 GMT+02:00 Jan Urbánek <notifications@github.com>:

**Comment by arnaudmz** [comment] 2015-10-09 17:14
Sounds like good news to me.

**Comment by hrenz** [comment] 2015-10-09 17:27
Hy, 
could I get please the original Frsky file
for the TARANIS X9E opentx-taranis-x9e-2.1.0 EEPR217
for Testing too master slave

**Comment by janekx** [comment] 2015-10-09 17:33
I think there  is possible to save the fw to file and send it to us for test.

**Comment by GervaisPinot** [comment] 2015-10-09 18:25
Here is the initial firmware

gervais

2015-10-09 19:33 GMT+02:00 Jan Urbánek <notifications@github.com>:

**Comment by bsongis** [comment] 2015-10-09 20:38
@GervaisPinot Yes this is excellent news, would you send this firmware to my email address? bsongis (at) gmail (dot) com

**Comment by janekx** [comment] 2015-10-09 20:53
Me too please to info (@) rcstudio (.) cz

**Comment by janekx** [comment] 2015-10-10 06:55
OK I got from Adela their 2.1.0 FW and I tested it now, it works well, Adela told me that their tests work OK on 2.1.0 and on 2.1.3 have issue. 
So we have confirmation that need to be something corrected in OpenTX and not HW issue.

**Comment by bsongis** [comment] 2015-10-10 08:18
Ok. I will try to find which revision introduced this problem. It's indeed good news.

**Comment by projectkk2glider** [comment] 2015-10-10 15:05
The most suspect is commit f6bff9683dd3ad058c0a5aa16060f08b963cfad8. I bet the new PPM validity check is discarding input signal. 
```c
inline void captureTrainerPulses(uint16_t capture)
{
  static uint16_t lastCapt=0;
  static uint8_t channelNumber=0;

  uint16_t val = (uint16_t)(capture - lastCapt) / 2;
  lastCapt = capture;

  // We process ppmInput right here to make servo movement as smooth as possible
  //    while under trainee control
  //
  // G: Prioritize reset pulse. (Needed when less than 16 incoming pulses)
  //
  if (val>4000 && val<19000) {
    channelNumber = 1; // triggered
  }
  else {
    if ((channelNumber > 0) && (channelNumber <= NUM_TRAINER)) {
      if (val>800 && val<2200) {
        ppmInputValidityTimer = PPM_IN_VALID_TIMEOUT;
        ppmInput[channelNumber++ - 1] =
          //+-500 != 512, but close enough.
          (int16_t)(val - 1500)*(g_eeGeneral.PPM_Multiplier+10)/10; 
      }
      else {
        channelNumber = 0; // not triggered
      }
    }
  }
}
```

**Comment by projectkk2glider** [comment] 2015-10-10 17:16
Using `git bisect` I determined that commit 60f2535212b04d06202e679f11299c16298d03a3 broke this (remember only when **haptic** option is selected).
```
opentx $ git bisect log
# bad: [bb1d368c039ecf5208c0e0f119bcc12c88cef7c3] Merge pull request #2933 from hrenz/patch-11
# good: [6fe12ba6251ac05ed8f38548b487f91645ac0c75] Cosmetics
git bisect start 'bb1d368c039ecf5208c0e0f119bcc12c88cef7c3' '6fe12ba6251ac05ed8f38548b487f91645ac0c75'
# good: [1d6adcc25a34c8f02b6406b215f58e366ff1bd1a] Fixes #2870
git bisect good 1d6adcc25a34c8f02b6406b215f58e366ff1bd1a
# good: [3f6e1d0b3a36857371b67e31e57a4c8c5a6cba8d] Lua error display function reused
git bisect good 3f6e1d0b3a36857371b67e31e57a4c8c5a6cba8d
# bad: [7ec4f508eec571e8331d25c50fa2596ce099384d] Merge pull request #2930 from opentx/bsongis/issue1914_by_dsbeach
git bisect bad 7ec4f508eec571e8331d25c50fa2596ce099384d
# bad: [60f2535212b04d06202e679f11299c16298d03a3] Fixes #1914
git bisect bad 60f2535212b04d06202e679f11299c16298d03a3
# first bad commit: [60f2535212b04d06202e679f11299c16298d03a3] Fixes #1914
```

**Comment by bsongis** [comment] 2015-10-10 22:30
Yes it is the most suspect, but there is no difference in the validity check itself!

**Comment by bsongis** [comment] 2015-10-11 10:14
No luck, I have another problem on my X9E prototype, the PPM signal is grounded if the plug is in its place. I have to pull a little bit the cable to make it work (with the firmware I received by email (date: 15 july of 2015)

**Comment by janekx** [comment] 2015-10-11 10:18
It look more like the mechanical issue the jack is not right in place. I found that there the jack female on PCB no go thrue the case and can make this issue....

**Comment by bsongis** [comment] 2015-10-11 10:44
I have found

**Comment by bsongis** [comment] 2015-10-11 10:45
Don't be too hard with me when you see the commit please ...

**Comment by bsongis** [comment] 2015-10-11 10:55
I just forced a new nightly build. Please check if it's ok, but I am confident, it works here (except the mechanical issue)

**Comment by janekx** [comment] 2015-10-11 11:06
N485 and still no data, appears -1.6 0.2 0.2 1.0 but not change, trainer port cennected and disconnected it tells.

**Comment by janekx** [comment] 2015-10-11 11:13
N486 on production line work for me well. Thanks

**Comment by hrenz** [comment] 2015-10-11 11:57
Hy,
Now I have the N486 at X9E too  

X9E als Master/Jacket  and a X9DPlus as Slave/Jacket

first problem is/was  the jacket !! Yes there is a contact-problem!!

second  
master/ jacket as input now is ok, can see the values from trainer comming
haptik comes at putting the jacket in

but 
no symbol at X9E main screen,  shouldn´t there be a trainer symbol too, same symbol as at X9D
no speach if Trainer signal is going On or Off, sholdn´t it be a speach?

**Comment by janekx** [comment] 2015-10-11 12:15
Yes icon is not there but it tells that trainer port is connected or disconected.

**Comment by projectkk2glider** [comment] 2015-10-11 16:22
Looks like the LCD symbol and voice announcements are still not working.

**Comment by janekx** [comment] 2015-10-11 16:26
For me it tells well trainer conmected /disconnected,  only icon not appear in the upper bar.

**Comment by projectkk2glider** [comment] 2015-10-11 16:28
OK, then only the LCD symbol is missing. Should be easy to find why. 

@janekx if you look really hard (at different angles) do you see a hint of the trainer symbol or completely nothing?

**Comment by janekx** [comment] 2015-10-11 16:34
Nothing no sign of the icon,  no ghost icon as well

**Comment by kilrah** [comment] 2015-10-11 16:47
> no speach if Trainer signal is going On or Off, sholdn´t it be a speach?

Make sure you actually have the relevant voice files, they were not in the first pack versions.

**Comment by janekx** [comment] 2015-10-11 16:48
Have actual voice pack Martin make in Czech right for 2.1

**Comment by wollenagold** [comment] 2015-10-11 17:33
@hrenz 
1 hour before I had updated to 2.1 4 nightly 486.
So now the teacher mode is running.
Haptic connecting/disconnect works.
No connected symbol showing.
But there are problems with the jacket. Missing a mono-cable since April I have used a stereo-type without problems. Think the socket is not the the very best

**Comment by wollenagold** [comment] 2015-10-11 17:36
The stereo-type cable worked every time well

**Comment by projectkk2glider** [comment] 2015-10-11 18:21
@janekx Does the trainer icon show if the X9E is slave? If not then we have a hardware problem, because the symbol on/off is directly controlled by the state of PA8 pin.

**Comment by janekx** [comment] 2015-10-11 18:28
I dont think so,  the trainer tell connected when i unplug the cable on trainee so there is no command from jack... Looks that it says when feel signal on port and not by some switch on the female jack

**Comment by projectkk2glider** [comment] 2015-10-11 18:30
Yes, the audio announcement is done based on the validity check of the incoming PPM signal and not on the state of PA8 pin.

**Comment by projectkk2glider** [comment] 2015-10-11 18:53
![trainer_jack_x9e](https://cloud.githubusercontent.com/assets/5950438/10418362/8f14afac-7058-11e5-9f32-ca20cdbc3c55.png)
 
I find this schematic of the trainer jack a bit odd. 
* The pin 2 is the tip of the jack and carries PPM signal
* the pin 3 is the first ring of the jack and is **grounded**. 
* the pin 4 is either second ring or a base of the jack
* the pin 1 is the base of the jack and is grounded.

Perhaps the pins 3 and 2 should be reversed and the pin 3 is actually the tip of the jack? That could explain the problems with the mono jacks.

The trainer detect should work either case, but there is additional transistor circuit in between, again by the schematic it looks good.

**Comment by janekx** [comment] 2015-10-11 19:01
I use mono most time and works well, i thing that the female jack on pcb is not alligned  to case so with   some cables can happend connecting issues.   Not  all cables are same long and unpossible to push  them in enough is issue too

**Comment by Eagle69** [comment] 2015-10-13 18:46
Any news about this issue?

**Comment by janekx** [comment] 2015-10-13 18:48
It is fixed now,  only issue is that not appear icon in trainer/trainee role on status bar

**Comment by bsongis** [comment] 2015-10-13 18:50
@janekx But the icon is displayed as soon as you plug in the cable, right? My radio prototype is faulty, I can't check that!

**Comment by janekx** [comment] 2015-10-13 18:53
No icon on production N486

**Comment by arnaudmz** [comment] 2015-10-13 18:53
Can you give us the link to the nightly builds to confirm the fix before the official release of 2.1.4?

**Comment by bsongis** [comment] 2015-10-13 18:55
And do you have an icon with the FrSky original firmware?

**Comment by janekx** [comment] 2015-10-13 18:57
Good question iam  not sure need to try again

**Comment by janekx** [comment] 2015-10-13 19:27
No icon at original working FW, tested now

**Comment by wollenagold** [comment] 2015-10-13 20:23
I tested today again my stereo-type cable and it is really that there are different styles. It isn't much but the tip of one is more spiky, and dosn't connect the signal. The tip who is more blunt gives me connection. Also is the second ring 0,5mm different from the tip.

**Comment by bsongis** [comment] 2015-10-13 20:28
Ok I think we can close the issue, it really seems hardware here.

**Comment by hrenz** [comment] 2015-10-14 05:44
Hy, 
if I use a working kabel at X9E  jacket, 
Values from Trainer ok
Haptik ok
Speach ok
but no Icon at X9E as Master

**Comment by dwcarter1066** [comment] 2015-10-14 22:35
Hi,
I have the same issue described with the trainer port. with my 9xe 2.1.4  ver 217..
The 9xe sends a signal when in Slave (tested on 9xd) ..but will not receive a signal when in master.(tested with 9xd)
To clarify the comments,from what I read above. There is an issue with the firmware 2.14 and with out reverting to 2.1 this issue can not as yet be resolved,

**Comment by bsongis** [comment] 2015-10-15 05:21
Please check the version you are running!

**Comment by janekx** [comment] 2015-10-15 07:08
I suggest to show icon when trainer hear the datas and not on the jack pin connection, When icon will be on user know the radio listen correct data.....

**Comment by LapinFou** [comment] 2015-10-15 07:51
@bsongis
FrSky generated a new firmware from the master branch, but didn't change the revision number.
So, the version which can be downloaded from the FrSky website is named 2.1.4...
http://www.frsky-rc.com/download/view.php?sort=&down=213&file=Firmware-%20Taranis%20X9E

This will not help you when people will report a bug...

**Comment by dwcarter1066** [comment] 2015-10-15 17:34
I have check the firmware and it is a follows:
date 24/09/2015
2.1.4
EEPR217.
As I commented, in Master does not receive a incoming signal, but in Slave it does transmit a signal.

**Comment by dwcarter1066** [comment] 2015-10-15 17:37
I someone can send the 2.1 firmware I will try it. However from what I understand the 2.1.4 firmware is important due to the watchdog bug fix.

**Comment by Murphy25** [comment] 2015-10-15 17:55
Bonjour, je suis partant pour tester...

**Comment by bsongis** [comment] 2015-10-15 17:57
@lapinfou good to know ...

**Comment by dwcarter1066** [comment] 2015-10-15 17:58
Can some please send me the 2.1 firmware I can test it too.

**Comment by Murphy25** [comment] 2015-10-15 18:08
OK to test. I must load 2.1.4 and 2.1.3 templacer French on my radio.

**Comment by janekx** [comment] 2015-10-15 18:12
I can but not now sorry, my internet connection is down and i write from smartphone

**Comment by bsongis** [comment] 2015-10-16 10:45
I got confirmation, the first batch (70 radios) has this problem. FrSky is also aware of the plug connection problem. We can't do anything in the firmware.

**Closed by bsongis** 2015-10-16 10:45 UTC
Labels: Bug, Radio Firmware, X9E

**Comment by Murphy25** [comment] 2015-10-16 11:30
Alors qu'Est-ce que je fait avec ma radio ?

So what do I do with my radio?

**Comment by Murphy25** [comment] 2015-10-16 11:31
So what do I do with my radio?

**Comment by kilrah** [comment] 2015-10-16 11:33
Contact your dealer for warranty repair/replacement?

**Comment by dwcarter1066** [comment] 2015-10-16 11:33
I thought that the 2.1 firmware worked. Can some one sent me the 2.1 to try

**Comment by janekx** [comment] 2015-10-16 11:50
email me to info(at)rcstudio(.)cz 
We are talking only about jack connection notification issue not about the trainer working I think

**Comment by dwcarter1066** [comment] 2015-10-16 11:59
my email is dw dot carter(at)outlook dot com

**Comment by dwcarter1066** [comment] 2015-10-16 12:00
I dont care if the icon works or not, the function of the trainer port is what is important.

**Comment by Murphy25** [comment] 2015-10-16 12:26
Kilrah => Replacement platine swith board ?

**Comment by Murphy25** [comment] 2015-10-16 12:41
I just sent an email with photo microtechnics.be where I bought the X9E to see if he can get me a swith board platinum.
