### ISSUE TITLE
Sensor menu has two lines with "name"

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2533] opened 2015-07-21 17:47 UTC
One can find sensor name at the top and at the bottom of the sensor setup menu. The bottom one is I think a bug.

**Comment by bsongis** [comment] 2015-07-21 17:50
A screenshot? I don't see it!!!

**Comment by projectkk2glider** [comment] 2015-07-21 17:57
![screenshot-2015-07-21-19-48-06](https://cloud.githubusercontent.com/assets/5950438/8808406/b74cd80c-2fe2-11e5-8009-1c11cbde506f.png)
![screenshot-2015-07-21-19-48-09](https://cloud.githubusercontent.com/assets/5950438/8808408/b8da1428-2fe2-11e5-91a0-9f846ea49eab.png)

**Comment by projectkk2glider** [comment] 2015-07-21 17:59
Hmm, it is not present on the simu. Only on my radio (self compiled). Weird.

**Comment by bsongis** [comment] 2015-07-21 18:07
It should be "Logs" with a checkbox. It is ok on my radio.

**Comment by projectkk2glider** [comment] 2015-07-21 18:10
Yes I see it in the simu. Why is there name on my radio, I have no clue. I can even edit the name there and it works!. I will try to rebuild....

**Comment by bsongis** [comment] 2015-07-21 18:16
Perhaps it hides something really bad.

**Comment by bsongis** [comment] 2015-07-21 18:21
Who added the ONLYPOSITIVE?

**Comment by projectkk2glider** [comment] 2015-07-21 18:24
Me :grinning:  am I to blame?

**Comment by bsongis** [comment] 2015-07-21 18:27
No, me who still didn't rewrite this menu system ... all ideas welcome!

**Comment by projectkk2glider** [comment] 2015-07-21 18:29
Uff, the menu system is so deeply embedded... it would be a big undertaking.

**Comment by bsongis** [comment] 2015-07-21 18:30
Yes, but if you find a good inspiration source, I am interested.

**Comment by projectkk2glider** [comment] 2015-07-21 18:40
Tested and confirmed, the fix is good. :+1: 

I am a little ashamed to admit :blush: , but today was the first time I used 2.1 on my working radio and hooked up to a model. At least I found a couple of bugs.

**Comment by bsongis** [comment] 2015-07-21 18:47
And do you like 2.1?

**Comment by projectkk2glider** [comment] 2015-07-21 19:12
Yes of course. For my relatively simple multi-rotor model the conversion process (on the radio) was flawless. I have still to verify more complex models (F5X sailplanes). But looking gooood.

**Comment by griebd** [comment] 2015-07-25 12:30
I may be wrong on that, but I think the problem is still there but in a different case...

I have a self compiled OpenTX from commit 2b25071 for Taranis Plus (make PCB=TARANIS PCBREV=REVPLUS HELI=YES GVARS=YES MIXERS_MONITOR=YES TEMPLATES=NO).

Have a model configured with X6R receiver, FLVSS and RPM sensors.

In TELEMETRY screen If I add a new sensor with the following configuration I get a 'name' line at the end.
Type: Calculated
Formula: Cell

The 'name' line appears as soon as I select Cell in Formula!

**Comment by kilrah** [comment] 2015-07-25 14:31
Just tried with current master, same command line and same sensors, can't reproduce... did you make clean before?

**Comment by griebd** [comment] 2015-07-25 18:17
yes, I did... but to be sure I updated to the current master, make clean and same make again... and updated the radio with the new file, of course. ;)

still the same, 'name' line at the end! can't get to it and when I update the name in the first line the last gets updated too...

would a backup of my model help?

**Comment by kilrah** [comment] 2015-07-25 19:53
maybe yes... but what would be even better is the exact steps to reveal the bug starting from a new blank model.

**Comment by griebd** [comment] 2015-07-25 20:39
ok, did try a new model on radio and on simulator:
1. create new model
2. go to telemetry screen
3. add a new sensor with: name: a type: custom id: 0300 0 unit: v precision: prec2
4. add a new sensor with: name: b type: calculated formula: cell
5. and then in that moment you have the error that is different on radio and on simulator
a) on radio the last line is 'name' as described before
b) on simulator the last line ('logs') is duplicated, both get selected together and I can't mark it

**Comment by bsongis** [comment] 2015-07-25 21:02
I don't reproduce on simu
Are you on latest nightly builds? You say unit is 'v', it should be 'V' in the latest nightly builds, do you confirm?

**Comment by kilrah** [comment] 2015-07-25 21:05
OK... I checked out that precise commit this time and built both firmware and simulator on Windows (firmware with the "approved" gcc 4.7-2014q2), flashed to my T+.

Following those exact instructions I don't get any issue neither on the radio nor on the simu (and both behave the same). 

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/8891223/5bfce482-3321-11e5-8c38-ed94145d1257.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/6065069/8891224/5dcf0114-3321-11e5-806e-135af5f159c0.png)

![screenshot-3](https://cloud.githubusercontent.com/assets/6065069/8891225/5f1e6104-3321-11e5-8ae7-64895c4dfe3b.png)

> 3. add a new sensor with: name: a type: custom id: 0300 0 unit: v precision: prec2

Note that this will not create a valid Cells sensor, you won't be able to select it in the "b" sensor as a source. At this point a Cell sensor can not be entered manually, it has to be autodiscovered. It uses a special "virtual unit" that allows handling the special case it is but is not available for manual selection.

**Comment by griebd** [comment] 2015-07-25 21:20
about your note at the end, no problems, I did this way just to see the error appear on my model the sensor is auto-discovered...

about the problem, I will dive it the code myself and see what is going on, maybe a problem with compiler versions... (was reluctant to do so because it's the first time I'll look at the radio code itself)

if I find the problem I'll made a pull request! and as this apparently is a problem of mine, lets close this issue again. ;)

**Comment by griebd** [comment] 2015-07-25 23:10
@bsongis, yes, it's V, I mostly always forget to use 'caps'... :wink:

anyway, just discovered why you are not seen the issue on simulator!
I was building companion for daily use, so I used 'cmake -DCMAKE_BUILD_TYPE=Release' by default...
if I build a Debug version I have no problems in companion simulator too. same if I avoid -DCMAKE_BUILD_TYPE altogether!

I probably shouldn't have used -DCMAKE_BUILD_TYPE=Release, right?

but that is still not the case for the radio itself, no cmake in that case. but still a different version of gcc, I will try your 'official' version later.

**Comment by projectkk2glider** [comment] 2015-07-26 11:57
That is a rather clear indication that some variable is uninitialized.

**Comment by projectkk2glider** [comment] 2015-07-26 12:05
Found one problem on simu: the Cells sensor :
![snapshot_12](https://cloud.githubusercontent.com/assets/5950438/8893797/6bf40900-339f-11e5-8ed2-a79393944f45.png)

**Comment by projectkk2glider** [comment] 2015-07-26 12:39
Found one bug, fix coming soon...

**Closed** 2015-07-26 13:06 UTC
Labels: Bug, Radio Firmware

**Comment by griebd** [comment] 2015-07-26 13:27
@projectkk2glider, thanks!!!! checked both in simulator and in radio, they are both correct now!!!

by the way, working with:
gcc (GCC) 4.8.2
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.8.4 20140725 (release) [ARM/embedded-4_8-branch revision 213147]

compiled with:
make PCB=TARANIS PCBREV=REVPLUS HELI=YES GVARS=YES MIXERS_MONITOR=YES TEMPLATES=NO
cmake -DCMAKE_BUILD_TYPE=Release ../companion/src/
make

**Comment by kilrah** [comment] 2015-07-26 13:51
I don't know if the situation has evolved on either side but we used to have problems with gcc 4.8 and recommended not to use it.

**Comment by griebd** [comment] 2015-07-26 21:34
talking about the firmware, what kinds of problems?
I have it compiled with no errors or warnings.... and so far the only problem I have noticed was the one reported and fixed above!
I did see the recommendation to use 4.7, but 4.8 was already available and laziness convinced me to use it!
anyway, will try to keep using it (until I have a reason to change) and if you need some tests done on it, please tell me! I'll gladly help.

**Comment by bsongis** [comment] 2015-07-26 21:54
Yes there were problems with 4.8 when we compiled in -O2
Now we use -Os (and we also fixed a bug in CoOS) but we didn't switch to 4.8
If you confirm it works perhaps we will change our mind for 2.1.2
