### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by eirrick** [opentx/opentx#5634] opened 2018-01-17 01:42 UTC
I am using companion v2.2.1 on ubuntu linux, and I'm getting cannot check for updates error when I try to check for updates or download firmware for my taranis x9d+.

**Comment by 3djc** [comment] 2018-01-17 07:16
I cannot reproduce your issue (but I'm trying on debian stretch). Please give as much details as possible

**Comment by selste** [comment] 2018-01-21 14:26
Hi,
same problem here - installed the latest OpenTX version via the provided Ubuntu PPA, and for the last couple of days every time i start the companion software i get the 'cannot check for updates' error dialog.

Enabling debug otput didn't actually help, there are just a couple of messages about the location and registration of shared libraries after startup.

**Comment by 3djc** [comment] 2018-01-21 15:07
2.2.1 ?

**Comment by selste** [comment] 2018-01-21 15:41
Yes,
version 2.2.1, via [Packages in “OpenTX Releases”](https://launchpad.net/~opentx-test/+archive/ubuntu/rel/+packages).
Noticed that the firmware downloads weren't working maybe 3 days ago while experimenting with telemetry settings for my Turnigy 9X.

When i reinstalled OpenTX 2.2.1 (must have been around New Year) the downloads worked just fine.

**Comment by powercycle** [comment] 2018-01-21 18:44
I can confirm this as well.

**Comment by 3djc** [comment] 2018-01-21 18:44
We are currently working on it

**Comment by powercycle** [comment] 2018-01-21 18:45
If it matters, mine has a date of November 10, 2017 from the about menu.

**Comment by eirrick** [comment] 2018-01-21 18:52
2 days ago, I actually uninstalled the package provided by the ubuntu PPA and installed from the debian package. That fixed the issue. Maybe that helps.

**Comment by eirrick** [comment] 2018-01-21 19:03
I'm running Ubuntu 17.10.

**Comment by powercycle** [comment] 2018-01-21 19:05
For me, it seems I didn't have the actual release version.   Now that I've downloaded that, it shows December 17, 2017 as the date in the about screen.  This now works for me.
![screenshot_2018-01-21_10-05-09](https://user-images.githubusercontent.com/2614846/35197859-991c50c0-fe92-11e7-8139-7596a1954944.png)

**Comment by powercycle** [comment] 2018-01-21 19:07
I got the working version from 
![image](https://user-images.githubusercontent.com/2614846/35197887-ec16b2ca-fe92-11e7-82e6-61fde74632bd.png)

**Comment by 3djc** [comment] 2018-01-21 19:09
It should be ok now

**Comment by selste** [comment] 2018-01-22 16:17
Hi,
sorry - still not working for me.
I'm running the 32 Bit variant, therefore i can't (easily) switch to the Debian package.

**Comment by 3djc** [comment] 2018-01-22 16:22
Can you launch it using command line and report what is happening, because it looks ok from here

**Comment by selste** [comment] 2018-01-22 17:42
Console output:
[opentx.log](https://github.com/opentx/opentx/files/1652973/opentx.log)
I got basically the same output when i enabled debugging.

Screenshot of the 'About' dialog:
![opentx](https://user-images.githubusercontent.com/54494/35235269-f342c6bc-ffa3-11e7-81d2-43235cab454a.png)

Hmm ... wait a sec - according to the OpenTX homepage release 2.2.1 dates from December 16, but this says Nov 10.
Still, it used to work until a couple of days ago.

**Comment by 3djc** [comment] 2018-01-22 18:00
Wait wait. What is that November 2.2.1 ? You said it is coming from release ppa, there was no 2.2.1 release in November ????

**Comment by 3djc** [comment] 2018-01-22 18:04
I’ll go back in time to November 10 having a look at what was downloaded at that time

**Comment by selste** [comment] 2018-01-22 18:18
Right,
i uninstalled the application, downloaded the latest deb archive from the PPA page, and manually installed it.
Working as expected now, no errors.

Doublechecked, i had the correct PPA in the 'sources.list.d' folder ...
When i ran the manual install i got a message that there was an older version available via the package sources - pretty strange!

**Comment by 3djc** [comment] 2018-01-22 18:30
OK, meanwhile I have investigated, the url used at that point in time is not availble anymore, but also not in use by any production  version of companion, ,neitehr by current companion nightly. Given that restoring it does have other implication, I do not plan to fix this url , the better fix being downloading release 2.2.1, which you did and it worked. I'm closing this, but please keep reporting those issues if they arise again

**Closed as completed by 3djc** 2018-01-22 18:30 UTC

**Comment by selste** [comment] 2018-01-22 18:35
Thanks for taking the time to investigate and resolve this problem!

OpenTX is awesome!
