### ISSUE TITLE
Improve request Too much backlight lcd to night flight

### ISSUE THREAD

**Issue by flaviomartins8** [opentx/opentx#5883] opened 2018-05-10 08:37 UTC
Hi,
I tried several times and i do not found the sleep mode in taranis X10s with opentx-x10-2.2.1(cca 71808) eepr:218
Backlight:
Off
duration 0s
On and Off Brightness are in the min.
I do not found any special function to turn off completely the light
we only can use min to max light.
in the minimum, the light is too much for night flight.
Tks

As i see, we have a function in frskyOS,
https://github.com/FrSky-OS/HORUS-X10-X10S-X12S-bug-report/issues/196
I opne the same issue in wrong place, FrskyOS

**Comment by 3djc** [comment] 2018-05-10 08:40
Duplicate of already fixed #5621

**Closed as completed by 3djc** 2018-05-10 08:40 UTC
