### ISSUE TITLE
Companion 2.1 repeatedly accesses floppy disk.

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#2160] opened 2015-03-22 12:34 UTC
Loaded Companion 2.0.99 on an WINXP SP3 desktop with a floppy disk drive. (Remember them?).

Floppy disk is accessed about once per second, repeatedely. No disk in drive, light flashes, drive clicks.
Open settings menu, close settings menu, floppy disk now accessed twice about every second.
Open a file and close, now three times every second.etc.

Tried another XP desktop and same condition.

Disabled floppy disk, don't use it anyway, but wondered if it indicates some other possible problem.

Doesn't happen on Companion 2.0.15. or previous versions used on this machine.

**Comment by kilrah** [comment] 2015-03-22 17:41
What are the different paths in the settings set to?

**Comment by Mow06** [comment] 2015-03-22 22:33
All set to C:/ drive settings, same as the 2.0.15 Companion settings. I've tried resetting everything and it still does it.

**Comment by bsongis** [comment] 2015-03-23 05:52
I think it's for the SD share button refresh, it polls all drives

**Comment by projectkk2glider** [comment] 2015-03-23 18:56
Two separate bugs.

First one is caused in `void MainWindow::updateMenus()` which calls `updateSdsyncAction();` Each call creates a new timer with 1s timeout. This explains the behaviour of 1, 2, 3 floppy acesses each second.

Second bug is access to floppy drive. It is caused by `findMassstoragePath()`which enumerates all drives and gets called periodically by `updateSdsyncAction();` Several possibilities to solve:
* we ignore drive letters A and B on Windows (that still leaves problem on Linux and Mac)
* we determine drive type for each device without access to device and skip it if it is floppy drive (not sure if this is possible, have to research....)

**Comment by projectkk2glider** [comment] 2015-03-23 19:34
First bug fixed, but the second one (skip floppy drives on Windows) is difficult. There is no simple solution, the best I have found is http://stackoverflow.com/questions/3156284/check-floppy-drive

I don't have a native Windows environment, so I am leaving this to someone else :)

**Comment by fraternl** [comment] 2015-04-29 21:27
If the problem is repeated access one could check the capacity and then leave out all with a capacity of less than a GB.

**Comment by romoloman** [comment] 2015-05-01 21:47
It would be possible to compile at runtime a blacklist of devices by using NtQueryVolumeInformationFile from winddk, at the first call of findmassstoragepath we compile the list by blacklisting all the devices that do not have the FILE_REMOVABLE_MEDIA flag set and that have FILE_FLOPPY_DISKETTE flag set.
In next call of the function we just skip drives in blacklist.
The only problem is that for calling NtQueryVolumeInformationFile we also need to install winddk.

**Comment by bsongis** [comment] 2015-05-11 20:32
Thanks to @romoloman I close this issue.

**Comment by Mow06** [comment] 2015-06-27 12:37
Been away for some time. Finally got to test this. 2015_06_27 is still accessing Floppy disk continuously.

**Comment by fraternl** [comment] 2015-07-03 18:27
First time I'm using Companion 2.1 on a machine with a Floppy drive.
It's still accessing it continuously on version 2015-07-03

**Comment by kilrah** [comment] 2015-07-18 07:27
Reopening that as there are still reports of the issue with release version.

**Comment by bsongis** [comment] 2015-07-18 10:26
I think I will make the button always enable, it will remove all problems!

**Closed** 2015-07-18 11:23 UTC
Labels: Bug, Companion

**Comment by kilrah** [comment] 2015-07-18 12:47
Yeah, as long as an error is thrown if the button is pressed and the card isn't available it should be good!

**Comment by projectkk2glider** [comment] 2015-07-18 16:22
It is good, erorr looks like this:
![screenshot](https://cloud.githubusercontent.com/assets/5950438/8762472/df1c6b06-2d79-11e5-8e3b-2db0b238b2c0.png)
