### ISSUE TITLE
Companion Crashes on startup

### ISSUE THREAD

**Issue by nveeser** [opentx/opentx#5123] opened 2017-07-30 17:31 UTC
Companion 2.2.0 crashes on startup on OSX
Tried two different machines

[github_bug.txt](https://github.com/opentx/opentx/files/1188803/github_bug.txt)

**Comment by RCdiy** [comment] 2017-07-30 19:17
Could you edit the first post and remove the debug output but place in an attached text file? I once posted something similar and received a similar request.

I'm on macOS Sierra 10.12.6 (16G29) and have not had any issues.
Is there a forum thread somewhere on this? If not maybe post and I or someone else will try and help.
https://www.rcgroups.com/forums/showthread.php?2823315-OpenTx-2-2
or
http://openrcforums.com/forum/viewforum.php?f=45

**Comment by RCdiy** [comment] 2017-07-30 19:21
I just did a download from http://www.open-tx.org/2017/05/30/opentx-2.2.0 and have had no trouble running it. 

I was able to run it from both the Application folder and the desktop.

**Comment by nveeser** [comment] 2017-07-31 20:50
I suspect that this is something to do with my preferences, or some such. Makes it hard to track down but still should not be happening

**Comment by schwabe** [comment] 2017-08-01 14:25
I think this bug is fixed in newer version. If you want, you can try this test build and see if it fixes your problem: http://opentx.blinkt.de:8080/~opentx/builds/opentx-companion-2.2.0test.dmg

**Comment by nveeser** [comment] 2017-08-01 23:56
Yes that seems to work for me. What was the issue?
FYI: Sierra 10.12.5 (16F73)

**Comment by rhyde** [comment] 2017-08-12 01:29
I am seeing a startup crash on OSX Yosmite.  I tried deleteing the previous preference files, but that did not change it.

**Comment by schwabe** [comment] 2017-08-12 09:12
@rhyde: your crash you posted in #5016 is also setting import related 2.2.1 should fix this (or the test version I posted here).

**Comment by kilrah** [comment] 2017-11-08 13:09
Duplicate of #5076

**Closed as completed by kilrah** 2017-11-08 13:09 UTC
