### ISSUE TITLE
GPS is unable to handle negative heights

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3594] opened 2016-06-13 07:05 UTC
Half of our country is beneath sea level and when I use my GPS there (uBlox, SP Racing F3, S-port to Frsky XSR) the height is clipped at 0, but also shoots at 65535 sometimes.

I thought it was cleanflight's fault, but they write it's properly handled by them.

Could you examine where it's done wrong?
I can only test a few days from now as I'm going on holiday next weekend.
https://github.com/cleanflight/cleanflight/issues/2223

It should only be a use of "int" where now an "unsigned int" is used.

https://github.com/cleanflight/cleanflight/issues/2223

**Comment by 3djc** [comment] 2016-06-13 07:29
https://github.com/cleanflight/cleanflight/blob/e133331cf34f94109774181c2d6f3ae74f4fba05/src/main/io/gps.h

Line 110:
extern uint16_t GPS_altitude;              // altitude in 0.1m

Looks like they are handling it unsigned; I believe OpenTx handles negative GAlt

**Comment by 3djc** [comment] 2016-06-13 07:41
What is displayed in cleanflight configurator when you have a GPS lock ?

**Comment by fraternl** [comment] 2016-06-13 09:06
I've never seen that...
Where I have my computer I can't get a GPS-lock and if I could it's on the first floor.

I will test something this afternoon using a laptop.

**Comment by fraternl** [comment] 2016-06-13 13:19
I just now tested it in Cleanflight configurator and there it is reported as 65533 metres.....
I think I will head over to the Cleanflight section....

**Comment by projectkk2glider** [comment] 2016-06-13 13:25
Closing then, reopen if the problem is indeed in OpenTX.

**Closed by projectkk2glider** 2016-06-13 13:25 UTC

**Comment by fraternl** [comment] 2016-06-13 16:58
I can't judge it properly.
It seems they insist it's in OpenTX

**Comment by bsongis** [comment] 2016-06-13 17:09
Do you need a firmware with LOG_TELEMETRY=YES ? 
There will be no doubt ...

**Comment by fraternl** [comment] 2016-06-13 17:12
Hi Bertrand...
I assume that will log the raw data.
Yes, please....
I'm currently running today's nightly

**Comment by kilrah** [comment] 2016-06-13 17:21
Could we not have an issue here? 
https://github.com/opentx/opentx/blob/master/radio/src/telemetry/frsky_sport.cpp#L188

Seems everything we receive is considered unsigned?

**Comment by fraternl** [comment] 2016-06-13 17:25
And how does latitude/longitude work?
These can be negative as well or is that carried in another field?

**Comment by schwabe** [comment] 2016-06-13 17:29
I think that signed is converted later. @fraternl does your flight board have a barometer? 

My cleanflight board has one and the (relative) altitude is sometimes negative.  I remember that there was some version (2.1.6 or 2.1.7) that a a broken altitude that showed -4,2 million.

And I cannot find a difference in GPS altitude and normal altitude handling in OpenTX at the moment.

**Comment by fraternl** [comment] 2016-06-13 17:39
Yes, I have a barometer and it can go negative...

**Comment by fraternl** [comment] 2016-06-13 17:44
I can wait some more for that "LOG_TELEMETRY=yes" version.
But if that takes a bit longer I'm going home to eat and I can test it tomorrow.
I'm sorry to admit that I have no development environment for OpenTX.

**Comment by schwabe** [comment] 2016-06-13 17:53
@fraternl I looked into the cleanflight source and I think I found the problem. I commented on the Cleanflight bug tracker

**Comment by projectkk2glider** [comment] 2016-06-13 18:00
@schwabe you are correct :+1:
