### ISSUE TITLE
Stick data updates much slower than RF packet rate

### ISSUE THREAD

**Issue by Faultyclubs** [opentx/opentx#8414] opened 2021-04-03 21:08 UTC
I am using the Radiomaster TX16S with Redpine protocol (2ms).

Using Betaflight Blackbox debug logging I can see that the RF packets are indeed arriving at 2ms as expected, HOWEVER the underlying stick data is only be updated every 6-8ms.   Meaning every three or four packets contain the same data.  This duplicated data is a problem, worse even that dropped packets, and especially affects feedforward causing rough motors.   And obviously negates the latency potential of the 2ms Redpine protocol.

I asked Radiomaster and understood from them the TX16S runs at 400k baud internally and should be fast enough therefore it is a software problem.

Is this a known problem and if so what  is causing the problem please and can it be fixed?

Thanks.

**Comment by kilrah** [comment] 2021-04-03 22:24
The protocol used by the multimodule to give it control data isn't designed with maximal speed in mind but flexibility.
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module

**Comment by Faultyclubs** [comment] 2021-04-03 22:43
What is the maximum RF packet rate that works properly then, please?

Also the link shows a "fast serial" interface to OpenTX.  My simple minded calculations shows that 400k is fast enough.  Isn't it?   Is OpenTX not using the full potential of the TX16S?   I'm sorry but am not quite understanding where the bottleneck is.

**Comment by kilrah** [comment] 2021-04-03 23:03
The software running on the RF module needs to be talked to at 100kbps and a frame is around 4ms. OpenTX just provides what the module wants. 

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/931ba2bd68f345f1c6eb59f6f0bb64e25e484bc5/Multiprotocol/Multiprotocol.h#L801

**Comment by Faultyclubs** [comment] 2021-04-04 00:15
I see.  But is that a legacy kind of thing?  If the TX16S is indeed running at 400k interface to it's internal MPM then all that is needed would be software updates (coordinated on both sides) as Radiomaster suggested...correct?  I realize that would be pushing the envelope and require work but seems worth it to get properly working protocols.   If it's even technically feasible of course, I can't find any hardware information on the TX16S to confirm that it really does support 400k to the MPM.

Also, not trying to be argumentative but are you sure about the 4ms?  That is not consistent with what I'm seeing.  It seems to be much higher.  I can show the logs if necessary.   At 4ms I would switch to S-FHSS to get consistent packets but even my 6.8ms S-FHSS seems to be duplicating packets.  (If S-FHSS *should* be working then I need to figure out why it is duplicating packets.)  I'm often seeing 8ms on Redpine.   I am running v2.3.9 though in case there's been a recent change.

**Comment by dgatf** [comment] 2021-04-04 08:13
> Using Betaflight Blackbox debug logging I can see that the RF packets are indeed arriving at 2ms as expected, HOWEVER the underlying stick data is only be updated every 6-8ms.

This is probably due to the period defined to update the mixer for the Multimodule in Opentx:

https://github.com/opentx/opentx/blob/a167ded9b534f373904e4424e053187b90237b8a/radio/src/pulses/pulses.h#L233

I'd expect frames get updated more frequently reducing this parameter

**Comment by Faultyclubs** [comment] 2021-04-04 16:13
Wow, great find.  I wish I knew my way around the code like some of you guys do.

Yes, 7ms explains what I'm seeing on Redpine.   It also explains why S-FHSS is getting buggered up.  S-FHSS is 6.8ms protocol which just misses the cutoff.  Can we at least adjust this parameter so S-FHSS works properly (ie consistent 6.8ms with no stale stick data).

Ideally we improve Redpine too.  Constant 6ms is better than jittery 6-8ms.  And of course 4ms is better still...

I can't help on the development but can test changes.

**Comment by 3djc** [comment] 2021-04-04 16:14
That’s not how it works, the multimodule ask for a specific rate as it sees fit

**Comment by raphaelcoeffic** [comment] 2021-04-06 07:46
@Faultyclubs if 500Hz is what you want, you should really have a look at ExpressLRS, because it's working there  ;-) (together with the new sync merged yesterday into 2.3)

**Closed as completed** 2021-04-06 07:49 UTC

**Comment by Faultyclubs** [comment] 2021-04-06 17:06
Close this if you want but, with all due respect, you guys didn't do anything. :)

S-FHSS is a well established protocol and should be fixed IMHO. The only stated technical limitation is the 100k link which is more than sufficient for S-FHSS to work properly.

In the process Redpine might be improved too since 100k should support better than 8ms.

ExpressLRS does sound promising.  Especially if it works on microwhoops with SPI receivers.  I had heard that wasn't going to happen though.  If not, then perhaps Redpine could be ported onto the ExpressLRS hardware for the tiny whoop guys.  I think the transceivers might be capable.

**Comment by kilrah** [comment] 2021-04-06 18:28
> but, with all due respect, you guys didn't do anything. :)

Of course, because as mentioned there's nothing for us to do at this point...

If you want faster multi then first get multi to run faster, then we can see to make it work from opentx :)

**Comment by raphaelcoeffic** [comment] 2021-04-07 11:16
> Close this if you want but, with all due respect, you guys didn't do anything. :)

@Faultyclubs

For my part, I strongly disagree:
- coordinated with 3 different parties / companies
- added a new sync mechanism
- added dynamic rates to adapt to the module's wishes

I cannot possibly go as well to each of the module makers and implement it for them. However, there is now a common interface for modules to request sync and dynamic rates. I'd say, now it's up to you ;-)

**Comment by brycedjohnson** [comment] 2021-05-05 22:12
@Faultyclubs agree with the above guys.  I wrote redpine, it was designed around deviationTX and later ported to MPM.  Currently it is MPM limitations prevent the higher updates.  I did some brief working looking to improve that, but haven't spent time on it lately.  It certainly is possible though, just need someone with some time to dig into it!

On a side note: SX1280 chipset on ELRS talking redpine to cc2500 spi receiver is on my list of things to try at some point.  Looks theoretically possible, but not tried out yet.

**Comment by raphaelcoeffic** [comment] 2021-05-06 05:34
> On a side note: SX1280 chipset on ELRS talking redpine to cc2500 spi receiver is on my list of things to try at some point. Looks theoretically possible, but not tried out yet.

@brycedjohnson that would be great! and if we could do the same thing with Frsky D8/D16, it would be just perfect!

**Comment by brycedjohnson** [comment] 2021-05-06 17:12
@raphaelcoeffic D8 D16 might not be possible because SX1280 only supported a few bitrates in FSK mode.  B8 D16 use an odd ball (?)46Kbs rate.  Redpine fast mode is 250Kbs that look like one of the supported rates.

![image](https://user-images.githubusercontent.com/2583801/117338521-e7413780-ae5b-11eb-8c75-8dc78e608f22.png)
