### ISSUE TITLE
X-Lite: Can't switch to "Bars" Telemetry page

### ISSUE THREAD

**Issue by ps915** [opentx/opentx#6044] opened 2018-07-14 11:23 UTC
If i create 3 Telemetry Screens where one is "Bars" i cant switch to this page.

[![LUA Script X-Lite KISS CC - Test #04](https://img.youtube.com/vi/9TFX4_sGkMI/0.jpg)](https://www.youtube.com/watch?v=9TFX4_sGkMI)

**Comment by 3djc** [comment] 2018-07-14 11:37
I cannot reproduce (but I'm not using the BF script). Two pages with nums, third with bars, I access it wihout issues. Could you test without the BT script ?

**Comment by ps915** [comment] 2018-07-14 11:42
Same without the BF Script. Screen 1 "Bars", Screen 2 "Nums". I only can see "Nums". If i switch it just blinks a millisecond that i can barely see the bars and its switches back to "Nums"

**Comment by kilrah** [comment] 2018-07-14 13:07
Can't reproduce either even with bf script. What version?

**Comment by 3djc** [comment] 2018-07-15 06:45
Please give us details on your opentx exact version and post your otx, as we are unable to replicate this issue

**Comment by salem83** [comment] 2018-07-26 18:38
same issue here
```
FW: opentx-xlite
VERS: 2.2.2 RC4 (4880497d)
EEPR: 218
```
it can also be reproduced with the simulator of the companion
1. Profile -> Radio Type -> X-Lite
2. Load the following otx (or create a blank, telempage 1 -> numbers, 2 -> bars)
[opentx_issue_6044.zip](https://github.com/opentx/opentx/files/2233156/opentx_issue_6044.zip)
3. start simualtor
4. open telemetry
5. try to switch between the pages

**Comment by 3djc** [comment] 2018-07-26 19:43
Maybe put valid bars limit ? Because 0 to 0 ain't gonna work

**Comment by salem83** [comment] 2018-07-28 07:36
thanks, that did the trick ...
but Is there any possibility to inform the user about an invalid configuration instead of "not working"?
i also noted if "low > high" it won't work either.

**Comment by SebbaLing** [comment] 2018-08-15 20:25
when i am using bf script, i cannot change to any other telemetry page...

which button should change telemetry pages?

**Comment by FearCapone** [comment] 2018-08-31 02:35
Same here. If i use lua Script,i can't switch to other telemetry pages

**Comment by 3djc** [comment] 2018-08-31 05:05
Initial issue was user error, hence closing

**Closed as completed by 3djc** 2018-08-31 05:05 UTC
