### ISSUE TITLE
Model conversion warning with Sky9x board

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5327] opened 2017-11-07 10:16 UTC
My T9x+sky9x is flashed with OpenTX 2.2.0

My models have been converted from an older release of OpenTx, they are working well.

But every time i read them from the radio i get a conversion message warning :

![bug_companion](https://user-images.githubusercontent.com/985702/32488360-a156f81a-c3ac-11e7-9d84-1fe123649040.png)

![bug_companion_2](https://user-images.githubusercontent.com/985702/32488493-177c5562-c3ad-11e7-9997-388f8205b652.png)

**Comment by schwabe** [comment] 2017-11-07 10:25
#5326  might actually caused by this.

**Comment by kilrah** [comment] 2017-11-08 11:09
Duplicate of #5009.

**Closed as completed by kilrah** 2017-11-08 11:09 UTC
