### ISSUE TITLE
Audio not playing in companion9x simulator

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#457] opened 2013-12-06 13:30 UTC
_From [mickwp...@gmail.com](https://code.google.com/u/111814648479692963065/) on September 16, 2013 07:59:48_

What steps will reproduce the problem? Companion9x does not play audio or sound track on PC

Should be able to preview/simulate the audio custom function or audio custom switch using the companion9x simulator

Version Companion9x  1.47
OS: windows 7 64bit
Firmware opentx0r2751 (Taranis)

_Original issue: http://code.google.com/p/companion9x/issues/detail?id=257_

**Comment by JoeB99** [comment] 2015-02-15 00:48
Did this ever get fixed? I'm not getting any audio in the simulator which is making the setup of audio alerts quite time consuming.

**Comment by kilrah** [comment] 2015-02-15 06:44
It is coded but not tested/included yet.

**Comment by JoeB99** [comment] 2015-02-15 09:17
Fantastic news !

**Comment by projectkk2glider** [comment] 2015-02-22 14:53
Both `master` and `next` have this now, closing.

**Closed by projectkk2glider** 2015-02-22 14:53 UTC
Labels: Companion, enhancement, Priority-Medium

**Comment by JoeB99** [comment] 2015-02-23 15:44
I've just tried this with the latest nightly build 23-FEB-2015, and it did not work for me. I tried a sound assigned to a switch (play value, timer), and also minute callout, voice, for an active timer. No sound for either.

Win7 x64

**Comment by projectkk2glider** [comment] 2015-02-23 17:43
I just tried the nightly build http://jenkins.open-tx.org/nightly-20/02_23_2015/companionInstall_2.0.15.exe on my virtual machine running Windows XP. It works.

Do you have a proper SD card path setup in Companion? Simulator now relies on audio files there and uses them to play voices. If it can not found them it wont work. What will work is if you click on trim buttons (not move trim sliders),  you should hear beeps. If that works for you then the sound works.

You could also paste the text that appears in a Debug Output window after you press key F6 in simulator and post it here. The output will show if simulator is finding sound files or not.

**Comment by JoeB99** [comment] 2015-02-23 18:01
OK, i have tried again (needed to restart companion after adding sounds dir), and yes it is working, but there are 2 things wrong with it. 

1) 
The sound is very quiet, i turned the sound on the PC up really loud and the timer count down is still quiet. 

2) 
The time it takes to "Play Value". 
Set the timer to 2 mins, then add a SF to play the timer value. It takes a second to read each part, e.g. 
"one" <sec pause> "minute" <sec pause> "thirty" <sec pause> "six" <sec pause> "seconds"

The slow playback is not a big problem, but the quiet sound will be a problem as when i receive email or some other windows sound is played, it is really loud!

**Comment by projectkk2glider** [comment] 2015-02-23 18:06
Correct the sound level is low, to make it more acceptable adjust volume in radio settings to maximum and it should be better. I might still not be loud enough, that is why we are planing to add some kind of volume gain in Companion for simulator sounds volume.

The slowness you

**Comment by JoeB99** [comment] 2015-02-23 18:13
It is slow on my pc (win7 x64), I will try on a different pc later which will also be win7x64, and update here with my findings.

**Comment by projectkk2glider** [comment] 2015-02-23 18:17
Make a short video that shows your problem and post it on youtube.

**Comment by projectkk2glider** [comment] 2015-02-23 18:32
Mine is at http://youtu.be/X64ao6a0moQ

**Comment by JoeB99** [comment] 2015-02-23 19:28
By turning the WAV volume to maximum in the sim, the audio is about the same level as windows sounds. When this is set to default middle value, it is too quiet to hear. Perhaps consider increasing the wav file player volume so that at mid volume, it plays at whatever the current max is, and at max, it increases by the same amount again?

The speed i'll check shortly.

**Comment by jtaylor2** [comment] 2015-02-23 21:01
For what its worth I have no audio slowness on either my Windows 7 64 bit laptop using the downloaded nightly or self compiled master on my OpenSUSE 13.2 desktop.  Volume is also very good on both of them.

Very nice, much better than the hack I've been using to get sound in companion for the last year.

Jim

**Comment by JoeB99** [comment] 2015-02-23 22:39
I've tried this on my home PC and it is all working perfectly. The sound volume is just the right volume and the reading of timer 1 is at normal speed.
I don't know how to proceed now? I'll take a video of the problem tomorrow.

**Comment by JoeB99** [comment] 2015-02-24 11:33
I've been playing with this and i have figured out that it works pefectly with the sounds from the sounds pack:
http://voices-20.open-tx.org/opentx-taranisplus/en/openTx-taranis-english.zip

But doesn't work correctly with sounds generated by "speaker":
http://www.open-tx.org/2014/03/15/opentx-speaker/

I have tried this on both PCs and both show the problem.

**Comment by projectkk2glider** [comment] 2015-02-24 21:23
@JoeB99 can you upload one such *slow* file somewhere and post link here.

**Comment by JoeB99** [comment] 2015-02-24 23:09
Video:
http://youtu.be/SFtsvXabll4

Sound files:
http://1drv.ms/17UJt8m

**Comment by projectkk2glider** [comment] 2015-02-25 08:04
The problem is in the sound files you provided. They contain a huge amount of silence at the end of each file. For example number five. Top is your sound, bottom is original one:

![screenshot from 2015-02-25 09 01 52](https://cloud.githubusercontent.com/assets/5950438/6366944/2a966dc0-bccd-11e4-959b-026d9a65d828.png)

When such files are played, the pause is also played and they appear to be playing slow to you. It should behave exactly the same on the real radio with such files.

**Comment by JoeB99** [comment] 2015-02-25 09:31
OK, phew! This means this is a bug with OpenTX-Speaker because that's what I used to create the files (see video).

**Comment by projectkk2glider** [comment] 2015-02-25 11:37
>This means this is a bug with OpenTX-Speaker

Might be, if I remember correctly it uses Windows speech generator which might also be responsible for this.

**Comment by JoeB99** [comment] 2015-06-12 22:54
Any update on this? I need to create some new sound files... What does everyone use for this? What was used to create the open tx voices here:

http://voices-20.open-tx.org/opentx-taranis/en/
