### ISSUE TITLE
Random Haptic Feedback

### ISSUE THREAD

**Issue by cpwilson** [opentx/opentx#2722] opened 2015-08-16 19:12 UTC
Experiencing random haptic feedback on Taranis Plus on 2.1.1 firmware.

Only experienced the issue on a model where the internal radio is off and external module (immersion uhf) is enabled.    At random times there is haptic feedback pulses for no apparent reason.   

Also when selecting the model using uhf have seen the Control Warning check screen fail to display the switches and the display is corrupt until radio is power cycled.

**Comment by cpwilson** [comment] 2015-08-16 19:14
Reverted TX back to firmware 2.0.17 and issue is not present.

**Comment by kilrah** [comment] 2015-08-17 07:24
What ezuhf version? The JR module or "big one"? The big one is known to provoke strong fields that cause undesired operation if it's too close to some radios.

**Comment by cpwilson** [comment] 2015-08-17 09:04
It's the JR module version.    I am aware that the high power modules can cause RFI issues with the Taranis but this usually shows as the classic speaker buzz which have always experienced.    I did some more testing and I get random haptic only on 2.1.1 firmware.    Reverted back to 2.0.17 and all is well again as it has been for some time so it's not hardware related.

**Comment by kilrah** [comment] 2015-08-17 09:42
Did you reflash the same 2.1.1 file you had before? Due to your screen issue I wonder if it could be corrupted, might be worth redownloading. What exact filename are you flashing (so I know the options)?

**Comment by cpwilson** [comment] 2015-08-17 10:59
I have updated the firmware 2 times via companion and downloaded firmware file on each occasion and also tried via the bootloader on the TX itself but still have the same results.   Filename is opentx-taranisplus-en.bin.

**Comment by kilrah** [comment] 2015-08-17 11:07
OK.
Could you post your eeprom (upload to some file host and paste link here) and detail what firmware version and settings you're using on the EZUHF?
I don't see what could be the cause but I'll have access to a JR EZUHF in a few days and can try to reproduce.

**Comment by cpwilson** [comment] 2015-08-17 11:25
I'm running firmware V1.52 on the EZUHF module with stock settings apart from enabling 430-450MHz Extreme Hopping frequency mode.   Also running the Diamond SRH 771 antenna.  I have just checked and I did not take a full backup of the eeprom when running V2.1.1, only have individual model backups,  and have now reverted it all back to V2.0.17.     If it's of help to you I could drop 2.1.1 back on and copy the eeprom file off once done.

**Comment by kilrah** [comment] 2015-08-17 11:49
The individual backup of the affected model you have should be enough for now, I'll get back to you if I need more.

**Comment by cpwilson** [comment] 2015-08-17 12:56
bin file for the model is here:

https://drive.google.com/folderview?id=0B_3ok934_pP5fkpiU3FMcm9lLUFRbnMzdFdHM2s1eUdGVXN0dGREZkhMX1ZrcU5lYU9mUUE&usp=sharing

**Comment by kilrah** [comment] 2015-08-18 20:46
This model has the internal module ON in D16 mode and the external one OFF so I doubt it is the correct file...

**Comment by cpwilson** [comment] 2015-08-18 23:15
Hi Kilrah, it's showing correctly in companion and was definitely working on the TX when I did the backup.   Here is the screenshot of companion of the bin file.

I also tried creating a new model and on disabling the internal module and enabling the external module the random haptic started so it's nothing on the model setup.

![rv jet](https://cloud.githubusercontent.com/assets/13822581/9345284/3b2ea634-4607-11e5-8bab-ec7e5b8da01e.jpg)

**Comment by bugobe** [comment] 2015-08-23 05:54
I just purchased a Taranis Plus along with the EZUHF JR module today. I updated everything to the latest firmware. 2.1.1 on the Taranis and 1.52 on the EZUHF. I have the same problem with the random haptic pulses. I'll try downgrading the firmware and see if it makes a difference.

**Comment by cpwilson** [comment] 2015-08-23 12:31
Would be interesting to see if the problem goes away for you if you downgrade to firmware v2.0.17.
Keep us posted on your results.

**Comment by bugobe** [comment] 2015-08-23 16:29
After downgrading to v2.0.17 the problem is gone. I verified that the module is working and communicating with the RX in both fw versions.

**Comment by kilrah** [comment] 2015-08-23 18:30
OK, I got my EzUHF back, updated it to 1.52 and can't seem to reproduce.

Can you detail the conditions? low and/or high power? Does it happen every 5 seconds or once an hour? Does it happen the same whether the receiver is powered or not? @cpwilson when did you buy your module?

**Comment by bugobe** [comment] 2015-08-23 19:24
Both the Taranis and module are new as of yesterday. It happens on low
power for me only when the module is powered and haptic is turned on. If
haptic is set to "quite" it's fine. It pulses probably once every few
seconds. It almost made me think of Morse code when it first started.

**Comment by kilrah** [comment] 2015-08-23 20:11
OK. 

Do you have the latest 2.1 sound packs (Aug. 7)? When you do, do you have any sound playing with the vibration?

**Comment by bugobe** [comment] 2015-08-23 20:16
That I'm not sure of, all I did was install the 2.1.1 firmware and then
found the problem and then downgraded to 2.0.1 7. I will have to do a
little research on how to upgrade the voice pack but I will post back once
I've tested it.

**Comment by kilrah** [comment] 2015-08-23 20:17
OK. Then note that 2.0 and 2.1 need different sound packs.

**Comment by bugobe** [comment] 2015-08-23 21:12
Ok, I updated the voice pack to Amber v2.1 for the Taranis Plus. Now, with
the EZUHF on low power I can't get it to vibrate but as soon as I flip to
high it vibrates and then it randomly vibrates about 1-2 times every 30
seconds. It also vibrates once on the switch flip back to low power but
thats it once its on low power.

**Comment by cpwilson** [comment] 2015-08-23 21:22
My module is about 7 months old and is definitely running Version: 1.52 (6), just double checked.
It's been in my Taranis Plus, on the following firmware revisions with no problems at all.
FRSky V2.0.9.2
OpenTX V2.0.15
OpenTX V2.0.17

I updated to V2.1.1 firmware, as well as installing the sound pack and get the random haptic on both high and low power, but less frequent on low power.
As soon as I revert back to V2.0.17 and restore model all is fine again.

Having tried out all the new telemetry on 2.1.1 I would love to stay on it but can't as I need to run the EZUHF for some of my FPV models.

**Comment by kilrah** [comment] 2015-08-23 21:23
OK, I take it you have no sound at the same time than the vibration then.

**Comment by bugobe** [comment] 2015-08-23 21:27
Oh sorry forgot about that. No sound, you can hear a little static if you
hold the TX close to your ear.  But nothing coinciding with the haptic.

**Comment by cpwilson** [comment] 2015-08-24 09:21
Same here, no sound just the vibrate and not using haptic for anything in the model setup.

**Comment by johnho100** [comment] 2015-09-01 15:18
Hi! I am having the same problem after updating to 2.1.1 firmware, I am getting random haptic feedbacks when I turn on my Ezuhf JR module. I also tested an Openlrs JR module, same issue. The haptic feedbacks happen randomly when no buttons or sticks are moved. I am able to repeatably "trigger" an abnormal haptic feedback when I press the ENT button (happens only if the LED backlight is off). 

I flashed back to 2.1.0 firmware, the problem disappeared. It seems the issue is caused by changes in 2.1.1 firmware only.

**Comment by GRCT42** [comment] 2015-09-09 02:51
I have the same problem as you guys. This is very frustrating so i just set it to quiet mode. Hopefully it will be resolved in a Firmware fix!!

**Comment by bsongis** [comment] 2015-09-09 05:13
@opentx/commiters Who has this module? We need to do the dichotomy and find which is the wrong commit!

**Comment by bsongis** [comment] 2015-09-09 05:27
Unless anybody here is ready to test firmwares I would send to him. If yes please contact me by email.

**Comment by GRCT42** [comment] 2015-09-09 12:07
I have the JR Module in a Taranis Plus. I have saved a copy of my Radio .Bin file if you need it.

I have the same problem as (bugobe )"Ok, I updated the voice pack to Amber v2.1 for the Taranis Plus. Now, with the EZUHF on low power I can't get it to vibrate but as soon as I flip to
high it vibrates and then it randomly vibrates about 1-2 times every 30
seconds. It also vibrates once on the switch flip back to low power but
that's it once its on low power."

Any help appreciated.

**Comment by kilrah** [comment] 2015-09-09 12:08
> @opentx/commiters Who has this module? 

I have one, but unable to reproduce...

**Comment by GRCT42** [comment] 2015-09-09 12:12
AsI stated in the forum, I have the JR Module in a Taranis Plus. I have saved a copy of my Radio .Bin file if you need it.I have the same problem as (bugobe )"Ok, I updated the voice pack to Amber v2.1 for the Taranis Plus. Now, with the EZUHF on low power I can't get it to vibrate but as soon as I flip to
high it vibrates and then it randomly vibrates about 1-2 times every 30
seconds. It also vibrates once on the switch flip back to low power but
that's it once its on low power."Any help appreciated.
 K. Pike 


     On Wednesday, September 9, 2015 2:58 AM, Bertrand Songis <notifications@github.com> wrote:
   

 Unless anybody here is ready to test firmwares I would send to him. If yes please contact me by email.—

**Comment by bsongis** [comment] 2015-09-09 13:24
Would it be possible that a signal comes to the module (heartbit PIN) and OpenTX thinks it is a trainer/trainee connection? In this case it would bzzz since we added this bzzz in 2.1.1

**Comment by kilrah** [comment] 2015-09-09 15:22
I thought about that but then the trainer found/lost sounds would play (checked they had the latest pack). 

But now someone made an interesting suggestion, the UHF could send noise into the analog path and cause the "center beep" to trigger. 

Can you look in the analog diag page if you have a big difference in "jumpiness" of the values with the UHF module on and off, and report what settings you have for the center beep?

**Comment by bsongis** [comment] 2015-09-09 15:33
Interesting, the user could try to "de-calibrate its sticks" to see if the bzz is done

**Comment by cpwilson** [comment] 2015-09-12 11:10
Hi, My module is the EZUHF.

I have tried de calibrating the sticks by doing a reset and not going through the calibration procedure and I can confirm the random haptic is still present on 2.1.1 and 2.1.3 firmware versions.
When I set haptic to Quiet then the issues goes away but when it's enabled random haptic is back.

Have also disabled the external module and there is no noticeable difference with the fluctuations in the channel monitor page with the module on or off.

I get random haptic when module is in the high or low power setting but less frequent in the low power setting.

**Comment by johnho100** [comment] 2015-09-17 08:49
Hi, I confirm I am still experiencing the same issue after flashing to 2.1.3 , when I switched back to 2.1.0 , the problem disappeared.

**Comment by flythai** [comment] 2015-09-21 15:14
I, i have the same problem, i no have previous versions open TX firmware, and i ask if i disable the haptic function have any problem.? Many thanks.

**Comment by er9xuser** [comment] 2015-09-22 09:17
Hi. I've the same problem (random vibrations) on Taranis Plus and openTx v2.1.3 but I'm using RLink UHF connected to pins for JR module.

**Comment by bsongis** [comment] 2015-10-13 13:17
Did someone check with our latest nightly builds? We have found 2 major bugs recently. It would be nice it is a side effect...

**Comment by cpwilson** [comment] 2015-10-13 23:07
HI, I have just tried 2.1.4N488 build on my Taranis Plus with the EZUHF module and unfortunately the Random Haptic is still present.   As such I'm sadly holding off upgrading from 2.0.17 until a fix is sorted as I use the EZHUF on my main model.

**Comment by cpwilson** [comment] 2015-10-13 23:10
I may be wrong but the random haptic does not seem as bad, less often, as it was in 2.1.3.

**Comment by projectkk2glider** [comment] 2015-10-19 17:36
Lets get some additional information:

Affected users please do this test:
* as reported when Haptic is set to `Quiet` this issue does not appear.
* set Haptic to `Alarm`, does the issue appear? If not then continue.
* set Haptic to `Nokey`, does the issue appear? If not then continue.
* set Haptic to `All`, does the issue appear?

More questions for affected users:
* what is the pattern of haptic, only one short vibration or several short vibration pulses?
* what is your setting for `Beep mode`?
* do you have files `trainko.wav` and `trainok.wav` on the SD card in `SOUNDS/en/SYSTEM`?

My bet is `AUDIO_TRAINER_LOST()` and `AUDIO_TRAINER_BACK()` because at least Kilrah's sound pack for 2.1 does not contain `trainko.wav` and `trainok.wav` files.

We also saw in #2913 that the trainer input detection is not working correctly (reported to be circuit problem) and it might be floating and affected by high RF levels.

**Comment by flythai** [comment] 2015-10-19 17:57
For me only in quiet mode no have vibrations, another all modes i have vibrations.
If i put haptic to alarm-nokey-or all, sometimes i have 1 short vibration and another times i have 2 sorts vibrations.
I no have the files trainko on the sdcard.
My settings for Beep mode is Nokey.

**Comment by projectkk2glider** [comment] 2015-10-19 18:09
@flythai please create trainko.wav and trainok.wav files (use any other file, copy, rename) and tell us if it plays when you get the random haptic vibration.

**Comment by flythai** [comment] 2015-10-19 18:14
Give-me 30 minutes and i tell you, any wav file, i rename.

**Comment by flythai** [comment] 2015-10-19 18:45
I again, i just make the experience, before the experience i just have haptic vibrations when i put the jr uhf on HI mode.
I rename the 2 files, and when i put ALARME and the jr module on HI mode, i have the same vibrations with sound wav.

**Comment by projectkk2glider** [comment] 2015-10-19 18:49
Thanks, that confirms it.

**Comment by flythai** [comment] 2015-10-19 18:51
This is have any solution ?
Or if i Put on Quiet mode i no have problems ?

**Comment by projectkk2glider** [comment] 2015-10-19 19:03
Now that we determined where the problem is, we will prepare a fix for it.  You  will be able to see the progress if you follow this issue.

**Comment by flythai** [comment] 2015-10-19 19:08
I follow this from begining, i hope you guys can fix this problem, i pray.

**Comment by kilrah** [comment] 2015-10-19 19:23
Meh, I asked 2 months ago of they were using the latest and full sound packs because it's the first thing that I thought was causing it. Answer was yes...

ImmersionRC have apparently changed something on their module though, because mine does not put anything on the affected pin.

**Comment by bsongis** [comment] 2015-10-19 19:28
I guess it's only an '''else''' missing in trainer_driver.cpp

**Comment by bsongis** [comment] 2015-10-25 14:41
Latest nightly builds now include the fix (I launched the last one this morning). I will need tests before closing the issue.

**Comment by flythai** [comment] 2015-10-25 18:30
Great bsongis, i hope result your tests

**Comment by bsongis** [comment] 2015-10-25 18:35
Did you try? I don't have the module myself ...

**Comment by flythai** [comment] 2015-10-25 18:40
I no see the new firmware update to try

**Comment by bsongis** [comment] 2015-10-25 18:46
You have to download Companion from nightly builds here:
http://downloads-21.open-tx.org/nightly/companion/
Then you enable firmware nightly builds in Preferences and download the latest nightly built firmware.

**Comment by flythai** [comment] 2015-10-25 18:58
The version of companion is 2.1.5n504.exe Correct ?
And the firmware version is -i686.rpm correct ?

**Comment by projectkk2glider** [comment] 2015-10-25 19:00
>The version of companion is 2.1.5n504.exe Correct ?

Correct

>The version of companion is 2.1.5n504.exe Correct ?

No that is Companion for RedHat based Linux distributions. You will download the radio firmware with the Companion2.1.5n504.exe when you install it and then make sure you enable `firmware nightly builds` in Preferences and then download the latest nightly built firmware.

**Comment by flythai** [comment] 2015-10-25 19:13
Inside companion where i can download the firmware nightly builds ?
I just check on firmware nightly builds on preferences.

**Comment by projectkk2glider** [comment] 2015-10-25 19:16
Now just got to `Download...` menu option and then `Check for updates`

**Comment by flythai** [comment] 2015-10-25 19:21
Ok, is done, but the haptic continues.

**Comment by flythai** [comment] 2015-10-25 19:21
on hi mode

**Comment by projectkk2glider** [comment] 2015-10-25 19:24
Are you sure you have 2.1.4N504 installed, to check: on the radio long press MENU then PAGE until you get to the version screen.

**Comment by flythai** [comment] 2015-10-25 19:26
i can take a photo and show here, give me only some minutes

**Comment by flythai** [comment] 2015-10-25 19:36
![img_0181](https://cloud.githubusercontent.com/assets/14582101/10717427/9ab4b350-7b4f-11e5-93e0-7971759ec832.JPG)

**Comment by projectkk2glider** [comment] 2015-10-25 19:40
Ok, thanks for testing. So this issue is still not solved!

**Comment by kilrah** [comment] 2015-10-25 19:41
Would really need someone with an oscilloscope to check if the module puts out something on pin 2.

**Comment by flythai** [comment] 2015-10-25 19:44
Sorry, i no have oscilloscope.

**Comment by bsongis** [comment] 2015-10-25 20:38
And the wav for trainer is played??? It means it's not the heartbeat PIN!

**Comment by bsongis** [comment] 2015-10-25 20:41
Unless it's serial data which comes on the heartbeat PIN, let's try ...

**Comment by bsongis** [comment] 2015-10-25 21:14
A new round of "forced" nightly builds is available, would you do another test? Thanks!

**Comment by flythai** [comment] 2015-10-25 22:58
Only tomorrown, time to go sleep.

**Comment by flythai** [comment] 2015-10-26 09:27
I guys, with the last nightly build is not working without vibration on Hi mode.
![img_0182](https://cloud.githubusercontent.com/assets/14582101/10725406/c7cdd92e-7bc3-11e5-94a4-631250178b4b.JPG)

**Comment by bsongis** [comment] 2015-10-26 16:38
What do you mean, you still have the haptic? And trainer sound file played as well?

**Comment by flythai** [comment] 2015-10-26 16:41
Yes, with this last nightly build im still continue with haptic vibrations when i selected on Ezuhf jr module Hi.

**Comment by bsongis** [comment] 2015-10-26 16:45
What are your Trainer settings? (in Model Setup)

**Comment by flythai** [comment] 2015-10-26 16:48
My trainer is selected on -Master/jack

**Comment by bsongis** [comment] 2015-10-26 17:17
Are your trainko.wav and trainok.wav files played as well?

**Comment by flythai** [comment] 2015-10-26 17:22
yes, at same time with vibrations

**Comment by bsongis** [comment] 2015-10-26 17:33
Now would you select another setting, for example "Slave"

**Comment by flythai** [comment] 2015-10-26 17:41
Ok, i just try the option ''slave'' and another other options, and no vibrations and no sound.
Only make vibrations and play sound on Master/Jack position

**Comment by bsongis** [comment] 2015-10-26 17:45
Interesting! @projectkk2glider @kilrah what do you think of this?

**Comment by kilrah** [comment] 2015-10-26 17:56
Again a scope would be needed... But I'm still pretty sure the module just sends whatever kind of pulses or serial data that randomly happen to be considered valid PPM for a while, then invalid, valid again...

**Comment by flythai** [comment] 2015-10-26 18:00
Al this is very strange, because only i receive vibrations on HI mode (500mw) and on LO mode (200mw) notting happen.

**Comment by projectkk2glider** [comment] 2015-10-26 18:07
It can still be the RF coupling that is causing the ghost PPM signal. The fact that it happens more frequently in high power mode is the clue. I think we need to make the trainer signal validity algorithm more robust:
* more than N valid PPM pulses in a row have to be received before the valid signal is declared
* more than M invalid PPM pulses in a row have to received before the signal is declared invalid

**Comment by flythai** [comment] 2015-10-26 18:09
I have also a ezuhf 4ch lite, and when i go make a flight and the quadcopter still about 1 km distance i switch to HI mode, and rssi don´t move to low, the values still the same.

**Comment by bsongis** [comment] 2015-10-26 18:10
Also we could avoid to capture the trainer signal if the pin detect is off

**Comment by bsongis** [comment] 2015-10-26 18:34
A new nightly build is ready, would you check? The trainer icon will be visible only if there is valid PPM input

**Comment by flythai** [comment] 2015-10-26 18:43
Give me some minuts to try

**Comment by flythai** [comment] 2015-10-26 19:06
Ok, now i no receive any vibrations and no play the 2 wav files, but i no see any icon.

**Comment by kilrah** [comment] 2015-10-26 19:33
Which would be normal as you have no trainer signal connected...

**Comment by flythai** [comment] 2015-10-26 19:36
Ok, now this issue is solved ?

**Comment by bsongis** [comment] 2015-10-26 20:06
I think so

**Closed by bsongis** 2015-10-26 20:06 UTC
Labels: Bug, Radio Firmware

**Comment by GRCT42** [comment] 2015-10-29 00:47
Thx! To all who participated to resolve this issue!
Great Job...

**Comment by clobybar** [comment] 2015-10-30 03:35
Working great for me too. Thank you very much.
