### ISSUE TITLE
Silence from the vario

### ISSUE THREAD

**Issue by BarryCole** [opentx/opentx#2213] opened 2015-04-21 09:11 UTC
Is it possible to get the vario to be silent, during the level flight phase.

Eg between the 1.0 and -1.0 settings.

Thanks if you can.

BC

**Comment by jtaylor2** [comment] 2015-04-21 10:28
You don't say what version of OpenTX or which transmitter but the answer is yes.  There is already an issue open ( https://github.com/opentx/opentx/issues/2076 ) to make it configurable in 2.1, but it can be done in 2.x with logical switches:

L1 a>x vspd 0.3 m/s and (a switch if wanted)
L2 a<x vspd -0.4 m/s and (a switch if wanted)

SF1 L1 vario
SF2 L2 vario

or only one if the values needed are the same

L1 |a|>x vspd 0.3 m/s
SF1 L1 vario

Jim

Duplicate of 2076

**Closed by jtaylor2** 2015-04-21 10:28 UTC
