### ISSUE TITLE
Companion 2.2.0 crash to desktop

### ISSUE THREAD

**Issue by kashido** [opentx/opentx#5081] opened 2017-07-07 00:00 UTC
Freshly installed on x64 Windows 7

Here's the installation log,
https://pastebin.com/d8LbKvHv
Here's the crash details,
https://pastebin.com/CGCpD62C

edit: pardon my hyperlink fail, I'm working on fixing that. copy/paste ftw

**Comment by kashido** [comment] 2017-07-07 00:06
When I ran companion 2.1.9 I got a message, Thanks for installing 2.2.0, so I tried to launch 2.2.0 again, and it worked.

**Comment by projectkk2glider** [comment] 2017-07-24 15:31
I bet this is duplicate of #5076

**Comment by kilrah** [comment] 2017-11-08 12:12
Duplicate

**Closed as completed by kilrah** 2017-11-08 12:12 UTC
Labels: Bug, Companion
