### ISSUE TITLE
Show receiver number of each model in Companion in Model select screen

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6262] opened 2018-12-08 08:37 UTC
To make sure a receiver # is not used twice it's hard to check.
It would be really nice if, in Companion models view, the receiver # would be shown.
Maybe in red if it is used more than once

**Comment by elecpower** [comment] 2018-12-29 11:12
Duplicate of #5088

**Closed as completed by elecpower** 2018-12-29 11:12 UTC
