### ISSUE TITLE
Companion 2.2 9XR-PRO

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4925] opened 2017-05-13 06:25 UTC
Hello,

version Opentx 2.2.0N371 (both companion and radio 9XR-PRO)

"Boot loader v1.3 Ready" displayed at radio startup with Yaw and Ail trim activated.
then
"Connecting.." when usb cable is plugged

In companion, tring to read/write Models and Settings from/to radio fails with error message
"Executable C:\.....\sam-ba.exe not found"

Thanks
Benoit

**Comment by schwabe** [comment] 2017-05-28 15:41
Duplicate of #4804

**Closed as completed by schwabe** 2017-05-28 15:41 UTC
