### ISSUE TITLE
Radio transfer improvement

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#4679] opened 2017-03-24 06:37 UTC
When transferring models to radios with different hardware layout,  the current interface does not offer flexibility (and since I'm exchanging between a fully loaded x9e and an x7, I know it first hand :D)

The proposal is to have a kind of two columns transfer map where you have on one side the 'from" radio switches and sliders, and the other the target one, and you could assign what goes where (and possibly save that map for future usage).

It could handle the following options:
- not mapiing a switch (but transfer the rest anyway)
- map several switches to one

**Comment by kilrah** [comment] 2017-03-24 07:56
Duplicate of #4264

**Closed by kilrah** 2017-03-24 07:56 UTC
Labels: Companion, enhancement, Undecided
