### ISSUE TITLE
Update SPORT devices

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#1599] opened 2014-08-10 17:14 UTC
Discussion about the best way to implement SPORT devices update. I don't have the protocol right now.

**Comment by fraternl** [comment] 2015-01-13 02:07
From a user's viewpoint this flashing using the bootloader feels correct and confirms you're doing something special.
Documentation is already needed (the reverse polarity of the cable)

**Comment by MikeBland** [comment] 2015-01-13 08:45
I wrote this last August (2014):
http://openrcforums.com/forum/viewtopic.php?f=52&t=2914&start=30#p84911

**Comment by bsongis** [comment] 2015-01-13 18:44
We have to release OpenTX 2.0.15 tonight, this one will be added to 2.0.15 as soon as 2.0.15 is ready. Thanks Mike for the code.

**Comment by rc-smurf** [comment] 2015-01-14 08:37
Will this functionality be able to upgrade the internal module as well?

**Comment by er9xuser** [comment] 2015-01-21 07:52
@rc-smurf yes you can. I've flashed internal module yesterday with ersky9x fw for taranis. It's easy.

**Comment by fraternl** [comment] 2015-01-23 12:36
Issue 2001 got closed because it was supposedly a duplicate of this one.
This is not true.
"Issue 2001" is about updating the parameters of S-Port devices. NOT updating the firmware.
It was more of a reminder for Mike Blandford as he more or less proposed to do it (if he finds the time)

https://github.com/opentx/opentx/issues/2001

**Comment by kilrah** [comment] 2015-01-24 03:05
It goes together, we'll just integrate Mike's code with the functionality it has.

**Comment by bsongis** [comment] 2015-02-06 16:08
I will integrate Mike's code into 'master', but I would like to have this version in 'next'

**Comment by janekx** [comment] 2015-02-09 07:23
I am ready to test :)

**Comment by projectkk2glider** [comment] 2015-02-21 16:56
Except for one comment, the code looks good to the eye.

**Comment by kilrah** [comment] 2015-02-23 14:52
Not working though. 
Serial data looks inverted (need to check Mike's stuff to see if an inverter was required but I don't remember it), and I only see (broken) 2-byte packets sent during discovery instead of 10-byte standard SPORT packets.

**Comment by MikeBland** [comment] 2015-02-23 16:09
Could be caused by running in the wrong environment, i.e. fully operating Tx instead of maintenance mode where only the update code is running. I can't see any maintenance mode only code.
For something like firmware update I would strongly recommend running only the code needed to minimise any possibility of the update failing.

NOTE: I built an openTx.bin from the master branch with "maintenance mode" in it and it all worked. That's the code is passed over.

Since the SPort receives what is sent, receive data is probably shutting down the transmit operation.

I have updated my code to the following so I can use the SPort for a different purpose. It turns the receive off while transmitting, and also only actions the TC interrupt if it is enabled.

void x9dSPortTxStart( uint8_t *buffer, uint32_t count )
{
	SportTx.ptr = buffer ;
	SportTx.count = count ;
	GPIOD->BSRRL = 0x0010 ;		// output enable
	USART2->CR1 &= ~USART_CR1_RE ; // Turn off receiver
	USART2->CR1 |= USART_CR1_TXEIE ;
}

extern "C" void USART2_IRQHandler()
{
  uint32_t status;
  uint8_t data;

  status = USART2->SR ;

	if ( status & USART_SR_TXE )
	{
		if ( SportTx.count )
		{
			USART2->DR = *SportTx.ptr++ ;
			if ( --SportTx.count == 0 )
			{
				USART2->CR1 &= ~USART_CR1_TXEIE ;	// Stop Tx interrupt
				USART2->CR1 |= USART_CR1_TCIE ;	// Enable complete interrupt
			}
		}
	}
	
	if ( ( status & USART_SR_TC ) && (USART2->CR1 & USART_CR1_TCIE ) )
	{
		USART2->CR1 &= ~USART_CR1_TCIE ;	// Stop Complete interrupt
		GPIOD->BSRRH = 0x0010 ;		// output disable
		USART2->CR1 |= USART_CR1_RE ;
  	while (status & (USART_FLAG_RXNE))
		{
    	status = USART2->DR;
    	status = USART2->SR ;
		}
	}

  while (status & (USART_FLAG_RXNE | USART_FLAG_ERRORS))
	{
    data = USART2->DR;

    if (!(status & USART_FLAG_ERRORS))
		{
			put_fifo64( &Telemetry_fifo, data ) ;
		}
		else
		{
			USART_ERRORS += 1 ;
			if ( status & USART_FLAG_ORE )
			{
				USART_ORE += 1 ;
			}
			if ( status & USART_FLAG_NE )
			{
				USART_NE += 1 ;
			}
			if ( status & USART_FLAG_FE )
			{
				USART_FE += 1 ;
			}
			if ( status & USART_FLAG_PE )
			{
				USART_PE += 1 ;
			}
		}
    status = USART2->SR ;
  }
}

This works reliably on a running Tx as well as SPort update.

Mike.

**Comment by rc-smurf** [comment] 2015-03-19 09:56
Is this going into 2.0.16 as well? Issue closed but code only committed to next...

**Comment by janekx** [comment] 2015-03-23 16:23
I suggest to change the order of the menu, first external and then internal flash command .... 
Most time will be flashed external devices then internal XJT and in case of playing around not possible to bad flash internal module. Is there some protection to not flash FW to not corresponding device?

**Comment by MikeBland** [comment] 2015-03-23 17:27
I'm getting a problem on the 9XR-PRO where the update fails sometimes. I've tracked this down to, most likely, the SPort output not being disabled soon enough after the end of transmission. Just occasionally it occurs much later than at other times. Also the updating device responds very quickly, sometimes as soon as around 18uS after the end of the stop bit last sent to it.
While running this update code you MUST make sure nothing holds the "end of transmission" interrupt off for any length of time.
I can see, on my 'scope, an occurance where the first start bit from the updating device has been cut because the output enable signal was still active.

Mike.

**Comment by projectkk2glider** [comment] 2015-03-23 17:47
I am reopening this ticket, two reasons:
* Mike's comment above (end of transmission bug)
* the need to include this in OpenTX 2.0.16

**Comment by bsongis** [comment] 2015-03-23 18:08
About the need to include this in 2.0.16, we are in the process of releasing an alpha for 2.1!

**Comment by kilrah** [comment] 2015-03-24 07:13
Yes but there are some people who will never want to update to 2.1 as there will be very big changes.

On 2.1 I have updated things a couple of dozen times and never had a failure. I however started a port to master and there I have the same issues as Mike, and what I saw with the LA could match (when it fails the radio is the last to send a packet, and never receives an answer from the device i.e. maybe the device is trying to talk but the line level is still being forced by the radio, so it gives up).

**Comment by MikeBland** [comment] 2015-03-24 11:57
I found my problem on the 'PRO, the 5mS timer interrupt was a higher priority than the end of transmission interrupt. I changed the 5mS to be lower priority and all is fine. I can see the transfer is now exact on my 'scope. I did 8 firmware updates with no failures.
On ersky9x, I have set most interrupts to be level 4, one or two are set lower. I now have the 5mS timer set at 3, needed to be higher than the general 4 for the audio output, the end of transmission is 2, and I have a software driven serial driver, to handle non-inverted serial on pin 5 of the module connector with the interrupt level at 1 as this is absolutely critical. It shouldn't be used with the updating code so shouldn't cause any problems.

Adding this feature as "maintenance mode" (trims held apart at power on) is quick and easy, only takes 10 minutes to do the changes.

Mike.

**Comment by griebd** [comment] 2015-03-24 12:08
> Adding this feature as "maintenance mode" (trims held apart at power on) is quick and easy, only
> takes 10 minutes to do the changes.

I do agree with @MikeBland on that.... Just my 2 cents... :wink:

**Comment by janekx** [comment] 2015-03-24 12:19
I agree for separate "maintenance mode". Flashing should be most safe how much is possible so OS  independent.

**Comment by neckisch** [comment] 2015-07-06 06:04
as there is a new etsi norm for european users to be adhered, the maintenance mode becomes more interesting. i want to downgrade my taranis back to the non EU tx module firmware due to receiver compatibility issues. therefore it would be really helpful to have a feature like this in openTX.
So why not doing it as in ErSky and lets see what users will say. if it is to confusing, lets implement another way.

**Comment by seancull** [comment] 2015-07-06 06:15
I flashed some receivers over the weekend and had to revert to an earlier version of the FRSky firmware tool that I was fortunate enough to have saved. The posted one did not work - not red progress "LEDs" in the UI and no response from the receiver.  It would be great to have this although I would agree with the comments about the whole firmware thing being very confusing to normal users.

**Comment by kilrah** [comment] 2015-07-06 07:20
Why is this still open? Smart port device flashing is already in 2.1 that is about to be released.

**Closed by kilrah** 2015-07-06 07:20 UTC
Labels: enhancement, Radio Firmware

**Comment by fraternl** [comment] 2015-07-07 08:13
Wasn't clear to me either...
I thought you might still want to move it to the startup code (trims held apart) for stability reasons.
But I've seen it in the SD card manager.
I might need it soon to retro-flash an X4R-receiver I am considering to buy

**Comment by tonimerlot** [comment] 2016-02-21 12:22
Sorry but not understand if It is programmed added firmware upgrade of SPORT devices on OpenTX 2.0 branch?

**Comment by janekx** [comment] 2016-02-21 13:02
No only 2.1

**Comment by MikeBland** [comment] 2016-02-21 14:13
For a straightforward build of openTx 2.0.x, I've posted some binaries I built that include "maintenance mode", together with the changed.added source files if you need to build openTx yourself. You may find them here: http://openrcforums.com/forum/viewtopic.php?f=45&t=6847&hilit=sport+device+updating
