### ISSUE TITLE
Horus hang up in Black Screen and  Blue Screen

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4036] opened 2016-11-17 23:52 UTC
If you choose Blue Background Screen in Telemetry, and go back in to the model sites to the mixer Site the Screen is blocking and show unclear colored screen, see pictures.

Also if you scroll through the Model Menus my system block 3 times during preparing a model, this evening. You need a very long Exit on Main switch.

Must be a big bug.

If you choose the Black Background in Telemetry the system hang up in the mixersite. in both problems you have to do a long switch off the main switch to exit.
![20161118_001215](https://cloud.githubusercontent.com/assets/22581690/20412753/eef224d2-ad28-11e6-8f9e-9eb932b094e9.jpg)
![20161118_001245](https://cloud.githubusercontent.com/assets/22581690/20412754/eef2c554-ad28-11e6-8aee-053a3fd4bd48.jpg)
![20161118_001251](https://cloud.githubusercontent.com/assets/22581690/20412755/eef41d64-ad28-11e6-8778-0ef06ba536f8.jpg)

**Comment by 3djc** [comment] 2016-11-18 06:20
Did you copy the whole SD card zip file ? It looks to me like you may have taken only the sounds and may be missing some files in the THEMES folder

**Comment by bsongis** [comment] 2016-11-18 06:49
@3djc do you know if is it reproductible?

**Comment by 3djc** [comment] 2016-11-18 06:50
I cannot reproduce this

**Comment by bsongis** [comment] 2016-11-18 06:51
It would be interesting to have the SD contents from @Githubbachelor to be able to reproduce it, we miss some check somewhere

**Comment by 3djc** [comment] 2016-11-18 06:53
It looks to me like drawing outside of the screen,, expereienced that a few times during the wizard handler dev. I'm having a look at the dark blue today, it is broken in many places

**Comment by bsongis** [comment] 2016-11-18 06:56
@3djc as soon as you find a way to reproduce this problem of drawing outside the screen please tell-me, I think we should fix it

**Comment by Githubbachelor** [comment] 2016-11-18 07:22
1. Yes I have the actuall Card. You can reproduce the problem with blue screen. 

2. That the system is hanging sometimes, maybe the system is too slow????? My Model Programm is big, with sounds and Infos. 
I try to load the system Sound. After rest of card
[SYSTEM.zip](https://github.com/opentx/opentx/files/599263/SYSTEM.zip)

[SD Karte Anlage Horus letzte version aktuell.zip](https://github.com/opentx/opentx/files/599265/SD.Karte.Anlage.Horus.letzte.version.aktuell.zip)

**Comment by Githubbachelor** [comment] 2016-11-18 07:23
I can answer more later at 5h pm earliest

**Comment by 3djc** [comment] 2016-11-18 07:41
Tested all the 14 models, cannot reproduce

**Comment by Githubbachelor** [comment] 2016-11-18 07:44
Ok I will try again in the afternoon. I got a new Horus 2 days ago. The first Horus had a TX damage and was changed now Albert Lacroix.

**Comment by 3djc** [comment] 2016-11-18 07:45
can you tell me what model it was ?

**Comment by Githubbachelor** [comment] 2016-11-18 07:46
It was Polizia X8 under Heli. I dont know the Modelnumber

**Comment by 3djc** [comment] 2016-11-18 07:47
![image](https://cloud.githubusercontent.com/assets/5167938/20422593/a47920ac-ad6b-11e6-9757-f6f3a5eb4e48.png)
???

**Comment by Githubbachelor** [comment] 2016-11-18 07:51
Moment
[SYSTEM.zip](https://github.com/opentx/opentx/files/599311/SYSTEM.zip)
[Archive.zip](https://github.com/opentx/opentx/files/599312/Archive.zip)

try this. Sorry I didnt save that night. That is actual

**Comment by Githubbachelor** [comment] 2016-11-18 07:51
Model Polizia Heli

**Comment by Githubbachelor** [comment] 2016-11-18 07:52
I must go now

**Comment by 3djc** [comment] 2016-11-18 07:55
Right, this model segfault with blue

**Comment by 3djc** [comment] 2016-11-18 08:12
ok, actually quite difficult to reproduce, but there are issues switching from default to dark blue. Here is an example of the wrong mask been loaded (bellow ch3, this is not the right icon)

![image](https://cloud.githubusercontent.com/assets/5167938/20423171/24274966-ad6f-11e6-9b7e-aa5462d2b078.png)

**Comment by 3djc** [comment] 2016-11-18 08:13
And this is when starting straight in blue

![image](https://cloud.githubusercontent.com/assets/5167938/20423192/432895fe-ad6f-11e6-993c-7561056d6054.png)

**Comment by 3djc** [comment] 2016-11-18 08:16
@bsongis , I may need some help here:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc8899700 (LWP 7564)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: Aucun fichier ou dossier de ce type.

**Comment by 3djc** [comment] 2016-11-18 08:17
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc8899700 (LWP 7564)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: Aucun fichier ou dossier de ce type.

**Comment by 3djc** [comment] 2016-11-18 08:26
ok, steps to reproduce:
1) create or load a model with a replace mixer
2) view the mixer either in blue or default
3) go back, load the other theme
4) go to view the mixer page
5) segfault

**Comment by 3djc** [comment] 2016-11-18 08:33
static const BitmapBuffer * mpx_mode[] = {
    mixerSetupAddBitmap,
    mixerSetupMultiBitmap,
    mixerSetupReplaceBitmap
  };

It is because of this static

**Comment by projectkk2glider** [comment] 2016-11-18 13:13
Perhaps while you at it, add a check that prevents writing/drawing outside the LCD buffer. This is already done on Taranis, but needs to be done for Horus and small pixel screen (ie sky9x).

**Comment by Githubbachelor** [comment] 2016-11-18 13:23
You have that problem if you switch through the Menu sites. If you switch to quick the Horus hang also up.

**Comment by 3djc** [comment] 2016-11-18 18:03
This issue will be fixed in the next nightly. In the interim, avoid changing theme ;)

**Closed by 3djc** 2016-11-18 18:03 UTC
Labels: Bug, Radio Firmware
