### ISSUE TITLE
X10S and Crossfire : Crossfire LUA not working

### ISSUE THREAD

**Issue by Barbaryann** [opentx/opentx#5316] opened 2017-10-31 19:54 UTC
Hello,
The Crossfire Lua to configurat the crossfire daosn't work with me.
CF Fw 2.11
OpenTX N417

**Comment by schwabe** [comment] 2017-10-31 20:53
Duplicate of #5315 (Same fundamental problem)

**Closed as completed by schwabe** 2017-10-31 20:53 UTC

**Comment by Barbaryann** [comment] 2017-10-31 20:58
thanks
