### ISSUE TITLE
Reversed trim on negative Input

### ISSUE THREAD

**Issue by seagovernor** [opentx/opentx#4261] opened 2017-01-20 11:22 UTC
I have noticed a reversed trim occurred in ver 2.1.9
When set negative weight of Ail Input and positive weight in Mixing, resulting in reversed trim.
But when set positive weight of Ail Input and negative weight in Mixing,it resulted in correct trim.

**Comment by 3djc** [comment] 2017-01-20 11:25
Working as intended I believe

**Comment by kilrah** [comment] 2017-01-20 11:40
Yep, documented and has been so since Inputs exist.

**Comment by projectkk2glider** [comment] 2017-01-20 11:43
Duplicate of #2958

**Closed by projectkk2glider** 2017-01-20 11:43 UTC

**Comment by seagovernor** [comment] 2017-01-20 16:38
I see, Thank you.
But is there any way to put positive value only, not allowed to put negative Input?
