### ISSUE TITLE
Losing audio while using the radio 9xr pro with open tx latest

### ISSUE THREAD

**Issue by Bogdanu2018** [opentx/opentx#5849] opened 2018-04-27 10:00 UTC
Hello people,

I'm recently experiencing problems with the audio from my radio 9xr PRO. I added the telemetry and RSSI alerts and now after few minutes after starting and using radio the sounds and alerts seems to stop working until I restart the radio and they work again for few minutes. 
I tried to format and reinstall everything even changed sound pack and SD card is different and new but the problem is still there.
I don't know what to do anymore so I hope someone can help here, I cannot enjoy my RSSI alerts is so sad, I bough telemetry receiver specially for that and now radio doesn't alert me when is low rssi.
How can i fix it ? Should I downgrade to other firmware ?

Thanks

**Comment by kilrah** [comment] 2018-04-27 11:08
Duplicate of #5824

**Closed as completed** 2018-04-27 11:08 UTC
