### ISSUE TITLE
FM sensor issue

### ISSUE THREAD

**Issue by RookFPV** [opentx/opentx#8089] opened 2020-11-12 15:17 UTC
Taranis x9d+SE (old)   /   OTX 2.3.10
Tbs Crossfire micro v1/   3.78
TBS crossfire nanoRX /   3.78
Kakute F7v1.5             /   BF 4.2.4

in OpenTx 2.3.10 the FM sensor does not work correct - it will show “---” in My radio why ?
Works fine with earlier version of OTX, will it work from 2.3.11?

**Comment by 3djc** [comment] 2020-11-12 15:20
There is no known issue around that, and since all the sensors are handled the same way, it seems unlikely that OpenTX is the cause of that

**Comment by RookFPV** [comment] 2020-11-12 15:29
TBS In his documentation he wrote "in OpenTx 2.3.10 the FM sensor does not work correct - it will show“ --- ”in your radio"
page 29 https://www.team-blacksheep.com/tbs-tracer-manual.pdf

**Comment by 3djc** [comment] 2020-11-12 15:44
I have sent questions to TBS, because no one (including themselves) ever reported that I think

**Comment by RookFPV** [comment] 2020-11-12 15:47
I figured out when I wanted to use "INAV lua" which needs an FM sensor. And I know that OTX worked properly in the earlier version. PS Thanks for the quick response.

**Comment by 3djc** [comment] 2020-11-12 15:47
I'm using iNav script with CRSF and 2.3.10 without issues

**Comment by RookFPV** [comment] 2020-11-12 15:49
I cannot use it properly due to a problem with the FM sensor after installing OTX 2.3.10
At the top, I described the hardware and firmware I have or do you have something completely different on which you check this sensor with OTX 2.3.10?

**Comment by 3djc** [comment] 2020-11-12 16:02
I have asked details to TBS, lets see what they say tomorow. I'm using iNav and I think a slightly different CRSF version, but a sensor should be a sensor

**Comment by kamik2** [comment] 2020-11-13 09:46
the note was written by me as i receiver many reports as mail and could create the behavior here. that's removed now

my testing setup (retested a few minute ago):

x9d+, colibri fc with BF 4.1.0, 
crossfire on 4.08 down to 4.00 and 3.78

- otx 2.3.10: fm == "---"
- otx 2.3.9: fm == "---"
- otx "tbs crsfshot version": fm == "sta" 

i also seen reports with frsky systems (r9 and xjt) on facebook with the exact same behavior.

**Comment by 3djc** [comment] 2020-11-13 09:49
Yes, I'm talking to Remo, we will investigate

**Comment by 3djc** [comment] 2020-11-13 10:32
The issue has been identified, a piece of code was deleted as part of another change. We need to understand why it was done at that time before a proper fix can be applied (but be assured that it will be fixed shortly)

**Closed as completed** 2020-11-14 12:28 UTC

**Comment by machadofelipe** [comment] 2020-11-17 14:37
Sorry guys, but it seems there is still something wrong, nightly 375 is always missing one letter for the flight modes. For instance, "OK" just shows "O" and "WAIT" shows "WAI".
@3djc I think you are cutting one digit out in the textLenght. Can you reopen the issue and check?

Thanks for the effort ;)

**Comment by 3djc** [comment] 2020-11-17 14:50
Well according to CRSF section of BF I should have : 
![image](https://user-images.githubusercontent.com/5167938/99404895-6c578500-28ec-11eb-8449-d5dff9dd5354.png)

and I have 
![image](https://user-images.githubusercontent.com/5167938/99405040-95781580-28ec-11eb-971b-0673c3fea988.png)
![image](https://user-images.githubusercontent.com/5167938/99405076-a0cb4100-28ec-11eb-808f-111f97ae0dc4.png)
![image](https://user-images.githubusercontent.com/5167938/99405114-acb70300-28ec-11eb-994d-5e9a1720807d.png)

**Comment by machadofelipe** [comment] 2020-11-17 14:55
I was testing with iNav, but in BF it seems that when it is disarmed, it also should have an "*" at the end. Check line 290 at https://github.com/betaflight/betaflight/blob/94cd6504722c7e39eee5bd2e1a41507a03ca561d/src/main/telemetry/crsf.c (not sure myselft).

**Comment by 3djc** [comment] 2020-11-17 15:02
Try tomorows nightly then

**Comment by machadofelipe** [comment] 2020-11-18 17:30
Thanks @3djc, just gave it a try and it seems to be perfect now ;)

**Comment by 3djc** [comment] 2020-11-18 17:31
Sweet
