### ISSUE TITLE
2.3.9 9xr-pro crash stays in safe mode after reboot

### ISSUE THREAD

**Issue by xxxFROSTxxx** [opentx/opentx#7810] opened 2020-07-10 03:42 UTC
When changing model external mode from ppm to xjt and then attempting to change to another mode reboots in safe mode. Unable to clear watchdog error. Safe mode problem persists after recycling power and removing battery with unexp.shtdown error. Turning on transmitter powers on immediately with no boot in safe mode. 

Flashed with generic 2.3.9 as well as heli same problem. 

when attempting to change mode in safemode watchdog reboot occurs guessing because SD card is disabled in safe mode...?

To restore flashed stock 9xr pro image and start over fresh opentx install. Will try nuking the models via USB and see if that fixes the constant safe mode.

**Comment by kilrah** [comment] 2020-07-10 06:33
Duplicate of https://github.com/opentx/opentx/issues/7810

**Closed as completed by kilrah** 2020-07-10 06:33 UTC

**Comment by xxxFROSTxxx** [comment] 2020-07-11 01:14
Duplicate of itself?   Can you share duplicate issue number as I have searched for the constant safe mode?

**Comment by kilrah** [comment] 2020-07-11 06:05
Bad link... https://github.com/opentx/opentx/issues/7594
