### ISSUE TITLE
TX antenna problem! [RTN] on Horus X12S when binding

### ISSUE THREAD

**Issue by mdpolasek** [opentx/opentx#5781] opened 2018-03-22 22:12 UTC
I have a Horus X12S flashed to  OpenTX 2.2.1RC99. When I try to bind a new model using the internal antenna I get an "Radio antenna defective" voice error message. The screen shows "TX antenna problem!". 

This looks to me like a software bug, because I don't have any issues with the internal antenna when using FrOS instead of OpenTX.

**Comment by 3djc** [comment] 2018-03-23 06:10
In all likelyhood, you really have an antenna issue, as you are the very first to report this.If there was a software bug, we should have had tons of report about it already.

As for FrOS,it could means they are not testing antenna status, or not with the value we use.

Could you go to Long Enter/Statistics/PgDn/PgDn in Analogs screen and let us know the values on the last line (RAS and XJTVER) ?

**Comment by mdpolasek** [comment] 2018-03-26 21:18
The value of RAS flips between 0 and 1, XJTVER is constantly 512. 

I bought the Horus in Switzerland and flashed it with the EUROPE FrSky bootloader. Can this be a reason for this issue?

**Comment by 3djc** [comment] 2018-03-27 05:05
No, EU-Lbt is no problem. Did you get those value with internal antenna selected ?

**Comment by mdpolasek** [comment] 2018-03-27 07:25
Yes, these are the values with the internal antenna. If I change it to "Ext + Int" I get slightly different values:
RAS 8, XJTVER is constantly 512.

**Comment by 3djc** [comment] 2018-03-27 07:32
Then it is very strange you get this alert, I guess your module gets defective only during bind process, very strange.

**Comment by martinpolasek** [comment] 2018-03-27 07:39
This is indeed strange. The funny thing is that everything works perfectly under FryOS - never had any issues with the antenna. And that I can bind the receiver under OpenTX using the „int + ext“ antenna setting.

Is there a way to debug this issue further?

**Comment by 3djc** [comment] 2018-03-27 07:44
The fact that you do not get an error with FrOS does not necessarly mean much, since we do not know if/how this error is handled by FrOS. If you get this with a brand new unprogrammed model, then that can only mean your hardware is somehow defective.

**Comment by 3djc** [comment] 2018-03-27 08:08
I may have an idea to diagnose further, do you have a firmware with lua option ? (luac also maybe ?) ?

**Comment by martinpolasek** [comment] 2018-03-27 10:49
I can flush Horus with a firmware with lua option enabled. This is not an issue.

**Comment by 3djc** [comment] 2018-03-27 10:58
Then do that, and put the content of the attached file in /SCRIPTS/MIXES, and 'activate' it using custom function screen
![image](https://user-images.githubusercontent.com/5167938/37963288-1e4e8aca-31be-11e8-8e38-cc507e973377.png)

![image](https://user-images.githubusercontent.com/5167938/37963334-41787d62-31be-11e8-87b8-4f462dd12b93.png)

Once it is done, discover sensors, you should have a new one called DBG. Do a special function that audio it's value every second.

![image](https://user-images.githubusercontent.com/5167938/37963402-6dbb1aa6-31be-11e8-9f40-8f93dbb9ab0f.png)

You should hear it say values between 1 and 5, something like that. Go to your binding process, and let us know what is the value told when binding

**Comment by martinpolasek** [comment] 2018-03-27 12:09
Thank you very much for your answer and the attached script. Will test it today evening and will let you know the result.

**Comment by mdpolasek** [comment] 2018-03-27 20:35
You managed to run the scripts and it worked immediately. The RAS value was before the binding procedure 0 or 1, but jumped to 96 during the binding procedure. Does this mean that the internal antenna is effectively broken?

**Comment by schwabe** [comment] 2018-03-27 21:29
or the firmware on the internal module just sends nonsense while binding

**Comment by mdpolasek** [comment] 2018-03-27 21:52
You are right! It's indeed an issue with the firmware of the internal module. I downgraded to firmware version to 1.4.04 (from 1.5.03) from there https://www.frsky-rc.com/horus-x12s/ and reflashed OpenTX. And now the issue went away magically :-)

**Comment by 3djc** [comment] 2018-03-28 07:37
We are in contact with FrSky on the subject, will update this thread when more info becomes available

**Comment by 3djc** [comment] 2018-03-28 09:03
It looks like your radio is fine and there might indeed  be an issue witth the iXJT firmware in the latest revision that sometime raise that alarm when it should not. My understanding is that it will be fixed in next FrOS version (and in the meantime, downgrading like you did is a perfect workaround).

**Comment by 1Sven** [comment] 2018-03-28 16:53
I hope it does not affect transmission security. I think it's very important that clarity arises here with FRSKY.

**Comment by 3djc** [comment] 2018-03-28 17:01
Why should it ? RAS is not critical anyway (many taranis do not have RAS at all (some X9, all X7,..))

**Comment by mpjf01** [comment] 2018-03-29 14:38
I have a X12S on FRSKYOS 1.5.03 and get a bind error message (SWR Warning) on that, as does everyone else I believe. It has been mentioned on RC Groups and advice is given there that is will be fixed in the next release.

**Comment by 3djc** [comment] 2018-03-29 15:37
As I said, I have talked with FrSky, they are aware of the issue, and it will be fixed in next FrOS version. Closing this issue as everythiiing has been said

**Closed as completed by 3djc** 2018-03-29 15:37 UTC

**Comment by arnovi** [comment] 2018-04-11 22:16
Hi guys,

Just updated Horus ixjt module using latest realease (1.5.04) and the RAS warning has disappeared.
I have not tested in flight but range test result is OK.

**Comment by 3djc** [comment] 2018-04-12 05:27
FrSky has confirmed me that FrTX 1.5.04 should fix this issue
