### ISSUE TITLE
CompanionV2.0.15  no S3 Poti or 6 Pos Switch  its in the T-Plus-Hardware selected

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2003] opened 2015-01-14 18:01 UTC
Companion V2.015 Taranis Plus 
At Hardware S3 selected al 6 Pos Sw or as Poti
but No S3 at Simulator

**Comment by projectkk2glider** [comment] 2015-01-14 18:11
Isn't this a duplicate of #1917?

**Comment by kilrah** [comment] 2015-01-15 09:05
Yes.

**Closed by kilrah** 2015-01-15 09:05 UTC
