### ISSUE TITLE
Source list in Input does not include Telemetry values

### ISSUE THREAD

**Issue by BurtPR** [opentx/opentx#8395] opened 2021-03-25 18:18 UTC
I use telemetry values (Curr) as a Source for an Input. I can configure these using the the transmitter interface and using Companion 2.2.4 but not using Companion 2.3.11. The Source list in Companion 2.3.11 is much smaller. 

  
[InputSourceList.zip](https://github.com/opentx/opentx/files/6206971/InputSourceList.zip)

**Comment by kilrah** [comment] 2021-03-25 19:07
Duplicate of already fixed #8271

**Closed as completed by kilrah** 2021-03-25 19:07 UTC
