### ISSUE TITLE
Link for OpenTX Companion 2.0.15 on Mac OS X is broken (HTTP 404)

### ISSUE THREAD

**Issue by xoxota99** [opentx/opentx#2055] opened 2015-02-04 04:59 UTC
Repro:
1) Go to http://www.open-tx.org/2015/01/13/opentx-2.0.15/
2) Try to download OpenTX Companion 2.0.15 for Mac OSX
3) Observe HTTP 404 error (for url http://downloads-20.open-tx.org/companion/companion-macosx-2.0.15.dmg).

**Comment by projectkk2glider** [comment] 2015-02-04 08:13
Unfortunately we don't have automatic build solution (yet) for MAC version of Companion. Therefore each release must be compiled *by hand* and the 2.0.15 for MAC was not done yet. Related issues #1482.

Also duplicate of #2049

**Closed by projectkk2glider** 2015-02-04 08:13 UTC
