### ISSUE TITLE
Set Volume From GVar

### ISSUE THREAD

**Issue by Johnex** [opentx/opentx#1841] opened 2014-11-11 12:19 UTC
Hi!
I am trying to use S2 together with SC to give S2 two uses. For switch up i have set a special function that changes the volume to the value of S2, and for switch down i have made it so GVAR1 is adjusted with the value of S2.

The problem is that since volume is taking the value directly from S2 only when the switch is in the up position, when i move the switch to the down, the volume is set to max again.

Instead i want S2 to modify 2 GVars depending on the switch position so that the values "stick", and i can make the volume function read the value from a GVar instead of the pot directly....

**Comment by kilrah** [comment] 2015-12-30 04:03
Duplicate of #2248

**Closed by kilrah** 2015-12-30 04:03 UTC
