### ISSUE TITLE
telemetry not available for inputs and mixers

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#8390] opened 2021-03-21 16:01 UTC
There is no telemetry avalilable in the source combobox both for inputs and mixers.

![image](https://user-images.githubusercontent.com/562809/111911683-d92f8700-8a66-11eb-98c5-4b4ef2d134de.png)

On the radio telemetry source can be selected.

 - OpenTX 2.3.11
 - Radiomaster TX16S
 - OpenTX Companion 2.3.11

**Comment by 3djc** [comment] 2021-03-21 16:03
Duplicate of already fixed #8271

**Closed as completed by 3djc** 2021-03-21 16:03 UTC
