### ISSUE TITLE
Batgraph not working Correctly

### ISSUE THREAD

**Issue by trashmaster9000** [opentx/opentx#2989] opened 2015-10-24 10:07 UTC
Hi,

The Batgraph isn't working Correctly.
http://fs5.directupload.net/images/151024/zrj4qnjy.png

Other Problem:
I cant Change the Battery Range in Companion and it resets every time i Update my EEPROM through Companion.

**Comment by projectkk2glider** [comment] 2015-10-24 16:48
Duplicate of #2950

**Closed by projectkk2glider** 2015-10-24 16:48 UTC
