### ISSUE TITLE
changed value with lua script has no effect

### ISSUE THREAD

**Issue by hsuq510** [opentx/opentx#6852] opened 2019-09-29 12:26 UTC
- OpenTX version 2.3 GA
 - Hardware Frsky X9D+

Changing a value with the minus button on a x9d+ has no effect, the number switch back to the previous value after release the minus button.

**Comment by 3djc** [comment] 2019-09-29 12:27
What script is that ?

**Comment by RookFPV** [comment] 2019-09-29 13:04
> What script is that ?

This problem occurs in the betaflight script,
you have to hold down the button for a long time to return to the value down.
I reported this problem and a similar one related to the crossfire script here #6840

**Comment by hsuq510** [comment] 2019-09-29 13:28
Yes, correct that the same issue

**Comment by RookFPV** [comment] 2019-10-03 18:10
Will this problem be resolved in 2.3.1?

**Comment by 3djc** [comment] 2019-10-03 18:21
We seem to have established in #6814 that the events are triggered correctly, so unless somebody diagnoses exactly what is happening in this script, it probably won’t be fixed

**Comment by RipperDrone** [comment] 2019-10-03 18:35
Issue confirmed on X9DP 2013, OTX 2.3.1N5, BF telemetry script that comes with BF4.1 or: https://github.com/betaflight/betaflight-tx-lua-scripts/releases

To replicate:
1. Flash BF 4.1 on quad
2. Flash OTX 2.3.1N5 on RC, including latest BF lua
3. Long press 'Page' to enter telemetry screen
4. Press '+' button to enter PID telemetry page
5. Navigate with +/- and edit any value by pressing 'Enter'
6. Try to decrease this value by short pressing '-'

--> Value is decreased, displayed for a fraction of a second, then automatically increased back to what it was. There seems to be a small glitch in evaluating the button press/release events correctly :-)

**Comment by 3djc** [comment] 2019-10-03 18:40
Then I suggest you try the event tester as described in #6814

**Comment by RipperDrone** [comment] 2019-10-03 18:43
@3djc Happy to do so - have downloaded both tester lua files and tried to execute on Taranis --> error 7: unexpected symbol near '>'

Am I doing it wrong?

**Comment by RookFPV** [comment] 2019-10-03 18:49
By the way. In the crossfire script, menu navigation works the other way around when you press "+" in the menu goes to "-"

**Comment by RipperDrone** [comment] 2019-10-03 18:50
@RookFPV True - but different topic. You might want to open a separate Issue report?

**Comment by RookFPV** [comment] 2019-10-03 18:52
I already opened it before but I think it was omitted, #6840

**Comment by RipperDrone** [comment] 2019-10-03 19:00
@3djc Have managed to download RAW version of lua and it executed on my X9DP 2013. +/- events are shown properly. BUT: +/- is also working ok in all BF telemetry screens, as long as you navigate only. Just when you **edit** / **decrease** any value, then '-' fails by somehow issuing a '-' first, followed by an uncommanded '+'. Pls see yourself by playing through the sequence described before... strange...

**Comment by 3djc** [comment] 2019-10-03 19:04
I cannot since I do not have a x9d(+), but clearly plus minus events seem to be ok. someone needs to investigate what is going on in the script

**Comment by RipperDrone** [comment] 2019-10-03 20:39
To update everybody here: 

Issue has to do with land of confusion caused by the plethora of supported RCs with buttons / wheels / knobs etc. OTX 2.3 has made changes to event handler which render BF Lua partly incompatible for some RCs.

OpenTX has introduced virtual events which BF lua script needs to adopt now as an abstraction layer. @raphaelcoeffic is boss on BF side and supposedly will take care of it... :-)

**Comment by RipperDrone** [comment] 2019-10-03 20:39
for an interim workaround (tested on Taranis X9DP 2013) see referenced issue #245 above.

**Comment by raphaelcoeffic** [comment] 2019-10-09 08:12
@RipperDrone I just added a fix in the BF scripts and improved the longer term solution. Please test these 2 PRs and give feedback there!

**Comment by 3djc** [comment] 2019-10-09 08:20
Closing as I have been informed by  BF team that this is resolved on their side (thx BF guys ;))

**Closed as completed by 3djc** 2019-10-09 08:20 UTC

**Comment by RipperDrone** [comment] 2019-10-09 19:21
@raphaelcoeffic happy to test. Last available Jenkins files are dated Oct 2nd, and your PRs have nnot been merged yet, so how can I download the latest lua version? Can I just download the .zip from the GitHub BF_tx_lua repository and extract all files onto my Taranis to test? Or does it need any processing/compilation and such? Have been using releases and Jenkins builds only so far... :-)

Seems @mikeller has tested the 2 PRs and confirmed on X9D+ anyway in the meantime, then pbly you don't need more tests on X9D+?

**Comment by raphaelcoeffic** [comment] 2019-10-09 22:23
@RipperDrone just copy everything in `src/` into your SD card. No processing needed here. And the more tests we have, the better it is.
