### ISSUE TITLE
Taranis X9D+ S1 not controlling Volume S2 works

### ISSUE THREAD

**Issue by boblane1949** [opentx/opentx#6072] opened 2018-07-31 20:15 UTC
**To Reproduce**
On Special Functions Screen:
Set SF1 ON Volume S2 ENABLED = S2 controls volume

BUT if you set it to S1

Set SF1 ON Volume S1 ENABLED = S1 does not control Volume, S2 still controls volume

OpenTX Companion simulator and FrSky X9D+ both do this
OpenTX 2.2.2 July 28, 2018

**Comment by 3djc** [comment] 2018-08-01 16:04
Have you checked that you don't still have an SF that keeps doing it with S2 ? Maybe a global SF ? Anyway, cannot reproduce here, closing it, but if you have more evidence of a real OpenTx issue, we will reopen it

**Closed as completed by 3djc** 2018-08-01 16:04 UTC

**Comment by boblane1949** [comment] 2018-08-01 20:21
Thank You very much for your prompt response.  Your suggestion was correct - it was set to S2 in the global settings.  My Bad - please excuse my inexperience.  Works as expected now.
