### ISSUE TITLE
Constant beep special function ? [9X/9XR]

### ISSUE THREAD

**Issue by batzkass** [opentx/opentx#2041] opened 2015-01-24 16:27 UTC
Hi,
For 9X/9XR users who don't have sound nor voice upgrades, it would be very helpful to have a constant beep custom function instead of the actual -,10,20,30,40,50,60 repetition time.
I can implement it, but the code is really heavy. At this time I had a look at the code for many hours but I didn't manage to find where I could do something. I even didn't found where the "-,10,20,30,40,50,60" parameters are set ...
Could someone help me ?

Thanks.

**Comment by kilrah** [comment] 2015-01-24 17:04
Duplicate of #1679

**Closed by kilrah** 2015-01-24 17:04 UTC
