### ISSUE TITLE
Horus model import fails

### ISSUE THREAD

**Issue by bigbobed** [opentx/opentx#4320] opened 2017-01-28 15:42 UTC
When importing models from Horus, switches don't translate correctly in SF and LS.
!SGup translates to !FM8
!SEup translates to !FM8
Problem is, only !SWA is available in the !SW selection. All others default to !FM8. All normal SWA-SWH are available.

**Comment by projectkk2glider** [comment] 2017-01-28 19:54
Might already be fixed, we need to check...

**Comment by kilrah** [comment] 2017-01-28 20:13
Yes, duplicate of #4288

**Closed by kilrah** 2017-01-28 20:13 UTC
