### ISSUE TITLE
OpenTX 2.1 fails to detect VFAS

### ISSUE THREAD

**Issue by flarssen** [opentx/opentx#2530] opened 2015-07-20 23:12 UTC
I have a FAS40 with FLVS-01 connected to D series RX, and I get no VFAS sensor. I do get "Curr" and "Cels" sensors that works, displaying the FAS current and FLVS-01 total voltage.
With my DIY sensor, sending voltage as ID 0x39, VFAS is detected but reads 0.98V instead of 9.8V

**Comment by kilrah** [comment] 2015-07-20 23:17
Duplicate of #2518.

**Closed by kilrah** 2015-07-20 23:17 UTC

**Comment by flarssen** [comment] 2015-07-21 09:35
OK, but I didn't see anything related to my ID 0x39 problem mentioned above. 1/100V instead of 1/10V is fine with me as I can just skip dividing my data by 10, but I guess it might cause problems for others.
Setting the ratio, whatever that is, to 25.7 gives correct readings. Is this the way to do it?

**Comment by kilrah** [comment] 2015-07-21 11:32
VFAS is not an official field for D series. If I remember well it was added to allow for 2 decimals, an advantage you're losing by dividing by 10.

And again some missing relevant information - what is your DIY sensor based on?

**Comment by flarssen** [comment] 2015-07-21 15:38
VFAS is documented as 0x3A and 0x3B in the FrSkys HUB protocol pdf. What's not mentioned, is that voltage should be given as half of the actual voltage. At least that's my conclusion after monitoring the FAS40 output yesterday. For a 3S lipo, I got 5E 3A 5 0 5E 5E 3B 7 0 5E = 5.7V, 10.92V on multimeter.
Probably the reason why I couldn't make sense of the 0x3A/0x3B, and choose 0x39 instead, after reading a suggestion somewhere. 

My sensor is based on the data units for the Hyperion EMeter (MDU/LDU/RDU). They give voltage with two decimals. In order to get it displayed correctly on Taranis when using ID 0x39, I had to divide this by 10, at least with 2.0.15. With 2,1, this is not necessary anymore, so something has changed. If it now works as planned, that's fine.

**Comment by kilrah** [comment] 2015-07-21 19:13
3A/3B indeed has some kind of weird ratio added to it, easy to find in opentx sources.

**Comment by projectkk2glider** [comment] 2015-07-21 19:20
The 0x3A and 0x3B has as resolution of 0.2 volts. The custom added 0x39 has a resolution of 0.1 volts.

**Comment by bsongis** [comment] 2015-07-21 19:22
Perhaps we can fix that in the sources, what do you think?

**Comment by kilrah** [comment] 2015-07-21 19:27
I don't think we can, it's due to that stupid ratio. Basically the sensor divides the value by "about 2" before sending it, so we have to multiply it by "about 2" to get the right value back and lose "about half" of the resolution as if I remember well the sensor only sends one decimal.

**Comment by projectkk2glider** [comment] 2015-07-21 19:31
I will fix this while fixing #2531

**Comment by flarssen** [comment] 2015-07-21 19:39
I changed the code of my sensor and got the full 0.01v resolution that the data source provides.
Would it be possible to switch between 0.1v and 0.01v based on the selected resolution in the telemetry page, instead of fixing it back to 0.1.
