### ISSUE TITLE
Mavlink support for 9XR PRO

### ISSUE THREAD

**Issue by marcustremonti** [opentx/opentx#3080] opened 2015-11-17 02:08 UTC
I see that there is previous support for the 9x and 9XR but it would be amazing to have it for the 9XR PRO! If this could be implemented in OpenTX Companion build options I would be, forever, grateful!

**Comment by kilrah** [comment] 2015-11-17 12:36
Duplicate of https://github.com/opentx/opentx/issues/2354

**Closed by kilrah** 2015-11-17 12:36 UTC
