### ISSUE TITLE
Companion 2.2.0 does not start

### ISSUE THREAD

**Issue by RustyPaint** [opentx/opentx#5076] opened 2017-07-02 23:49 UTC
Running from the shortcut, nothing starts, and no error messages are given.

Running it in vs2015 community edition debugger gives this:

Exception thrown at 0x66AF9E46 (Qt5Core.dll) in companion.exe: 0xC0000005: Access violation reading location 0x05000004.

This is running on Windows 10 with all updates installed.

**Comment by RustyPaint** [comment] 2017-07-02 23:55
Downloading the QT SDK and copying over the DLLs used (and PDBs) shows that it is throwing the excption in:

>	Qt5Core.dll!QSettings::value(const QString & key, const QVariant & defaultValue) Line 3305	C++

**Comment by RustyPaint** [comment] 2017-07-03 01:33
Well... managed to build a debug build of Companion on my system.  Debug ran just fine.  And now the production version starts up just fine.

**Comment by K2AAE** [comment] 2017-07-13 19:24
This sucks, mine fails on Qt5Core.dll

**Comment by K2AAE** [comment] 2017-07-13 21:18
ANd then I find all the issues are caused by crap left in the windows registry by the 'Uninstaller'

**Comment by projectkk2glider** [comment] 2017-07-24 15:12
This might be a QT bug.

**Comment by kilrah** [comment] 2017-07-24 16:00
I think these crashes originate from a problem when importing settings from previous versions.

**Comment by RustyPaint** [comment] 2017-07-25 02:00
The previous version on my system is 2.0.19

**Comment by mpaperno** [comment] 2017-11-12 23:29
Duplicate of #5016, fixed a while ago in 655e2f9.

**Closed as completed by mpaperno** 2017-11-12 23:29 UTC
Labels: Bug, Companion, OpSys-Windows
