### ISSUE TITLE
[Bug][OpenTX 2.1.6] False "Model ID already used" warning

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#3098] opened 2015-11-24 09:05 UTC
Hi folks,

Here is the steps to reproduce the problem:

1. Create a **1st model** with the following RF parameters:
 * Internal Radio System: D16 / Ch: 1-8 / Receiver No. 2
 * External Radio Module: OFF
2. Change the RF parameter of the **1st model**:
 * Internal Radio System: OFF
 * External Radio Module: D16 / Ch: 1-8 / Receiver No. 3
3. Create a **2nd model** with the following RF parameters:
 * Internal Radio System: D16 / Ch: 1-8 / Receiver No. 2
 * External Radio Module: OFF

At this point you will get the warning **"Model ID already used"**.
Look like the receiver number are check without taking in account if the RF module is effectively ON or OFF.

**Comment by griebd** [comment] 2015-11-24 11:50
Yes, we now :wink:. This one is a duplicate of #2187. Closing this one as there are more info on and discussion going on there.

**Closed by griebd** 2015-11-24 11:50 UTC

**Comment by LapinFou** [comment] 2015-11-24 12:48
OK. I missed this one. The issue title was misleading (talking about DSMx).
:smiling_imp:

**Comment by griebd** [comment] 2015-11-24 14:38
Sure, I though so, don't worry!
