### ISSUE TITLE
adding a multimodule to turnagy 9xr

### ISSUE THREAD

**Issue by poporbit** [opentx/opentx#5245] opened 2017-09-27 14:23 UTC
The Multimodule option is not present for the 9xr but is available for the 9xrpro.  Is this due to hardware limitations or was that missing module an over site?

**Comment by powercycle** [comment] 2017-09-27 14:45
I'm not completely sure of my memory here, but I believe development for 9xr stopped just before multimodule.  You can use er9x and it has support for multimodule.

**Comment by schwabe** [comment] 2017-09-27 15:37
Duplicate of #3812, see that for more details (and continue there)

**Closed as completed by schwabe** 2017-09-27 15:37 UTC
