### ISSUE TITLE
sky9x strange sound and vocal behaviour after upgrade for multimode

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [opentx/opentx#6395] opened 2019-04-17 18:03 UTC
hello
i need some help
i've been using my sky9x for many years now and recently had to upgrade to be able to use pascal langer's multimodule 
thanks to windows 10 faulty autoupgrade lost samba1.1 and was really a pain to upgrade radio then companions versions step by step as climbing  a ladder
now i'm on companion2.2 and actual last summer version of firmware
i'm using on ppm1 a diy frsky d8mode module and a rs232/ttl converter but didin't changed any hardware since sky9x has been built
now when i'm flying slope i'm losing telemetry announces (vocal and vario) in the few minutes of the flight
if i reset radio by rebooting the system reworks for  a few
i had to reprogram sound calls since voice and sound packs have changed
i tried to upgrade to 2.3 companion as proposed but installation went wrongly with errors and without samba , after reinstall manually samba, i can read models and settings but can't upgrade firmware anymore with samba 
is someone   experimented the same
thanks for help ,

**Comment by kilrah** [comment] 2019-04-18 03:50
Duplicate of #6394. Please don't use the bug tracker for usage questions.

**Closed as completed by kilrah** 2019-04-18 03:50 UTC
