### ISSUE TITLE
Companion telemetry simulator not usable with "real" sensors on 2.3

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#6862] opened 2019-09-30 09:44 UTC
Lacks support for keeping the source intact and feeding the same one

**Comment by offer-shmuely** [comment] 2019-10-09 05:05
can you tag it with “companion” label?

**Comment by George-111** [comment] 2019-11-08 17:02
I'm getting the same issue with Companion 2.3.1, simulating telemetry of my QX7S under Windows 10 1903. 
None of the manually entered telemetry values for RSSI, RxBt, Cels, Alt etc. are posted to the simulated radio or logical switches with checked "Simulate".

**Comment by T3chDad** [comment] 2020-01-06 16:21
Telemetry simulator not working in 2.3.4.  Multiple, radio profiles, multiple models.  Windows 10 1903 or  Insider 15936.

**Comment by kilrah** [comment] 2020-01-06 17:42
Yeah that's the whole point of this ticket.

**Comment by offer-shmuely** [comment] 2020-01-06 18:22
Is there estimation for a fix?

**Comment by T3chDad** [comment] 2020-01-06 18:30
> Yeah that's the whole point of this ticket.

My apologies, I was just verifying this issue still exists in the stable version released in mid December.  It pretty much makes LUA debugging impossible.  Thank you for your efforts.

**Comment by guillaumevaret** [comment] 2020-01-27 09:10
Hi everybody. I will add some elements for the diagnostic of the problem.
 - post #7328 : french duplicate of this one with more infos, telemetry problems :  it seems that it's RSSI 248 that is wrong => should be RSSI 25 to makes works all the others sensors.
  - post #7327, telemetry transfers through companion and directly go back through the radio. The edition of each sensor, changing the type and put it back fix the problem 1
 
the instance of the ID can take the (0 to100) values when just discovered or in companion, but goes from 1 to 32 in opentx. 

from the 2.3.6 companion, different vues of the 2 sames sensors in the
- telemetry tab on companion
- telemetry simulator on companion
- simulator of opentx edition on companion
- simulator of telemetry tab on companion

![Sans-titre-2](https://user-images.githubusercontent.com/48926221/73161913-e3692600-40ec-11ea-8b8e-c7c986e0a437.jpg)



so it seems that the problem come from the conversion of the ID number + instance  (telemetry tab on companion and principal telemetry screen on opentx) into a unique ID number (simulator on companion and edition of sensor on opentx)
-  removing sometimes 1 to the unique ID number.
-  taking the instance for unique ID  number instead of ID number

**Comment by gastolectric** [comment] 2020-01-30 06:18
For anyone else following this 'issue' - I have found that amending the reference value in the telemetry simulator to match the "Instance" ID's on the telemetry menu page resolves the issue of telemetry not simulating in Companion 2.3.x for Horus radios. 

<img width="1440" alt="Screen Shot 2020-01-30 at 5 10 31 pm" src="https://user-images.githubusercontent.com/60124074/73424959-5b9d4900-4384-11ea-8fbc-37ff70952ed9.png">

This is only a partial solution because each time you close the Simulator and re-open it, the value changes are lost and have to be re-entered each time you run the sim...

**Comment by LapinFou** [comment] 2020-01-30 10:01
If this can be any helpful, it seems there is an offset of 223 on all instances. After lunching the simulator, if you do the subtraction of -223, the sensor will work.
It has been found by a French guy here: [#107929](http://frskytaranis.forumactif.org/t9810-probleme-simulateur-telemetrie-companion-2-3-4#107929)

**Comment by guillaumevaret** [comment] 2020-01-30 13:05
On the side of the horus, each time I transfer my model to the radio,  I have a problem with all the sensors in ID 1 not recognized anymore (so ID224 coming from the PX4), I edit the sensor and double enter on the "type", it fix the problem and put back the ID on the telemetry screen to 0 (=> ID = 1 on the ID edit).

**Comment by sam2b** [comment] 2020-02-10 23:44
@LapinFou thanks for attention on this! At least there is a workaround for now. :) 👍

**Comment by offer-shmuely** [comment] 2020-04-10 11:16
any estimation for a fix?
we currently need to debug widgets on companion 2.2, 
however the X10 itself is on an other version (2.3.7)

**Comment by 3djc** [comment] 2020-04-10 11:20
Should be ok in 2.3.7

**Comment by offer-shmuely** [comment] 2020-04-11 10:09
(edited) yes, looks like it working ok

**Comment by offer-shmuely** [comment] 2020-10-10 05:25
this issue not need to be stale
it working very good, no issues anymore

can be closed

**Closed as completed** 2020-10-10 06:12 UTC
Labels: Companion
