### ISSUE TITLE
Open TX Horus 2.2 ON352 - Flight mode trim assignments not working

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#3927] opened 2016-10-17 17:35 UTC
Example, selecting trim from another flight mode + own trim as offset. This function does not appear to work.

**Comment by kilrah** [comment] 2016-10-17 17:49
I have a model set up that uses this config and have no issue.

You should update your firmware to the current build before reporting issues, especially as it's still pre-release there are many bugs that get solved everytime, you're 4 builds behind.

**Comment by clivemartin** [comment] 2016-10-17 18:10
Sorry, will update to 358

**Comment by clivemartin** [comment] 2016-10-17 19:02
Still have an issue despite updating to 358.  If cross trims are selected in Input menu (elev trim on Thr trim) then the fault as detailed above holds.

**Comment by kilrah** [comment] 2016-10-17 19:08
Please post a non-working setup (ideally the .bin file of that model on the SD card).

**Comment by projectkk2glider** [comment] 2016-10-30 14:52
Could this #170 be related?

**Comment by projectkk2glider** [comment] 2017-01-14 14:11
Duplicate of #170

**Closed by projectkk2glider** 2017-01-14 14:11 UTC
Labels: Horus, Needs more data
